
<h2>3 4, 1797</h2>""<p>John Adams is inaugurated as the second President of the United States in Philadelphia. Thomas Jefferson will serve as Vice President.</p>
<h2>5 15, 1797</h2>""<p>Adams calls the first special session of Congress to debate the mounting crisis in French-American relations.  Charles Cotesworth Pinckney, the American envoy in France, had left France after being insulted by the French foreign minister.</p>
<h2>5 19, 1797</h2>""<p>Adams appoints a three man commission, composed of Charles C. Pinckney, Elbridge Gerry, and John Marshall, to negotiate a settlement with France.</p>  
<h2>6 24, 1797</h2>""<p>President Adams is authorized by Congress to raise a militia of 80,000 men for defensive purposes in case of war with France.</p> 
<h2>10 18, 1797</h2>""<p>The three man American peace commission is received coolly and then asked to pay a bribe in order to speak with French Foreign Minister Charles Maurice Talleyrand. This episode becomes known as the "XYZ Affair." </p>   
<h2>1 8, 1798</h2>""<p>The Eleventh Amendment to the Constitution of the United States is declared in full force by President Adams.  It stipulates that federal courts shall not have the jurisdiction over litigation between individuals from one state against individuals from another state. </p>
<h2>4 3, 1798</h2>""
<p>President Adams exposes the XYZ affair, providing Congress with letters from the peace commission indicating French efforts to bribe and intimidate U.S. officials seeking to speak with French diplomat, Charles Maurice Talleyrand. The reaction was one of outrage and intimidation. </p>  
<h2>4 7, 1798</h2>""<p>Congress establishes the government for the new Mississippi Territory. The Spanish had ceded the territory to the United States in the 1795 Treaty of San Lorenzo.  President Adams appoints native Winthrop Sergeant as governor and selects the town of Natchez to serve as its first capital. </p>   
<h2>5 3, 1798</h2>""<p>Adams appoints Benjamin Stoddert to serve as the first secretary of the Navy for the newly formed Department of the Navy. Congress had established the department four days earlier in preparation for war with France. </p>  
<h2>5 28, 1798</h2>""<p>Congress empowers Adams to enlist 10,000 men for service in case of a declaration of war or invasion of the country's domain. It also authorizes Adams to instruct commanders of ships-of-war to seize armed French vessels praying upon or attacking American merchantmen about the coast. </p>
<h2>6 18, 1798</h2>""<p>The first of four acts known collectively as the Alien and Sedition Acts is adopted. The Alien and Sedition acts aimed to curb criticism of administration policies and prevent internal subversion. The first act, stipulating requirements for naturalized citizenship, demanded residence in the United States for period of fourteen years and a declaration of intention for five years. </p>  
<h2>6 25, 1798</h2>""<p>Congress passes the Alien Act, granting President Adams the power to deport any alien he deemed potentially dangerous to the country's safety. </p>
<h2>7 6, 1798</h2>""<p>Congress passes the third of the Alien and Sedition acts, the Alien Enemies Act. The act provides for the apprehension and deportation of male aliens who were subjects or citizens of a hostile country. </p>   
<h2>7 7, 1798</h2>""<p>Adams appoints George Washington to serve as commander in chief of the United States Army. All French treaties between the United States and France are declared null and void by vote in Congress, most notably the 1778 Treaty of Alliance. </p>
<h2>7 14, 1798</h2>""<p>Congress adopts the Sedition Act, the fourth and last of the Alien and Sedition acts. The bill subjects any American citizen to a fine and/or imprisonment for obstructing the implementation of federal law, or for publishing malicious or false writings against Congress, the President, or the government. </p>   
<h2>9 12, 1798</h2>""<p>Philadelphia newspaper editor Benjamin Franklin Bache, grandson of Benjamin Franklin, is arrested under Sedition Act for "libeling" President Adams. </p>
<h2>11 16, 1798</h2>""<p>The Kentucky State Legislature adopts the Kentucky Resolutions, reserving states' right to override federal powers not enumerated in the U.S. Constitution. Thomas Jefferson, angry at the Adams administration for the Alien and Sedition acts, authors the resolution. </p>   
<h2>2 9, 1799</h2>""<p>The United States Navy scores its first clear victory against France when the frigate <i>Constellation</i> captures the French ship <i>L'Insurgente</i> near the island of St. Kitts. </p>   
<h2>3 30, 1799</h2>""<p>President Adams selects Van Murray, Chief Justice Oliver Ellsworth, and North Carolina Governor Davie to serve as U.S. envoys to France upon assurance from the French that they will be received with the respect owed to their nation. </p>
<h2>7 11, 1799</h2>""<p>U.S. diplomats conclude a Treaty of Amity between the United States and Prussia in Berlin. </p>   
<h2>10 26, 1799</h2>""<p>Thomas Cooper, a resident of Northumberland, Pennsylvania, is tried and convicted of libel against President Adams and his administration under the newly adopted Sedition Act. </p>   
<h2>1 10, 1800</h2>""<p>Congress finally passes a treaty with Tunis, negotiated originally in 1797. </p>   
<h2>2 1, 1800</h2>""<p>The United States frigate <i>Constellation</i> defeats the French ship <i>La Vengeance</i> on the high seas. </p>   
<h2>4 4, 1800</h2>""<p>Congress passes and Adams signs into law the Federal Bankruptcy Act, providing merchants and traders protection from debtors. </p>    
<h2>4 24, 1800</h2>""<p>A resolution is passed and eventually signed by President Adams calling for the establishment of a Library of Congress. </p>    
<h2>5 7, 1800</h2>""<p>Congress passes an act dividing the Northwest Territory into two parts, with the border between them running north from the junction of the Ohio and Kentucky Rivers. The western part of the territory will be known as the Indiana Territory while the eastern half will retain the name Northwest Territory. </p>  
<h2>6 , 1800</h2>""<p>The new city of Washington in the District of Columbia becomes the official capital of the United States, succeeding Philadelphia. It would not be until November that Congress convened in the new capital and Adams moved into the new Executive Mansion. </p>  
<h2>9 30, 1800</h2>""<p>The "quasi"-naval war with France effectively ends with the signing of the Treaty of Mortfontaine in Paris.  France agrees to lift its embargos on American ships, cancel all letters of marque, and respect neutral ships and property. The United States agrees to return captured warships but not captured privateers. </p>  
<h2>10 1, 1800</h2>""<p>Spain cedes the Louisiana territory to France with the signing of the secret Treaty of San Idlefonso. Leaders express alarm because the French could be a potentially dangerous enemy in the region. </p>
<h2>11 11, 1800</h2>""<p>The fourth presidential election is held. Adams, the Federalist Party candidate, loses his bid for reelection. A tie in electoral votes between Thomas Jefferson and Aaron Burr throws the election into the House of Representatives, with Jefferson emerging the winner. </p>  
<h2>3 4, 1801</h2>""<p>Thomas Jefferson is inaugurated as the third President of the United States, becoming the first President to be inaugurated in Washington, D.C. John Adams's term as President officially ends. </p>   
