
<h2>3 4, 1889</h2>""<p>Republican Benjamin Harrison is inaugurated as the twenty-third President after losing the popular vote to Grover Cleveland. The Republicans hold small majorities in both houses of Congress, making this the first time since 1875 that Republicans control both Congress and the White House.</p>
<h2>3 7, 1889</h2>""<p>The Harrison Cabinet meets for the first time. It decides against the use of an informal "Kitchen Cabinet" and criticizes the practice of "senatorial courtesy" and the spoils system. Secretary of State James G. Blaine serves as a prominent figure in Harrison's core group, campaigning heavily for American interests in Latin America and Hawaii. </p>
<h2>4 29, 1889</h2>""<p>The Berlin Conference on Samoan Affairs begins, with the United States, Germany, and the United Kingdom attempting to bring peace to the troubled area. The conference will conclude with the making of a treaty, "The Final Act of the Berlin Conference on Samoan Affairs," which declares the neutrality and nominal independence of Samoa while creating a three-power protectorate over the islands. Secretary of State Blaine handles the negotiations. </p>
<h2>5 3, 1889</h2>""<p>Harrison invites Theodore Roosevelt to the White House and appoints him Civil Service Commissioner on May 7. Roosevelt, a reform Republican from New York, heads the department until 1895. </p>
<h2>8 6, 1889</h2>"8 16, 1889"<p>Building on the work of President Arthur, Harrison tours New England and reveals plans for an expanded merchant marine and two-ocean Navy. Expansion of the Navy will be a distinguishing feature of Harrison's presidency. </p>
<h2>10 2, 1889</h2>""<p>Secretary of State Blaine initiates the first Pan-American Conference, primarily to increase U.S. commercial interests in Latin America. Blaine hopes to heighten the American presence in Latin America to the detriment of Britain. </p>
<h2>11 2, 1889</h2>""<p>North and South Dakota join the Union as the thirty-ninth and fortieth states. </p>
<h2>11 8, 1889</h2>""<p>Montana becomes the forty-first state. </p>
<h2>11 11, 1889</h2>""<p>Washington is admitted as the forty-second state. </p>
<h2>12 3, 1889</h2>""<p>Harrison sends his first message to Congress. Among his recommendations are civil rights and civil service reform, naval legislation, improved conditions for railroad workers, and pensions for veterans. </p>
<h2>12 4, 1889</h2>""<p>Harrison nominates David J. Brewer to the Supreme Court. The Senate approves the choice two weeks later. </p>
<h2>6 27, 1890</h2>""<p>The Dependent Pension Bill is passed, providing benefits to Union veterans as well as to their children and widows. Former President Cleveland vetoed the same bill three years earlier. By 1907, the law will have cost the government more than a billion dollars. </p>
<h2>7 2, 1890</h2>""<p>The Sherman Anti-Trust Act is enacted, forbidding business practices that restrain trade and commerce or attempt to create monopolies. Until the presidency of Theodore Roosevelt, the government will rarely invoke the law: between the act's inception and 1901, only eighteen antitrust suits appear, with four of them coming against labor unions. </p>
<h2>7 3, 1890</h2>""<p>Idaho is admitted as the forty-third state. </p>
<h2>7 10, 1890</h2>""<p>Wyoming is admitted as the forty-fourth state. </p>
<h2>7 14, 1890</h2>""<p>Harrison signs into law the Sherman Silver Purchase Act after convincing free silver senators to compromise on the legislation. Support comes from farmers who argue that increased silver coinage will inflate the currency supply and raise prices, as well as from leaders of new western states with silver mines. The law permits the Treasury to buy 4.5 million ounces of silver each month, doubling the previous purchase amount. Nevertheless, the bill has little effect on the economy. </p>
<h2>7 29, 1890</h2>""<p>Harrison sends a special message to Congress in which he requests legislation to ban lottery ticket sales by mail. </p>
<h2>9 2, 1890</h2>""<p>Congress passes the Anti-Lottery Bill proposed by John Caldwell of Ohio. It is signed into law on September 19. </p>
<h2>10 1, 1890</h2>""<p>Congress passes the McKinley Tariff, introduced by Ohio Senator William McKinley, future President of the United States. Average duties on manufactured goods are increased to 49.5 percent. It is the most controversial legislation passed during Harrison's term, greatly expanding the power of the President in foreign trade. A section of the tariff allows the President to negotiate reciprocity agreements for certain commodities. Secretary of State Blaine endorses this portion of the bill, believing it will enable Harrison to influence Latin American countries to lower rates on American exports. In June, Harrison will sign several such accordance agreements. </p>
<h2>11 7, 1890</h2>""<p>The mid-term elections result in a Democratic sweep of the House, while in the Senate the Republican majority falls to eight. The Democratic victory reflects society's displeasure with the higher tariffs imposed by the McKinley Tariff. </p>
<h2>12 29, 1890</h2>""<p>Harrison appoints Henry B. Brown to the Supreme Court. </p>
<h2>3 3, 1891</h2>""<p>Harrison signs a historic measure creating nine Circuit Courts of Appeals. The new Courts are set up to relieve the demands on the Supreme Court. </p>
<h2>3 14, 1891</h2>""<p>A mob in New Orleans lynches eleven Italian immigrants from Sicily, resulting in Italy severing its diplomatic ties to the United States and threatening war. Those murdered are among a group of nineteen Italian immigrants indicted for the murder of police chief David C. Hennessey. Amidst allegations of threats and bribes to the jury, all nineteen had been cleared. The incident helps usher the word "mafia" into common parlance. </p>
<h2>5 6, 1891</h2>""<p>Responding to a request from the Balmaceda government of Chile, the United States seizes a Chilean rebel ship, the <i>Itata</i>, as it is carrying an arms shipment from San Diego. The rebels eventually defeat the Balmaceda government in a civil war, leading to the emergence of tense relations between the United States and Chile. </p>
<h2>10 16, 1891</h2>""<p>A brawl between American sailors and Chilean nationals in Valparaiso, Chile, results in the deaths of two Americans and many arrests. Tensions between the United States and Chile escalate, and many fear the outbreak of war between the two nations. </p>
<h2>12 9, 1891</h2>""<p>In his annual message to Congress, Harrison denounces the Valparaiso attack as "savage, brutal, unprovoked." </p>
<h2>12 16, 1891</h2>""<p>Harrison nominates Stephen B. Elkins as the new secretary of war. </p>
<h2>1 1, 1892</h2>"1 20, 1892"<p>Harrison states that all members of his cabinet are in favor of war with Chile. During the first three weeks of January, Secretary of State Blaine is the only cabinet member arguing against an ultimatum. </p>
<h2>1 21, 1892</h2>""<p>The United States sends an ultimatum to Chile. </p>
<h2>1 25, 1892</h2>""<p>In a special message to Congress, Harrison asks that lawmakers take "appropriate action" regarding Chile. </p>
<h2>1 26, 1892</h2>""<p>Chile backs down in the conflict. Ultimately, it pays an indemnity of $75,000. </p>
<h2>5 23, 1892</h2>""<p>Harrison decides to run for re-election; party bosses oppose him. </p>
<h2>6 4, 1892</h2>""<p>Secretary of State Blaine resigns. His disagreements with the President have increased. Additionally, Blaine has grown increasingly ill and will die less than eight months after leaving office. </p>
<h2>6 7, 1892</h2>"6 10,1892"<p>Harrison is nominated on the first ballot at the Republican National Convention in Minneapolis. Whitelaw Reid of New York is nominated as his running mate. </p>
<h2>6 23, 1892</h2>""<p>The Democrats nominate Grover Cleveland and Adlai E. Stevenson. </p>
<h2>7 6, 1892</h2>""<p>After being locked out over a contract dispute, steel workers at the Homestead plant (part of Carnegie Steel) in Pennsylvania fight with men from the Pinkerton Detective Agency, who have been brought in to bust the strike. Seven Pinkertons and nine workers die. Six days later, 8,000 militiamen accompany and protect the Pinkerton men. </p>
<h2>7 11, 1892</h2>""<p>Silver miners at Coeur d'Alene, Idaho, go on a violent strike. Thirty men are killed as they fight non-union help. Harrison sends in federal troops to restore order. </p>
<h2>7 30, 1892</h2>""<p>Harrison privately supports mediation in the Homestead Steel Strike and sends Whitelaw Reid as an emissary to Henry Clay Frick, the man whom Carnegie has left in charge of Homestead. This proves to be fruitless; the strike lasts five months, breaks the union, and deals a major blow to organized labor. When the strike ends on November 20, Carnegie realizes his major aim as the union is virtually destroyed. </p>
<h2>10 25, 1892</h2>""<p>After suffering from tuberculosis, Harrison's wife dies. </p>
<h2>11 8, 1892</h2>""<p>Garnering 43 percent of the popular vote, Harrison is defeated by Grover Cleveland, who gains 46 percent in the presidential election. Cleveland receives 277 electoral votes to Harrison's 145. </p>
<h2>1 17, 1893</h2>""<p>Queen Liliuokalani of Hawaii is deposed on January 17, with a provisional government being established under Sanford B. Dole. News of the revolt reaches Washington on January 29. Harrison responds by deploying 150 marines to Hawaii to protect the new government. </p>
<h2>2 16, 1893</h2>""<p>Harrison sends a treaty to the Senate requesting "full and complete" annexation of Hawaii. The Senate, intensely divided, refuses to act. </p>
<h2>3 4, 1893</h2>""<p>Grover Cleveland is inaugurated as President, and Harrison returns to Indianapolis. </p>
