
<h2>1 20, 1989</h2>""<p>George H. W. Bush is inaugurated as the forty-first President.</p> 
<h2>2 6, 1989</h2>""<p>President Bush, at a White House press conference, introduces his bail-out plan for troubled savings and loans banks. It provides for the sale of $50 billion in government bonds to finance the bail-out and gives the Federal Deposit Insurance Corporation (FDIC) regulatory oversight over S&Ls. </p>
<h2>3 14, 1989</h2>""<p>The Bush administration, at the urging of federal drug czar, William Bennett, announces a temporary ban on the importation of semi-automatic rifles, a reversal of President Bush's earlier statements indicating that no restriction on these firearms would be enacted. </p>  
<h2>3 24, 1989</h2>""<p>In the worst oil spill on American territory, the <i>Exxon Valdez</i> supertanker runs aground in southeastern Alaska. The tanker dumps 240,000 barrels of oil into the surrounding waters and causes extensive environmental damage. </p>
<h2>4 17, 1989</h2>""<p>President Bush offers a program of special assistance for Poland, whose Communist government has agreed to negotiations with the opposition Solidarity party which produce a plan for free elections. Elections are held in August, 1989, which lead to the end of single-party rule in Poland. </p>
<h2>6 4, 1989</h2>""<p>The People's Liberation Army, the military arm of the Chinese government, uses tanks and armored cars to suppress a burgeoning pro-democracy movement that had encamped in Beijing's Tiananmen Square. Estimates on the number of demonstrators killed vary between 700 and 2,700. </p>
<h2>6 5, 1989</h2>""<p>In the wake of the Tiananmen Square massacres, President Bush announces a number of condemnatory actions, including the suspension of the sale of American weapons to China. </p>
<h2>8 9, 1989</h2>""<p>President Bush signs into law the Financial Institutions Reform, Recovery, and Enforcement Act of 1989, a compromise with Congress on the bail-out of savings and loans. This law differs from Bush's February 6 proposal of financing the bail-out from the Treasury Department through the sale of bonds. It offers $166 billion worth of aid to troubled savings and loans institutions and creates a new government body, the Resolution Trust Company, to oversee the merger or liquidation of troubled banks. </p>
<h2>11 9, 1989</h2>""<p>The Berlin Wall falls, marking the symbolic end of Communist rule in Eastern Europe. </p>
<h2>11 17, 1989</h2>""<p>President Bush signs the Fair Labor Standards Amendments of 1989, which by April 1991 would raise the minimum wage to $4.25 an hour. The law was a significant victory for Bush over congressional Democrats, who in the spring of 1989 passed a bill, which President Bush vetoed on June 13, that raised the minimum wage to $4.55. </p>   
<h2>11 21, 1989</h2>""<p>President Bush signs a new anti-drug law that provides more than $3 billion for expanded anti-drug programs, including treatment facilities, federal prison expansion, education, and law enforcement. </p>    
<h2>12 2, 1989</h2>"12 3, 1989"<p>President Bush and Soviet President Mikhail Gorbachev hold their first meeting of Bush's presidency in the harbor of Valetta, Malta, to discuss nuclear disarmament and the strengthening of Soviet-American trade relations. Both leaders announce that the Cold War is effectively over. </p>
<h2>12 20, 1989</h2>""<p>American armed forces invade Panama to capture Manuel Antonio Noriega, the country's military dictator. Noriega, who had been indicted in the United States on drug trafficking charges, surrendered on January 3, 1990. He was convicted on drug charges on April 9, 1992, and sent to prison. </p>   
<h2>6 1, 1990</h2>""<p>At a summit meeting in Washington, D.C., President Bush and Soviet President Mikhail Gorbachev sign the broadest arms reduction agreement in two decades. The agreement stipulates that the United States and the Soviet Union scrap 25 percent and 40 percent of their respective nuclear stockpiles. </p>
<h2>6 26, 1990</h2>""<p>President Bush, in a written statement released to the press, reneges on his "no new taxes" pledge from the 1988 presidential campaign by stating that in order to solve the deficit problem, tax increases might be necessary for the 1991 fiscal year. </p>
 
<h2>7 26, 1990</h2>""<p>President Bush signs the Americans with Disabilities Act, which affects over 43 million Americans and forbids discrimination in employment, public accommodations, and transportation. </p>
<h2>8 2, 1990</h2>""<p>Iraq invades Kuwait. President Bush strongly condemns Iraq's actions, setting the stage for an American response. </p>
<h2>10 3, 1990</h2>""<p>Seven months after East Germans overwhelmingly approve reunification, the two German states are formally reunited. </p>
<h2>10 22, 1990</h2>""<p>President Bush vetoes the Civil Rights Act of 1990, stating that the bill would "introduce the destructive force of quotas into our nation's employment system." </p>   
<h2>11 5, 1990</h2>""<p>President Bush signs a budget law intended to 						reduce the federal budget by almost $500 billion 						over the next five years. The law includes $140 						billion dollars in new taxes. </p>
<h2>11 8, 1990</h2>""<p>President Bush increases the number of American troops in Saudi Arabia to 400,000. </p>
<h2>11 15, 1990</h2>""<p>President Bush signs the Clean Air Act of 1990, which tightens air pollution standards and seeks to reduce urban smog, cut acid rain pollution by one-half, and eliminate industrial emissions of toxic chemicals by the end of the 20th century.  </p>
<h2>11 19, 1990</h2>""<p>The United States, Canada, and twenty other European nations sign the Conventional Forces in Europe Treaty (CFE). The CFE limits NATO and Warsaw Pact weapons holdings and caps the American troop presence in Central Europe at 195,000. </p>
<h2>11 29, 1990</h2>""<p>President Bush signs the Immigration Act of 1990, the most extensive revision to immigration law in more than a half century. The new law allows for the admission of 700,000 aliens each year.  </p>
<h2>1 17, 1991</h2>""<p>The Persian Gulf War, code-named Operation Desert Storm, begins with a massive, American-led air attack on Iraq. </p>
<h2>2 24, 1991</h2>""<p>Ground troops, including a large contingent of American soldiers, begin operations in Operation Desert Storm. </p>
<h2>2 27, 1991</h2>""<p>After liberating Kuwait, coalition troops advance rapidly into Iraqi territory, encountering no resistance. President Bush, deciding that the war's objectives had been met, calls off the ground offensive. </p>
<h2>7 10, 1991</h2>""<p>President Bush lifts most American sanctions against the Republic of South Africa, saying that the movement to end apartheid is now "irreversible." </p>   
<h2>7 31, 1991</h2>""<p>President Bush and Mikhail Gorbachev meet in Moscow to sign a nuclear arms reduction treaty (START-I) which calls for both nations to make significant reductions in the number of nuclear warheads in their respective arsenals. </p>  
<h2>10 15, 1991</h2>""<p>Clarence Thomas, President Bush's nominee to replace retiring justice Harry A. Blackmun on the Supreme Court, is confirmed by the Senate in a close 52-48 vote. Thomas' confirmation hearings focus on charges of sexual harassment made by Anita F. Hill, a law professor and former colleague of Thomas. </p>
<h2>11 21, 1991</h2>""<p>President Bush signs the Civil Rights Act of 1991, making it easier for employees to sue employers on grounds of discrimination. </p>
<h2>12 31, 1991</h2>""<p>The constituent republics of the Soviet Union dissolve the Union of Soviet Socialist Republics. </p>
<h2>1 10, 1992</h2>""<p>The Labor Department announces that the unemployment rose to 7.1 percent in December 1991, the highest mark in over five years. </p>   
<h2>2 1, 1992</h2>""<p>At the presidential retreat at Camp David, Maryland, President Bush and Russian president Boris Yeltsin meet to discuss U.S.-Russian relations and officially declare the end of the Cold War. </p>
<h2>2 18, 1992</h2>""<p>President Bush wins the New Hampshire primary but faces a strong challenge from conservative media personality Patrick Buchanan. The conservative wing of the Republican Party supports Buchanan, revealing a division within the party. </p>
<h2>4 1, 1992</h2>""<p>President Bush announces an aid plan of $24 billion to spur democratic and a free market reforms in the former Soviet Union. </p>
<h2>5 23, 1992</h2>""<p>The United States signs agreements with Russia, Belarus, Ukraine, and Kazakhstan, ensuring the continued participation of these nations in the nuclear arms reduction treaties signed by the U.S.S.R. before its collapse in late 1991. </p>
<h2>6 12, 1992</h2>""<p>Speaking at the Earth Summit in Rio de Janeiro, Brazil, President Bush announces that the United States will not sign a treaty designed to protect rare and endangered animals and plants, saying that it would retard the development of technology and the protection of ideas. The United States does sign the Framework Convention on Climate Change aimed at preventing further global warming. </p>
<h2>6 16, 1992</h2>""<p>President Bush and President Yeltsin announce an agreement by which the United States and Russia reduce their nuclear warheads to between 3,000 and 3,500 by the year 2003. </p>
<h2>6 22, 1992</h2>""<p>President Bush signs a supplemental appropriations act that provides aid to inner cities, specifically Los Angeles, which is trying to recover from the Rodney King riots of April 1992. </p>  
<h2>7 3, 1992</h2>""<p>President Bush signs the Unemployment Compensation Amendments of 1992, extending coverage to the unemployed for 26 weeks, following their initial 26 weeks of benefits. The previous day, the Labor Department announced that the unemployment rate had reached 7.8 percent, its highest level since 1984. </p>
 
<h2>8 19, 1992</h2>"8 20, 1992"<p>The Republican Party nominates President George Bush for a second term as President. The party also re-nominates Vice-President Dan Quayle. There is some evidence that the Bush team had considered replacing Quayle on the Republican ticket. </p>
<h2>11 3, 1992</h2>""<p>Arkansas Governor Bill Clinton, a Democrat, is elected President after defeating President Bush and Ross Perot, an independent from Texas. Clinton wins 43 percent of the vote and 370 Electoral College votes, to Bush's 38 percent and 168, and Perot's 19 percent and 0. </p>
<h2>12 9, 1992</h2>""<p>American troops land in Somalia as part of the UN-sponsored "Operation Restore Hope." The humanitarian mission's first goal was to ensure the distribution of food and medical aid and supplies to suffering Somalis. Somalia had been wracked by starvation, drought, and violence. </p>
<h2>1 20, 1993</h2>""<p>President Bush and his wife Barbara fly home to Houston, Texas. </p>
