
<h2>8 3, 1923</h2>""<p>At a 2:30 a.m. ceremony in Plymouth, Vermont, Calvin Coolidge is sworn in by his father as the thirtieth President of the United States.</p>
<h2>9 15, 1923</h2>""<p>Governor J. C. Walton places Oklahoma under martial law in order
to suppress the increasing terrorism of the Ku Klux Klan, which has reemerged in the South and Midwest in response to worsening economic conditions. </p>
<h2>12 6, 1923</h2>""<p>In his first State of the Union address, Coolidge expresses his support for prohibition and U.S. involvement in the World Court. He also states his opposition to government interference with business and calls for lowering taxes, thereby extending Harding's policies. It is the first broadcast of an official presidential address, made possible by the more than 2.5 million radios in U.S. homes; in 1920 there had been less than 5,000. </p>
<h2>3 18, 1924</h2>""<p>Providing twenty-year annuities for veterans at an overall cost of $2 billion, the Soldiers' Bonus Bill is passed by the House. One month later, the Senate also passes the bill only to have Coolidge veto it; Congress will later override the veto. </p>
<h2>5 3, 1924</h2>""<p>Representatives from Nicaragua, Guatemala, and El Salvador sign the Pact of Anapala with the United States, agreeing to cut off aid to the insurgent forces in neighboring Honduras threatening to overthrow President Rafael Gutierrez.  This was one of many attempts by the United States, which had first sent Marines to Honduras as early as 1919, to keep Gutierrez in power. These efforts ultimately failed when insurgent leader Tiburcio Carias became dictator in 1933. </p>
<h2>5 26, 1924</h2>""<p>Congress passes a new immigration law with even more restrictive quotas than those established by a temporary act two years earlier. Japanese immigrants are barred completely while Canadians and Mexicans remain exempted from the quotas. </p>
<h2>6 -July, 1924</h2>""<p>The national political parties hold conventions to nominate presidential and vice-presidential candidates for the upcoming elections. The Republican Party nominates Coolidge and Charles G. Dawes; the Democrats, John W. Davis and Charles W. Bryan; and the Progressives, Robert La Follette and Burton K. Wheeler. </p>
<h2>9 18, 1924</h2>""<p>The last U.S. Marines, first sent to Santo Domingo in 1916 by Woodrow Wilson, withdraw from the Dominican Republic, finalizing a process begun three years earlier by Secretary of State Charles Evans Hughes. During this period, the United States helped the country prepare for free elections and, ultimately, independence. The withdrawal reversed decades of U.S. involvement in the Dominican Republic under the auspices of the Roosevelt Corollary to the Monroe Doctrine. </p>
 
<h2>8 30, 1924</h2>""<p>The Dawes Plan is signed by the United States, France, Great Britain, Italy, and Belgium to solve the German reparations problem and to end the occupation of the Ruhr by French and Belgium troops. Overseen by Secretary of State Charles Evans Hughes, the plan was drawn up by Coolidge's running-mate, Charles G. Dawes, and based the reparations schedule on what Germany could pay rather than on what she could be forced to pay. For his part, Dawes would win the Nobel Peace Prize the following year. </p>
<h2>11 4, 1924</h2>""<p>Coolidge wins the election easily with 382 electoral votes (15,725,000 popular votes) to the Democrats' 136 (8,386,000 popular votes).  La Follette wins a surprisingly large 4,823,000 popular votes, though only 13 electoral votes. </p>
<h2>3 4, 1925</h2>""<p>Coolidge is inaugurated President in his first elected term. The following day, Frank B. Kellogg is named Secretary of State, replacing Charles Evans Hughes, who had resigned two months earlier. A lawyer by training, Kellogg had previously served as a senator from Minnesota and ambassador to Great Britain. </p>
<h2>3 23, 1925</h2>""<p>The Isle of Pines Treaty is finally ratified by the Senate. Pending since 1904, the treaty recognizes Cuban possession of the Isle of Pines. </p>
<h2>5 5, 1925</h2>""<p>John T. Scopes, a public school teacher in Dayton, Tennessee, is arrested for teaching Darwin's theory of evolution. His trial in July captures national attention as William Jennings Bryan is called on behalf of the prosecution and Clarence Darrow, the skilled and nationally-renowned attorney, agrees to represent Scopes. Although Scopes ultimately loses and pays a $100 fine, the trial serves as a national debate between Darrow and Bryan, science and religion. </p>
<h2>8 8, 1925</h2>""<p>The Ku Klux Klan holds a massive political demonstration in Washington, D.C. Possibly the largest Klan parade in history, around 40,000 men and women march down Pennsylvania Avenue decked out in their white Klan robes, a scene which reflects the group's resurgence during the 1920s. </p>
 
<h2>1 27, 1926</h2>""<p>The Senate adopts a resolution allowing the United States to join the World Court in the event that U.S. participation accord with five separate conditions. All but one are satisfied; failure to meet every condition leads the Senate to reject full U.S. participation. While America will work with the World Court and the League of Nations over the next decade, it never becomes a member of either. </p>
<h2>2 26, 1926</h2>""<p>Coolidge signs the Revenue Act into law, as Harding's policy of "normalcy" morphs into keeping "cool with Coolidge."  With the goal of cutting the size of the Federal government, the Act reduces income taxes as well as other duties. While it helps the Republican Party weather the investigations of corruption under Harding, it further weakens the already deteriorating national economy. </p>
<h2>4 29, 1926</h2>""<p>France and the United States sign an agreement that eventually cancels sixty percent of the French debt from the Great War. </p>
<h2>5 9, 1926</h2>""<p>Rear Admiral Richard E. Byrd and Floyd Bennett make the first successful flight over the North Pole. </p>
<h2>5 10, 1926</h2>""<p>The U.S. Marines land in Nicaragua to quiet a revolt. America military forces will maintain a presence in Nicaragua until 1933. </p>
<h2>5 20, 1926</h2>""<p>The Air Commerce Act is passed by Congress. While the federal government already subsidized airmail, this act gave the Commerce Department regulatory powers over sectors of the aviation industry, such as the licensing of pilots and aircrafts. </p>
<h2>7 2, 1926</h2>""<p>Congress establishes the Army Air Corps and the Distinguished Flying Cross. </p>
<h2>10 10, 1926</h2>""<p>A naval ammunition depot at Lake Denmark, New Jersey, explodes after it is struck by lightning. With explosions continuing for several days, 31 dead, and $93 million in damages, it is the worst such disaster in the history of the U.S. military. </p>
<h2>10 25, 1926</h2>""<p>The Supreme Court rules that the President has the right to remove cabinet members at his own discretion. The ruling nullifies the 1868 Tenure of Office Act, which required consent of the Senate in order to restrict the powers of President Andrew Johnson during Reconstruction. </p> 
<h2>2 18, 1927</h2>""<p>The United States and Canada establish diplomatic relations independent of Britain. </p>
<h2>2 23, 1927</h2>""<p>Congress creates the Federal Radio Commission to regulate this burgeoning field of national and international communication. In doing so, lawmakers continue the trend of imposing increasing federal regulation on private sectors of the economy. </p>
<h2>3 7, 1927</h2>""<p>The Supreme Court rules that a Texas law prohibiting blacks from voting in Democratic primaries is unconstitutional. </p>
<h2>5 21, 1927</h2>""<p>Charles A. Lindbergh completes the first transatlantic flight, traversing the distance from New York to Paris in his monoplane, the <i>Spirit of St. Louis</i>, in less than thirty-four hours. A year later, Amelia Earhart will become the first woman to make the flight. </p>
<h2>8 2, 1927</h2>""<p>Concerned that four more years in office might appear to some observers as a third term as President, Coolidge ends any talk of his candidacy for the 1928 election stating, "I do not choose to run." </p>
<h2>8 23, 1927</h2>""<p>Nicola Sacco and Bartolomeo Vanzetti are executed in Massachusetts for their alleged 1920 murder of a factory guard, despite protests that the two men had been unfairly prosecuted for their radical beliefs. </p>
<h2>10 6, 1927</h2>""<p>The first "talkie," <i>The Jazz Singer</i>, starring Al Jolson, is released. </p>
<h2>12 25, 1927</h2>""<p>Reversing its 1917 Constitution, Mexico's Congress grants unlimited concessions to foreigners for lands on which they engaged in any "positive" acts prior to May 1917. Soon after, however, the government revokes all rights to oil-rich territories, generating fierce protest by American businessmen. The United States recognizes new president Alvaro Obregon on the condition that he grant American firms subsoil rights. Under such pressure, the Mexican Supreme Court rules the law unconstitutional, returning all rights back to American companies. </p>
<h2>1 16, 1928</h2>""<p>At the Sixth International Conference of American States in Havana, Cuba, South American countries introduce a resolution opposing U.S. invocation of the Roosevelt Corollary. By the end of the year, the State Department will issue a statement redefining the Monroe Doctrine as a policy which "does not concern itself with purely inter-American relations." This redefinition brought an end to the Roosevelt Corollary in word, if not in deed. </p>
<h2>6 29, 1928</h2>""
<p>The Democratic Party nominates Alfred E. Smith for President and Joseph T. Robinson for vice president. A Catholic, Smith will have his loyalty questioned during the campaign as religious prejudice plays a key role in the election. </p>
<h2>7 25, 1928</h2>""<p>The United States recognizes Chiang Kai-shek's Kuomintang (KMT) nationalist government of China and signs a tariff treaty with the Chinese. </p>
<h2>8 25, 1928</h2>""<p>Richard E. Byrd begins the first leg of his flight to the South Pole in Antarctica. Reaching the pole in November, Byrd explores and studies the continent for the next twenty years. </p>
<h2>8 27, 1928</h2>""<p>The Kellogg-Briand Pact, or the Pact of Paris, as it was also known, is signed by the United States and fifteen other nations. Named for its two principal authors, Secretary of State Frank B. Kellogg and French foreign minister Aristide Briand, the pact outlaws war as a means to settle disputes, substituting diplomacy and world opinion for armed conflict.  Ultimately signed by 62 nations, the pact is more symbolic than practical, though Kellogg would win the Nobel Peace Prize for his efforts the following year. </p>
<h2>11 6, 1928</h2>""<p>Hoover wins the presidential election in an apparent landslide, 444 electoral votes to Smith's 87. In fact, the popular vote shows a much closer race, with 21,392,000 for Hoover and 15,016,000 for Smith. </p>
