
<h2>7 9, 1850</h2>""<p>President Zachary Taylor dies suddenly of cholera at the age of 55. Vice President Millard Fillmore is slated to assume the duties of the presidency.</p>
<h2>7 10, 1850</h2>""<p>Judge William Cranch administers the executive oath to Millard Fillmore, making Fillmore the nation's thirteenth President. Knowing that Fillmore's sympathies lie with the proposed congressional compromise, regarding the number of free and slave states, Zachary Taylor's cabinet resigns unanimously. Fillmore responds by appointing pro-Union, pro-compromise Whigs, including Daniel Webster as secretary of state, to his cabinet. </p>
<h2>8 6, 1850</h2>""<p>Fillmore announces his support of the compromise. He sends a message to Congress recommending that (1) Texas be paid to abandon claims to part of New Mexico and (2) that the Wilmot Proviso, which states that all land acquired from the Mexican War be closed to slavery, be overturned. </p>
<h2>9 9, 1850</h2>""<p>As one of the recommendations of the compromise, California enters the Union as the thirty-first state. As a "free" state, its admittance gives non-slaveholding states a majority in the Senate. Simultaneously, the Texas and New Mexico Act establishes boundaries between the two. As a concession to the South, New Mexico's status -- free or slaveholding -- will be dependent on how its constitution reads at the time of admittance to the Union. Similarly, the Utah Act decides boundaries of Utah according to the principles governing New Mexico. </p>
<h2>9 18, 1850</h2>""<p>Congress passes the Fugitive Slave Bill, prohibiting individuals from aiding runaway slaves, and threatening fines and imprisonment to those who do. Escaped slaves will be returned to their owners, denied a jury trial, and prevented from testifying on their own behalf. Part of the Compromise of 1850 and an attempt to ease tensions within the fractious nation, the bill is a concession to the South but angers many Northerners. </p>
<h2>9 20, 1850</h2>""<p>Congress passes the Compromise of 1850, written by Kentucky senator Henry Clay. California is admitted as a free state, the Utah and New Mexico territories are to be organized on the principle of "popular sovereignty," and the slave trade is to be abolished in Washington, D.C. The deal settles the issue of slavery in the newly acquired territories, dividing the country along the thirty-seventh parallel, with slavery in the South and free states in the North. Northern "irreconcilables" refuse to forgive Fillmore for the act, catalyzing the sectionalism afflicting the United States. </p>
<h2>9 28, 1850</h2>""<p>President Fillmore names Brigham Young, president of the Mormon Church, governor of the Utah territory.  From 1846 to 1847, Young leads thousands of disciples from Illinois to the central Utah valley, where he establishes Salt Lake City, the site for the Church's new temple. With hundreds of new arrivals each year, Young founds scores of colonies to provide the inhabitants with homes and land; at his death in 1877, nearly 400 Mormon colonies exist. Serving as governor until 1857, Young clashes with the "outside" federal employees who oppose many of the Church's stances.  </p>
<h2>10 23-24, 1850</h2>""<p>Headed by feminists and abolitionists, a national women's rights convention is held in Worcester, Massachusetts, and is attended by delegates from nine states. Chosen for its accessibility by rail, the Worcester convention attracts hundreds of people. Among the main topics, participants discuss employment opportunities, political and legal rights, property rights after marriage, and educational opportunities for women, especially in medicine. </p>
<h2>1 2, 1851</h2>""<p>Acting on long-held interest in gaining influence in Central America, the United States ratifies its first commercial treaty with El Salvador. </p>
<h2>3 3, 1851</h2>""<p>The coinage of three-cent pieces, the smallest coin in weight and thickness ever issued, begins to facilitate postal payments. </p>
<h2>6 5, 1851</h2>""<p>Appearing in serialized form, the first installment of <i>Uncle Tom's Cabin</i> (or <i>Life Among the Lowly</i>), by Harriet Beecher Stowe, is published in the <i>National Era</i>; the book form appears in 1852. Coupled with Northern anger over the Fugitive Slave Bill, this book generates more support for abolitionist causes. Years later, President Abraham Lincoln will call Stowe "the little lady who caused the Civil War." By 1853, with more than 300,000 copies of <i>Uncle Tom's Cabin</i> sold, the novel becomes a play in New York; it is dramatized by George Aiken and runs for more than 100 nights. Southerners denounce the work while Northerners embrace it as a true depiction of slavery. </p>
<h2>7 25, 1851</h2>""<p>Gold is found in Oregon along the Rogue River, a prospective new territory for the California gold rushers of 1849. The discovery leads to the arrival of thousands of individuals in search of the metal. </p>
<h2>11 14, 1851</h2>""<p>The first American edition of Melville Herman's <i>Moby Dick</i> is published. The work does not become widely accepted for another seventy years. </p>
<h2>6 1-6, 1852</h2>""<p>The Democratic National Convention nominates Franklin Pierce of New Hampshire for the presidency and William R. King of Alabama for the vice presidency. </p>
<h2>6 16-21, 1852</h2>""<p>The Whig National Convention nominates General Winfield Scott of New Jersey for the presidency and William Graham of North Carolina for the vice presidency. Both adhere to the strict enforcement of the Compromise of 1850. </p>
<h2>8 24, 1852</h2>""<p>Karl Marx, a German exile living in London, makes his first appearance in print with a series called "Revolution and Counter-Revolution," in the <i>New York Tribune</i>. Over the next decade, Marx will write a series of news articles that appear in the newspaper about European events and affairs. </p>
<h2>11 2, 1852</h2>""<p>Franklin Pierce is elected President of the United States with William R. King as his vice president. </p>
<h2>11 , 1852</h2>""<p>In Congressional elections, Democrats gain three Senate seats for a 38-22 majority over the Whigs. The Democrats also pick up 19 seats in the House for a 159-71 majority. Meanwhile, following Pierce's election over the Whig candidate Scott, the Whig Party splits with Southern Whigs defecting and abstaining to protest the party's antislavery leadership. The emergence of both the Know-Nothing (1853) and Republican (1854) parties, coupled with the 1852 deaths of Whig leaders Henry Clay (June) and Daniel Webster (October), eventually lead to the party's demise. </p>
<h2>3 2, 1853</h2>""<p>The territory of Washington is formed after its separation from the Oregon Territory. </p>
<h2>3 3, 1853</h2>""<p>With direct rail service from New York to Chicago beginning in the previous year, Congress authorizes the transcontinental railroad survey one day prior the expiration of Fillmore's term as President. Six years later, in May 1869, the railroad is officially completed in Utah. </p>
<h2>3 4, 1853</h2>""<p>Pierce's appointment of James Campbell of Pennsylvania for postmaster general marks the first Catholic cabinet officer and touches off a political storm that leads to the growing prominence of the nativist American Party (commonly referred to as the Know-Nothing Party -- in response to questions about their views, members frequently reply that they "know nothing"). Party adherents lament the numerous arrivals of immigrants, particularly Roman Catholics. Member will seek to exclude from office all who are not native-born and urges the repeal of naturalization laws. The movement enjoys success in the 1850s, most notably electing governors in Massachusetts and Delaware. The party collapses after the 1856 elections. </p>
