
<h2>3 4, 1801</h2>""<p>Thomas Jefferson is inaugurated as the third president of the United States, becoming the first president inaugurated in Washington, D.C. Aaron Burr, who had tied Jefferson in electoral votes before losing the election in the House of Representatives, is inaugurated Vice President.</p>  
<h2>5 14, 1801</h2>""<p>Yusuf Karamini, pasha of Tripoli, declares war on the United States by symbolically cutting down the flagpole at the U.S. consulate. This action came after the United States refused to pay more tribute to the Tripolitans in exchange for protection from piracy against American ships. </p>   
<h2>7 10, 1801</h2>""<p>William C.C. Claiborne is appointed the new territorial governor of Mississippi. </p>  
<h2>12 8, 1801</h2>""<p>President Jefferson delivers his first address to the newly convened seventh Congress of the United States in writing and is read aloud by the House clerk. Expressing his dislike for ceremony, Jefferson establishes the precedent, not broken until the presidency of Woodrow Wilson, of not delivering the State of the Union address in person. </p>   
<h2>1 8, 1802</h2>""<p>A convention between the United States and Britain regarding the treaty of 1794 is concluded. A commission rules that the United States owes £2,664, 000 to British citizens in settlement of Revolutionary War claims. </p>  
<h2>2 6, 1802</h2>""<p>Congress recognizes the War with Tripoli, authorizing the arming of merchant ships to ward off attacks. </p>   
<h2>3 16, 1802</h2>""<p>Congress reduces the size of the U.S. army to its 1796 limits. It also passes an act, which is signed into law by Jefferson, establishing an official United States Military Academy at West Point. </p>  
<h2>4 6, 1802</h2>""<p>Infamous excise taxes on commodities such as whiskey are repealed. </p>    
<h2>4 14, 1802</h2>""<p>The notorious naturalization laws of 1798 are repealed. The required length of residency reverts from fourteen years to five years. </p>   
<h2>4 24, 1802</h2>""<p>The Georgia legislature cedes to the United States its western territory, notorious for the Yazoo land fraud of 1795. </p>  
<h2>4 30, 1802</h2>""<p>President Jefferson signs the Enabling Act, establishing procedures under which territories organized under the Ordinance of 1787 can become a state. The law effectively authorizes people of the Ohio territory to hold a convention and frame a constitution. </p>      
<h2>5 3, 1802</h2>""<p>Congress officially incorporates Washington as a city, empowering Jefferson to appoint the mayor. </p>   
<h2>8 11, 1802</h2>""<p>The United States and Spain resolve to refer all disputes between the two countries to a special convention at Madrid. </p>    
<h2>1 11, 1803</h2>""<p>Jefferson appoints James Monroe minister to France and Spain, instructing him to purchase New Orleans and East and West Florida. Napoleon informs U.S. minister in Paris Robert Livingston that France will be willing to sell the entire Louisiana territory, much to his surprise. </p>  
<h2>2 19, 1803</h2>""<p>Ohio officially becomes the seventeenth state of the Union. It is the first state to prohibit slavery by law at its inception. </p>   
<h2>4 19, 1803</h2>""<p>Spain reopens New Orleans to American merchants. </p>  
<h2>4 30, 1803</h2>""<p>Livingston and Monroe are sent to conclude a treaty for the acquisition of New Orleans, but instead conclude a treaty for the purchase of the entire Louisiana Territory. This day marks the official signing of a peace treaty with France and the purchase of Louisiana. The addition of 828,000 square miles of land between the Mississippi and the Rocky Mountains is purchased from France for approximately $15 million, increasing the national territory by 140 percent.</p>    
<h2>5 23, 1803</h2>""<p>Jefferson commissions Commodore Edward Preble as commander of a U.S. Navy squadron sent to battle Tripoli. </p>  
<h2>8 31, 1803</h2>""<p>Captain Meriwether Lewis, formerly Jefferson's personal secretary, sets out from Pittsburgh to begin an expedition of the newly acquired western territory of the Louisiana Purchase. Lewis will pick up Captain William Clark to serve as co-leader of the trip early in the next year. Jefferson sponsored the journey out of personal scientific curiosity and concern for the economic and political security of the western United States. </p>   
<h2>12 9, 1803</h2>""<p>Motivated by the infamous election of 1800, Congress passes the Twelfth Amendment to the Constitution, requiring electors to vote for President and vice president separately. This ends the tradition of the runner up in a presidential race becoming vice president and prevents chances for a deadlock tie. </p>     
<h2>12 20, 1803</h2>""<p>The French flag is lowered in New Orleans and the U.S. flag raised, symbolizing the transfer of the Louisiana territory from France to the United States. </p>    
<h2>2 16, 1804</h2>""<p>Lt. Stephen Decatur burns the captured U.S. frigate <i>Philadelphia</i> while docked in Tripoli harbor. Tripolitan gunboats had captured the frigate during the previous October. No one is killed. </p>  
<h2>3 26, 1804</h2>""<p>Congress passes the Louisiana Territory Act, dividing the Louisiana Purchase into the Territory of Orleans in the south and the district of Louisiana in the north. </p>  
 <h2>7 11, 1804</h2>""<p>Alexander Hamilton is fatally wounded in a pistol duel with Aaron Burr. Hamilton had opposed Burr's bid for the presidency in 1800. He further opposed Burr's bid for the governorship of New York, exposing an alleged subversive attempt to establish a separate northern confederacy amongst disgruntled states of New England. Vowing to avenge these dishonors, Burr had challenged Hamilton to the duel. </p>  
<h2>9 25, 1804</h2>""<p>The Twelfth Amendment to the U.S. Constitution is officially ratified, allowing for the presidential election of 1804 to be conducted under new rules. </p>  
<h2>11 13, 1804</h2>""<p>The fifth presidential election is held under the auspices of the newly ratified Twelfth Amendment. </p>   
<h2>12 5, 1804</h2>""<p>Thomas Jefferson is officially reelected President of the United States. Fellow Democratic-Republican and first governor of New York George Clinton will be the vice president. </p>   
<h2>3 4, 1805</h2>""<p>President Jefferson is inaugurated for his second term. George Clinton officially succeeds Aaron Burr as vice president. In his inaugural address, Jefferson proposes that Federalist-inspired internal taxes be completely eliminated. </p>   
<h2>4 26, 1805</h2>""<p>Lewis and Clark reach the mouth of the Yellowstone River. </p>  
<h2>4 27, 1805</h2>""<p>U.S. Marines and Arab mercenaries capture the Tripolitan port city of Derna, achieving a major victory for the United States in the Tripolitan War.  Eaton's ultimate plan, approved by President Jefferson, entailed replacing the ruling pasha of Tripoli with the rightful ruler. This is aborted with the forthcoming peace treaty in June. </p>  
<h2>6 4, 1805</h2>""<p>The United States and Tripoli sign a Treaty of Peace and Amity in Tripoli, effectively ending the Tripolitan War. </p>  
<h2>7 23, 1805</h2>""<p>The British justify seizure of American ships in neutral ports with the invocation of the Rule of 1756. </p>  
<h2>7 23, 1805</h2>""<p>Rumors circulate about the subversive activities of Aaron Burr as he arrives in New Orleans. These include plans to establish a separate country with New Orleans as its capital and a plot to invade Mexico. </p>  
<h2>11 7, 1805</h2>""<p>Lewis and Clark reach the Pacific after a perilous journey of nearly eighteen months and 4,000 miles. </p>  
<h2>12 3-4, 1805</h2>""<p>Jefferson makes two addresses, one public and one before Congress, regarding land in Florida. In the public address, Jefferson cites the need to prepare for war with Spain. Privately, Jefferson informs Congress of secret negotiations with France in order to buy the territory from them and asks for five million dollars to be appropriated. The request receives a controversial response from Congress. </p>    
<h2>1 11, 1806</h2>""<p>Michigan is formed from the territory of Indiana. </p>  
<h2>3 9, 1806</h2>""<p>Congress authorizes a commission to build a national road from Cumberland, Maryland, to the Ohio River.  </p>  
<h2>4 18, 1806</h2>""<p>In protest against the seizure of American ships and the impressment of American sailors by Britain, Congress passes a law prohibiting the importation of many British products into the United States. </p>  
<h2>7 15, 1806</h2>""<p>Zebulon Pike begins his exploration of what is now the southwestern United States. On November 15, Pike explores the famous 18,000-foot peak that still retains his name in what is now Colorado. </p>    
<h2>8 27, 1806</h2>""<p>American envoys James Monroe and William Pinckney commence talks with British official Lord Holland on the current naval hostilities. </p>    
<h2>12 12, 1806</h2>""<p>Jefferson appeals to Congress asking for a ban on the slave trade. </p>   
<h2>10 21, 1806</h2>""<p>Congress passes legislation providing for a military organizational structure. </p>   
<h2>11 27, 1806</h2>""<p>In Washington, D.C., President Jefferson publicly warns citizens not to take part in a plot to invade Spanish territory. Jefferson issues this warning after having been told of Aaron Burr's subversive activities with respect to annexing Spanish territory. </p>  
	
<h2>2 19, 1807</h2>""<p>Aaron Burr is arrested near Fort Stoddart, Alabama, in connection with his alleged conspiracy against the government. </p>     
<h2>3 2, 1807</h2>""<p>At Jefferson's behest, Congress passes a law prohibiting the importation of slaves into any place within the jurisdiction of the United States after January 1, 1808. </p>    
<h2>3 12, 1807</h2>""<p>The Embargo Act, modified and authorized by President Jefferson, now permits vessels to transport American goods from foreign ports. </p>    
<h2>6 22, 1807</h2>""<p>The infamous <i>Leopard</i> incident occurs.  The British ship <i>Leopard</i> fires upon the United States frigate <i>Chesapeake</i> in Chesapeake Bay after the latter's commander, James Barron, refuses to surrender four British deserters on board. Many on the U.S. frigate are killed and wounded. </p>      
<h2>9 1, 1807</h2>""<p>Circuit court in Richmond acquits Aaron Burr of treason. </p>    
<h2>10 17, 1807</h2>""<p>In spite of Thomas Jefferson's vehement protest, the British government announces it will continue to impress seamen on American ships thought to be British. </p>   
<h2>11 11, 1807</h2>""<p> Britain issues its "Order in Council," forbidding neutral nations and her allies from trading with France except under tribute to England.</p>  
<h2>12 17, 1807</h2>""<p>Napoleon issues the Milan Decree, forbidding trade with England or her colonies under penalty of confiscation and impressments of any vessel paying tribute to Britain. </p>    
<h2>12 22, 1807</h2>""<p>President Jefferson signs the Embargo Act, putting a halt to all trading with any country in the entire world. The act serves as a retaliatory measure to the increasingly coercive trade policies of the British and the French. </p>    
<h2>1 1, 1808</h2>""<p>The law officially banning the slave trade goes into effect. </p>    
<h2>1 11, 1808</h2>""<p>The Second Embargo Act comes into force. It is more stringent than the first and is commonly known as the "O grab me Act." </p>  
<h2>4 17, 1808</h2>""<p>Napoleon issues the Bayonne Decree, authorizing the French seizure of all U.S. vessels entering French and Italian ports and all ports of the Hanseatic League. Napoleon conveniently argues that his action helps the United States enforce its new policy prohibiting trade with other nations. </p>    
<h2>11 8, 1808</h2>""<p>The sixth presidential election for President of the United States is held. </p>   
<h2>12 7, 1808</h2>""<p>James Madison is elected president of the United States, with George Clinton as vice president. </p>  
<h2>3 1, 1809</h2>""<p>After the U.S. economy suffers at the hands of the embargo, Congress repeals the Embargo Act.  Jefferson signs the Non-Intercourse Act the same day, closing U.S. ports only to France and England.  Trade with the two countries is to be resumed when they agreed to respect the rights of U.S. citizens and vessels. </p>      
<h2>3 4, 1809</h2>""<p>James Madison is inaugurated as the fourth President of the United States, thereby ending Jefferson's presidency. Jefferson retires to his home at Monticello outside Charlottesville, Virginia, to assume a private life. </p>     
 
