
<h2>3 4, 1837</h2>""<p>Martin Van Buren, the eighth President of the United States, delivers his inaugural address. The speech serves largely as a commemoration of his predecessor, President Andrew Jackson. Additionally, Van Buren presents his states' rights approach to slavery.</p>
<h2>5 10, 1837</h2>""<p>The Panic of 1837 begins in New York when banks first suspend payments of specie. Following the collapse of credit facility, banks can no longer redeem currency notes in gold and silver. Compounding the problem, a depression in England causes the price of cotton to drop and ends British loans to the United States. An already unstable economy now suffers from additional debts and unemployment. </p>
<h2>8 5, 1837</h2>""<p>Van Buren announces his opposition to the annexation of Texas, primarily to make possible the ensuing peace with Mexico but also to alleviate abolitionist concerns at home. </p>
<h2>9 5, 1837</h2>""<p>In response to the economic crisis, Van Buren calls for a special session of Congress. As a proponent of laissez-faire, he feels no obligation toward public welfare but worries about the government's own financial situation. Refusing to participate in sectional disputes, Van Buren proposes a bank divorce policy and the establishment of an independent treasury. </p>
<h2>11 , 1837</h2>""<p>A rebellion erupts in Lower and Upper Canada against the British. Sympathetic volunteers in Maine and New York rally in support with promises of various bounties and land allotments. The American volunteers cross the Niagara River into Canada and occupy Navy Island. After a series of events, Van Buren instructs General Winfield Scott to persuade the American citizens to restrain themselves from further incursions violating national law and neutrality. </p>  
<h2>12 , 1837</h2>""<p> Britain orders the Canadian militia to seize the American steamship <i>Caroline</i>, which had been supplying Canadian rebels, on the Niagara River. One American is killed, and several are wounded. </p>
<h2>1 , 1838</h2>""<p>Following the <i>Caroline</i> incident, Van Buren criticizes the British but maintains a neutral stance in the conflict. While Van Buren's peace appeals to the invading partisans and enjoys initial success, even the Neutrality Law of 1838 -- which provides for the arrest of people and the confiscation of arms, vehicles, and supplies flowing illegally across the border -- fails to deter additional incursions. Rebel assistance by secret rebel societies will continue in Detroit, Cleveland, and along the New York and Vermont borders. </p>    
<h2>9 11, 1838</h2>""<p>Van Buren agrees on the principle of forming an arbitration commission to settle disputed claims with Mexico. </p> 
<h2>3 25, 1839</h2>""<p>A treaty ending the Aroostook War, which begins in 1838, is signed between the United States and Canada. Lumberjacks in Maine and New Brunswick had disputed the border and disagreed on the ownership of trees in the Aroostook Valley; the claims stemmed from an ambiguous boundary determination in the 1783 Treaty of Paris. Van Buren sends General Winfield Scott to calm matters in the area before working toward the treaty. </p>
 
<h2>5 , 1839</h2>""<p>Van Buren secures an agreement with England on compensation for two slave ships, the <i>Comet</i> and the <i>Encomium</i>, which had run ashore on the British territory of the Bahamas. </p>
<h2>8 26, 1839</h2>""<p>The <i>U.S.S. Washington</i> seizes the <i>Amistad</i>, a mutinous slave ship, and brings the captives to a jail in New Haven, Connecticut. West African slaves had taken over the Cuban ship, traveling from one Cuban port to another, and sail up the United States coastline. The incident prompts the Van Buren administration to argue, first, that the property and expropriation dispute be handled by the executive branch, and second, that the United States would uphold its obligations under the Treaty of 1795, whereby ships stranded abroad remain under the jurisdiction of the originating nation. These principles dictate the return of the <i>Amistad</i> and its occupants to Havana. </p>
<h2>12 4, 1839</h2>""<p>The Whigs meet in Pennsylvania to determine their presidential ticket and nominate William Henry Harrison for President and John Tyler for vice president. </p>
<h2>9 19, 1840</h2>""<p>The <i>Amistad</i> hearings begin in a Hartford, Connecticut, courtroom. The court will find the clearance papers of the <i>Amistad</i> to fraudulently identify the slaves as Spanish-speaking Ladinos; however, the Hartford court, a circuit court, and ultimately the Supreme Court concur that treaty obligations have no relevance to the matter of slaves and award compensation for the ship only. The slaves will be returned to Africa in January 1842. </p>
<h2>7 4, 1840</h2>""<p>By signing the Independent Treasury Act, Van Buren "divorces" the federal Treasury Department from its relationship with all banks. His action stems from the controversy surrounding the Deposit Act of 1836. The Whigs will repeal the Independent Treasury Act in 1841; it will be restored in 1846. </p>
<h2>11 , 1840</h2>""<p>The contest between Democrat Martin Van Buren and Whig William Henry Harrison results in the largest turnout of any election to that point. Harrison soundly defeats Van Buren with 234 electoral votes to the incumbent's 60. Among the reasons for his loss, Van Buren cannot overcome opposition from southern and expansionist groups who support the immediate annexation of Texas. </p>
<h2>3 4, 1841</h2>""<p> William Henry Harrison is inaugurated as the ninth President of the United States. 
