
"1881/03/04","","Day","Arthur takes office as vice president in the presidential administration of James Garfield."
"1881/07/02","","Day","President Garfield is shot in Washington by Charles Julius Guiteau, a deranged, disappointed office seeker. "
"1881/09/19","","Day","President Garfield dies from injuries sustained in the attack. "
"1881/09/20","","Day","Arthur is sworn in as President of the United States. "
"1881/09/22","","Day","Arthur formally takes the oath of office in Washington, DC. "
"1881/11/14","","Day","The murder trial of Charles Guiteau begins. He will be convicted on January 25, 1882, and executed on June 30, 1882. "
"1881/12/15","","Day","Secretary of State James G. Blaine resigns due to political differences between himself and President Arthur. "
"1882/02/28","","Day","Congress passes a bill mandating the use of the census for determining congressional representation, a move which increases the number of representatives in Congress to 325. "
"1882/03/04","","Day","Nine men are indicted for defrauding the government in a postal scam, an episode that becomes known as the Star-Route Scandal; the trial begins on June 1. "
"1882/03/16","","Day","The Senate ratifies the Geneva Convention of 1864 for the care of wounded war personnel. "
"1882/03/22","","Day","Congress passes the Edmunds Act, which excludes bigamists and polygamists from voting and holding office, and establishes a five-man “Utah commission” to supervise voting in the territory of Utah. "
"1882/04/04","","Day","Arthur vetoes the first Chinese Exclusion Act, which would have banned the immigration of Chinese laborers for twenty years and denied American citizenship to current Chinese residents; the veto greatly angers labor groups, who feel increasingly threatened by the influx of Chinese labor. "
"1882/05/06","","Day","A revised version of the Chinese Exclusion Act, which reduces the period of non-immigration to ten years but maintains the ban on Chinese citizenship, becomes law. The act will be renewed regularly into the twentieth century. "
"1882/05/15","","Day","Arthur approves a bill to appoint a tariff commission; the commission eventually recommends tariff reductions. "
"1882/05/22","","Day","The United States recognizes the independence of Korea, although Korea's future is uncertain because of Chinese, Russian, and Japanese manipulations. "
"1882/07/01","","Day","Arthur vetoes the Carriage of Passengers at Sea Bill, a steamboat safety bill, claiming that it contains several major technical errors. "
"1882/08/01","","Day","The President vetoes the River and Harbor Act, a pork-barrel piece of legislation that Arthur claimed would benefit only "particular localities;" Congress overrides the veto and passes the legislation the next day. "
"1882/08/01","","Day","Brode Herndon, Arthur's physician, writes in his private diary, "The President sick in body and soul." Arthur had been diagnosed that year with Bright's disease, a fatal kidney ailment; his health will deteriorate rapidly while being kept secret from the general public. "
"1882/09/11","","Day","The verdict in the Star-Route trial is rendered.  Of the nine accused, only two minor defendants are found guilty. The foreman of the jury charges that a government agent attempted to bribe him, and the judge orders a retrial, to begin on December 7, 1882. "
"1882/11/07","","Day","In the midterm elections, Democrats gain 50 seats in the House giving them a 197-118 majority (ten remaining seats were filled by minor parties). In the Senate, Republicans take one seat and gain a 38-36 majority (with two seats filled by minor parties). "
"1883/01/16","","Day","Congress passes the Pendleton Civil Service Reform Act. The bill establishes a three-man Civil Service Commission and specifies rules for filling federal government positions according to a merit system. The number of Civil Service positions affected by the bill would later be expanded. "
"1883/03/03","","Day","Congress passes the so-called "Mongrel" Tariff Act, a complex tariff revision that reduces rates on various items by less than 2 percent; Arthur had lobbied Congress for a 20 to 25 percent cut on all items. The act establishes the Republicans as the party in favor of higher protective tariffs. "
"1883/03/03","","Day","Recognizing the disgraceful state of the U.S. Navy, Arthur signs a bill appropriating funds for the Navy's first steel vessels. "
"1883/05/24","","Day","President Arthur and New York Governor Grover Cleveland attend the opening of the Brooklyn Bridge. "
"1883/06/14","","Day","The court renders a verdict in the second Star-Route case. All nine defendants are found not guilty. "
"1883/09/18","","Day","Arthur receives Korean ambassadors in New York. "
"1883/10/29","","Day","The United States and Luxembourg conclude an extradition treaty in New York. "
"1883/12/21","","Day","Arthur issues a proclamation recommending the observance of the 100th anniversary of General George Washington returning his commission as commander-in-chief to the Continental Congress. "
"1884/03/13","","Day","The United States participates in an international conference establishing standard time. "
"1884/03/26","","Day","In a special message to Congress, Arthur asks the legislature to appropriate funds for naval reconstruction work. "
"1884/05/13","","Day","Congress passes a bill repealing the 1862 test oath, which required office holders to swear they had never engaged in illegal or disloyal conduct. "
"1884/05/17","","Day","Congress passes an act regarding civil government in Alaska. The territory had been ceded to the United States by Russia in an 1867 treaty. "
"1884/06/06","","Day","The Republican National Convention meets in Chicago. Political opponent of the President and former secretary of state James G. Blaine defeats Arthur for the nomination; John A. Logan is selected as vice president. "
"1884/06/27","","Day","The United States Bureau of Labor is created within the Department of the Interior; an independent Department of Labor will not be created until 1913. "
"1884/07/01","","Day","Arthur issues a proclamation warning people not to settle on Oklahoma lands. "
"1884/07/04","","Day","France presents the United States with the Statue of Liberty at a ceremony held in Paris. "
"1884/07/11","","Day","The Democratic National Convention meets in Chicago, nominating Grover Cleveland and Thomas A. Hendricks for President and vice president, respectively. "
"1884/11/04","","Day","In the federal presidential election, Grover Cleveland defeats James G. Blaine. "
"1884/11/12","","Day","The United States and Mexico conclude a convention on their shared territorial boundary. "
"1885/02/21","","Day","The Washington Monument is dedicated in Washington, D.C. "
"1885/02/25","","Day","Congress passes an act prohibiting the fencing of public lands in the west. "
"1885/02/26","","Day","Congress passes the Contract Labor Law, also known as the Foran Act, which virtually outlaws alien contract labor. The act is designed to ban companies from importing immigrant workers to break strikes and drive down wages. "
"1885/03/04","","Day","Grover Cleveland is inaugurated as the twenty-second President of the United States. "
