
"1857/03/04","","Day",<p>James Buchanan, a Democrat from Pennsylvania, is inaugurated as the nation's fifteenth President. He enters office without a strong national mandate, having mustered support from only four of fourteen northern states and secured only 45.3 percent of the popular vote. Buchanan has served previously in Congress, as a secretary of state for President Polk and as minister to Britain and Russia. In his inaugural speech, Buchanan advocates a modification of the recently passed Tariff Act, which lowers import duties to an average of 20 percent. Advocates of the Tariff Act hail generally from the South, while the legislation is unpopular in the North. The United States suffers a major depression in the Panic of 1857, caused in part by stagnant international trade. The North will suffer the brunt of the economic downturn, and the country will not emerge from the depression until 1859.</p>
"1857/03/06","","Day",<p>In the <i>Dred Scott</i> decision, a Southern, pro-slavery majority on the Supreme Court, led by Chief Justice Roger B. Taney, finds that (1) blacks are not citizens, and (2) that slavery cannot be prohibited in the territories. It further declares the 1820 Missouri Compromise unconstitutional. Scott, a slave who lived in the free state of Illinois and free territory of Wisconsin before moving back to the slave state of Missouri, sued for his freedom. In addition to denying Scott's claim, the majority opinion of the Supreme Court finds that blacks, lacking the rights of citizens, consequently cannot enter suits in a court of law. Abolitionists are furious. </p>
"1857/09/07","1857/09/11","Day",<p>The Mountain Meadow Massacre in Utah results in the deaths of roughly 140 people. Paiute Indians and the Mormon Militia, incited by Mormon fanatic John D. Lee, kill emigrants heading for California. Lee stages the event in direct retaliation for President Buchanan's order to remove Mormon leader Brigham Young from his position as governor of Utah. </p>
"1857/10/05","","Day",<p>Kansas elects a free-state legislature under Governor Robert J. Walker.  Elections occur under supervision, with thousands of fraudulent pro-slavery votes rejected. </p>
"1857/12/21","","Day",<p>Kansas holds a referendum on the Lecompton Constitution, drafted in the territorial capital of Lecompton, Kansas, as an attempt to bring Kansas into the Union as a slave state. Pro-slavery supporters rig the referendum so that slavery will not be eliminated from the territory even by a negative majority vote. While Buchanan throws in his lot with the pro-slavery forces, Stephen Douglas and Northern Democrats ally with Republicans in Congress to reject the pro-slavery document and refuse admittance of Kansas as a slave state. </p>
"1858/01/04","","Day",<p>The Lecompton Constitution loses by an overwhelming vote, with 10,226 voting against the constitution and only 138 for it. </p>
"1858/03/23","","Day",<p>The Senate votes to accept Kansas into the Union under the Lecompton Constitution after it has already been rejected in Kansas. The House votes to resubmit the Constitution to popular vote. </p>
"1858/05/04","","Day",<p>Congress passes the English Bill after Representative William Hayden English (Democrat-Indiana) strikes a compromise between the House and Senate bills on the admission of Kansas to the Union. The bill effectively resubmits the Lecompton Constitution to Kansas voters with the attached incentive of land if ratified. </p>
"1858/05/11","","Day",<p>A Republican-controlled Congress admits Minnesota to the Union as the thirty-second state (and a free one). Congressional approval had been delayed for several months due to the Kansas controversy. </p>
"1858/08/02","","Day",<p>The federal government submits the Lecompton Constitution to the people of Kansas for the third time. It again fails to win approval, with a vote of 11,300-1,788 against, turning Kansas into a non-slaveholding state when it enters the Union officially in 1861. </p>
"1858/01/01","1859/12/31","Year",<p>Congressional elections are held. The Republican Party makes a strong showing and takes control of the House for the first time.  The Lincoln-Douglas debates take place, in which Stephen Douglas attempts to reconcile "popular sovereignty" with the Dred Scott decision by arguing that territorial governments can refuse to pass laws necessary to support slavery (a stand that subsequently alienates him from Southern Democrats). Meanwhile, Abraham Lincoln denounces the Dred Scott decision and voices his opposition to slavery. Lincoln will lose the Illinois Senate race but secure a national reputation as an anti-slavery spokesman.</p>
"1859/02/14","","Day",<p>Oregon is admitted as the thirty-third state in the Union. </p>
"1859/03/12","","Day",<p>The Southern Commercial Convention meets in Vicksburg, Mississippi, and Southern slave owners advocate for the reopening of the African slave trade. A congressional act banned the slave trade in 1808. </p>
"1859/07/05","","Day",<p>The fourth and final Kansas Constitutional Convention, held in Wyandotte, Kansas, considers the future of Kansas as a free or slave state and drafts a state constitution; the document prohibits slavery in the state. Additionally, Clarina Nichols, the sole woman present, successfully lobbies for the inclusion of three sections involving women's rights. </p>
"1859/10/04","","Day",<p>The Kansas Constitution is ratified as an antislavery document by an overwhelming popular vote. A provisional state government is elected in December.  The Comstock Lode is discovered in western Nevada. It is the first major U.S. silver strike and the richest U.S. silver deposit. Virginia City becomes a boomtown. </p>
"1859/10/16","","Day",<p>John Brown raids Harper's Ferry, Virginia (now West Virginia), with twenty men, including five blacks, in an effort to establish an abolitionist republic in the Appalachians. Unsuccessful, Brown is captured and hanged at Charles Town, Virginia, on December 2, for murder, conspiracy, and treason against the state of Virginia. Southerners regard Brown as a traitor who deserves death; the raid prompts the creation of militias throughout Southern states. Northerners hail Brown as a martyr and hero. Lincoln, Thoreau, and Longfellow all defend his actions, proclaiming that "when a government puts forth its strength . . . to kill the liberators of the slave, what a merely brute . . . force it is seen to be" (Thoreau). The episode further polarizes North and South. </p>
"1860/02/27","","Day",<p>Abraham Lincoln delivers an address at Cooper Union in New York City. In it, he sets forth the platform of the Republican Party and confirms its no-compromise stance on slavery. The speech is also printed in the New York Tribune and pushes Lincoln into the lead for the presidential nomination on the Republican ticket. Lincoln follows his New York appearance with a two-week speaking tour of New England. </p>
"1860/04/23","","Day",<p>The national convention of the Democratic Party, led by Stephen Douglas, meets at Charleston, South Carolina. Southern delegates are determined to enforce a pro-slavery stance in the territories but Northern Democrats oppose such a code and support popular sovereignty in the regions. Douglas fails to reunify the party, and no nominations are handed out. The Alabama delegation walks out of the convention, leading an exodus of members from other Gulf states, as well as those from Georgia, South Carolina, and parts of Arkansas and Delaware. </p>
"1860/05/09","","Day",<p>The Constitutional Union Party, comprised of remnants from the Whig and American parties, nominates John Bell for the presidency and Edward Everett for the vice presidency. </p>
"1860/05/18","","Day",<p>The Republican National Convention in Chicago nominates Abraham Lincoln for the presidency and Hannibal Hamlin for the vice presidency. </p>
"1860/06/18","","Day",<p>The Democratic Party meets again in Baltimore and nominates Stephen Douglas for the presidency and Herschel Johnson for the vice presidency. </p>
"1860/06/28","","Day",<p>The delegations of Southern Democrats, that abandoned the April meeting in Charleston, nominate John C. Breckinridge for the presidency and Joseph Lane for the vice presidency. Their platform supports slavery in the territories. </p>
"1860/11/06","","Day",<p>Abraham Lincoln is elected the sixteenth President of the United States, winning roughly 39 percent of the popular vote. The electoral vote stands at Lincoln with 180, Breckinridge with 72, Bell with 39, and Douglas with 12. In the popular vote, Douglas wins 30 percent, Breckinridge gets 18 percent, and Bell 12 percent. Lincoln carries only 2 of 996 counties in the South. </p>
"1860/12/18","","Day",<p>The Crittenden Compromise is put forth as a last attempt to persuade Southern states to remain in the Union. Kentucky senator John Crittenden proposes constitutional amendments that would extend the Missouri Compromise line across the country, allowing slavery south of the line. Lincoln opposes the plan, affirming that he will not compromise on the issue of slavery, as stated in his Cooper Union address. </p>
"1860/12/20","","Day",<p>A South Carolina convention votes unanimously for an Ordinance of Secession and secedes from the Union. </p>
"1860/01/01","1861/12/31","Year",<p>In congressional elections, the Republicans take control of both the House and Senate. </p>
"1861/01/08","","Day",<p>Buchanan makes his final message to Congress and calls the Union "a sacred trust." Unfortunately, throughout his term, he hesitated to take strong action against secessionist leanings. </p>
"1861/01/09","","Day",<p>Mississippi becomes the second state to secede from Union. </p>
"1861/01/10","","Day",<p>Florida secedes from Union. </p>
"1861/01/11","","Day",<p>Alabama secedes from Union. </p>
"1861/01/19","","Day",<p>Georgia secedes from Union. </p>
"1861/01/26","","Day",<p>Louisiana secedes from Union. </p>
"1861/01/29","","Day",<p>Kansas is admitted to the Union as the thirty-fourth state, entering as a free state. </p>
"1861/02/04","","Day",<p>The Confederate States of America (CSA) is formed in Montgomery, Alabama, from seven secessionist states. On February 7, it adopts a provisional constitution. </p>
"1861/02/09","","Day",<p>Jefferson Davis is elected President of the CSA, with Alexander Stephens as vice president. A provisional congress asserts that all U.S. laws not in accordance with those of the CSA constitution would have no authority in the CSA. </p>
"1861/02/18","","Day",<p>Jefferson Davis is inaugurated as President of the Confederacy.  The capital of the Confederacy, Montgomery, Alabama, will later be moved to Richmond, Virginia. </p>
"1861/02/23","","Day",<p>Texas secedes from Union. </p>
"1861/03/02","","Day",<p>An act of Congress establishes that the territories of Nevada and Dakota will be carved out of Utah Territory and Nebraska Territory, respectively. </p>
"1861/03/04","","Day",<p>Abraham Lincoln is inaugurated as President of the United States. By this time, seven states have already seceded from the Union. </p>
"1861/03/04","","Day",<p>The Confederate "stars and bars" flag, containing seven stars and three stripes, is established and adopted at a convention. During the Battle of Bull Run, the Confederate flag becomes confused with the Union flag, resulting in the creation of a new battle flag, a red field with the blue cross of St. Andrew holding thirteen stars. </p>
