
"1977/01/20","","Day","Carter is inaugurated the thirty-ninth President of the United States."
"1977/01/21","","Day","Carter pardons Vietnam War draft evaders. "
"1977/02/02","","Day","Congress passes Emergency Natural Gas Act, authorizing the President to deregulate natural gas prices due to a shortage in supply. Carter signs the bill and announces plans to present an energy program to Congress. He later proposes the establishment of a cabinet-level Department of Energy. "
"1977/02/15","1977/02/21","Day","Secretary of State Cyrus Vance travels to the Middle East in an attempt to reconvene the 1973 Geneva Conference. "
"1977/02/17","","Day","Soviet dissident Andrei Sakharov receives a written letter of support from President Carter. "
"1977/04/18","","Day","In an address to the nation, Carter calls his program of energy conservation the "moral equivalent of war." "
"1977/05/22","","Day","Carter speaks at Notre Dame University, presenting a new direction in foreign policy which takes the focus off anti-Communism and emphasizes support for fundamental human rights. "
"1977/06/20","","Day","Carter announces opposition to production of the B-1 strategic bomber. "
"1977/07/19","","Day","Newly elected Israeli Prime Minister Menachem Begin meets with Carter in Washington. "
"1977/12/29","1977/12/31","Day","Carter meets with Polish First Secretary Gierek in Warsaw. "
"1977/12/31","1977/01/01","Day","Carter visits the Mohammed Reza Shah Pahlavi, in Tehran, calling Iran "an island of stability" in the Middle East. "
"1978/01/01","1978/01/06","Day","Carter travels to India, Saudi Arabia, Egypt, France, and Belgium. "
"1978/03/09","","Day","Carter invokes the Taft-Hartley Act to end a strike by coal miners. "
"1978/03/17","","Day","Carter warns of the Soviet threat in a foreign policy address at Wake Forest University. "
"1978/06/07","","Day","Carter graduation speech at Annapolis emphasizes the importance of human rights in foreign policy. "
"1978/09/05","1978/09/17","Day","Carter mediates talks between Prime Minister Menachem Begin of Israel and President Anwar Sadat of Egypt at Camp David, resulting in a peace treaty between the two nations. "
"1978/10/15","","Day","Congress passes a revised energy bill eighteen months after Carter proposed it. Congress also passes the Humphrey-Hawkins full employment bill. "
"1978/12/15","","Day","The Carter administration grants full diplomatic status to the People's Republic of China. "
"1979/04/05","","Day","Carter announces his "phase two" energy plan calling for conservation and phasing out price controls on oil. "
"1979/04/20","","Day","President Carter claims a rabbit tried to attack him during a fishing trip in Georgia, and the <i>Washington Post</i> runs a front page story with the headline: "President Attacked by Rabbit." "
"1979/06/07","","Day","Carter approves development of the MX missile. "
"1979/06/18","","Day","Carter signs the second Strategic Arms Limitation Treaty (SALT II) with the USSR. The U.S. Senate never ratifies the controversial treaty, although both nations voluntarily comply with its terms. "
"1979/07/15","","Day","Carter delivers what becomes known as his "malaise speech," blaming the problems of the nation on "a crisis of spirit." "
"1979/07/18","1979/07/19","Day","Carter accepts the resignations of five cabinet members and names Hamilton Jordan chief of staff. "
"1979/09/14","","Day","A <i>Washington Post</i> poll gives Carter the lowest approval rating of any President in three decades. "
"1979/09/15","","Day","Carter collapses in 10K race, leading the press to depict the event as representative of the strength of his presidency.  "
"1979/10/17","","Day","Carter signs a bill establishing the Department of Education and appoints Shirley Hufstedler as its secretary. "
"1979/11/04","","Day","Iranian students take sixty-six Americans hostage at the American embassy in Tehran. "
"1979/12/04","","Day","Carter officially announces his candidacy for reelection. "
"1980/01/03","1980/01/04","Day","Due to the invasion of Afghanistan, Carter asks the Senate to table its consideration of SALT II.  He also placed an embargo on grain sales to the Soviet Union and suggests the possibility of boycotting the Summer Olympics in Moscow. "
"1980/01/23","","Day","Carter announces the "Carter Doctrine" in his State of the Union address, asserting that threats to the Persian Gulf region will be viewed as "an assault of the vital interests of the United States." "
"1980/03/14","","Day","Carter announces his anti-inflation program which includes a proposal for a balanced budget for fiscal year 1981. "
"1980/04/17","","Day","Carter announces that the economy is in recession, with the inflation rates hitting ten percent and interest rates climbing to eighteen percent. "
"1980/04/22","","Day","The U.S. Olympic Committee votes to boycott the Moscow summer Olympics, supporting Carter in protesting the Soviet invasion of Afghanistan. "
"1980/04/25","","Day","Carter announces the failure of "Desert One," the mission to rescue the Iranian-held hostages, and that several American military personnel had been killed. "
"1980/06/01","","Month","Carter's approval rating reaches the lowest mark of any President since 1945. "
"1980/07/25","","Day","Carter signs Presidential Directive 59 advocating a strategy for fighting a "limited" nuclear war. "
"1980/11/04","","Day","Carter loses election to Ronald Reagan, winning only 49 electoral votes to Reagan's 489. "
"1981/01/20","","Day","Ronald Reagan is inaugurated President, and Carter leaves Washington, D.C.  "
