
<h2>1893/3/4</h2>"","",<p>Cleveland is inaugurated, becoming the only President to serve two nonconsecutive terms.</p>
<h2>1893/3/9</h2>"","",<p>Cleveland withdraws the Hawaiian annexation treaty, signed just prior to his inauguration. He takes the advice of a special commissioner who reports that proponents of the annexation are sugar planters; the majority of the population opposes such action. Cleveland advocates the restoration of the queen but the provisional government rejects this idea. </p>
<h2>1893/4/22</h2>"","",<p>For the first time, the U.S. Treasury gold reserve falls below $100 million. This is partially due to the failure of an important British bank which discharges its American holdings in return for gold. </p>
<h2>1893/4/23</h2>"","",<p>Cleveland vows to defend the gold standard. </p>
<h2>1893/5/4</h2>"1893/5/5","",<p>The Panic of 1893 begins after the National Cordage Company and the Philadelphia and Reading railroads go bankrupt on May 4. A sharp decline in the New York stock market follows the next day, known as "Industrial Black Friday." The panic also distresses farm regions. </p>
<h2>1893/6/18</h2>"","",<p>A malignant growth is detected on the roof of Cleveland's mouth. </p>
<h2>1893/6/30</h2>"","",<p>Cleveland calls a special session of Congress for August 7, with the intent of handling the economic crisis through tariff reform and the repeal of the silver-purchase law. Concerned about the low gold reserve, Cleveland wants to end the practice of issuing silver notes that can be redeemed in gold. </p>
<h2>1893/7/1</h2>"","",<p>In a secret operation aboard the yacht <i>Oneida</i> in New York's East River, Cleveland's cancerous growth -- and a portion of his jaw -- are removed. </p>
<h2>1893/8/8</h2>"","",<p>Congress begins debate on the silver issue and tariffs. On August 16, William Jennings Bryan delivers a speech in support of free silver coinage and on August 28, the House votes to repeal the silver clauses of the Sherman Act. </p>
<h2>1893/9/9</h2>"","",<p>Esther Cleveland, Grover's second child, is born. Her birth is the first in the White House. </p>
<h2>1893/11/1</h2>"","",<p>The Sherman Silver Purchase Act, implemented under President Harrison, is repealed. Cleveland supports this policy shift. </p>
<h2>1894/1/17</h2>"","",<p>The United States offers treasury bonds for sale in an effort to increase gold reserves. The measure is unsuccessful, and a second bond sale is offered with similar results. </p>
<h2>1894/2/1</h2>"","",<p>The House passes a tariff revisions bill. </p>
<h2>1894/3/25</h2>"","",<p>Led by rich quarry owner and populist Jacob Coxey, the four hundred members of the "Army of the Commonwealth of Christ" departs from Massillon, Ohio, on a march to Washington. They come to demand that the government take action to alleviate economic depression by providing the unemployed with worthwhile jobs. </p>
<h2>1894/4/29</h2>"","",<p>The "Army of the Commonwealth of Christ" arrives at Capitol Hill. Their arrival had been greatly anticipated and feared by many, but the event proves anti-climactic. Coxey and others are arrested for trespassing. </p>
<h2>1894/5/1</h2>"1894/7/28","Month",<p>Eugene Debs, president of the American Railway Union, organizes a strike by employees of the Pullman railway car company, beginning in Pullman, Illinois. Company workers find themselves forced to live in the company town where costs are higher than elsewhere. Additionally, George Pullman lowers wages, in light of the 1893 depression, but maintains rent and other charges. The strike spreads throughout the West and halts rail service, affecting twenty-seven states and territories. Following a recommendation by Attorney General Richard Olney, Cleveland sends federal troops to Chicago on July 3. Eventually, Debs and others are arrested, and the strike is broken. </p>
<h2>1894/7/4</h2>"","",<p>Hawaii's provisional government declares the Republic of Hawaii. In its constitution, the body includes a provision for possible American annexation. On August 8, the U.S. government recognizes the Republic of Hawaii. </p>
<h2>1894/8/28</h2>"","",<p>The Wilson-Gorman Tariff Bill becomes law without Cleveland's signature (he refuses to veto or sign the measure). The law includes an income tax of 2 percent on all personal income greater than $4,000 and on all corporate income above operating expenses. </p>
<h2>1894/12/1</h2>"1897/6/28","Month",<p>The United States intervenes in a boundary dispute between Venezuela and Britain, eventually invoking the Monroe Doctrine to assert its rights. Britain agrees to arbitration rather than going to war with the United States. </p>
<h2>1895/2/8</h2>"1895/2/20","",<p>A third treasury bond sale to a syndicate headed by J.P. Morgan restores gold reserves and validates the credit of the government.  </p>
<h2>1895/2/24</h2>"","",<p>A revolution begins in Cuba against Spanish rule. By this point, the United States surpasses Spain in its trade with and investment in Cuba. American sympathy lies with the rebels. Under Cleveland, the United States adopts a policy of neutrality; this changes during the administration of President William McKinley. </p>
<h2>1895/5/20</h2>"","",<p>The Supreme Court nullifies the income tax law in <i>Pollock</i> v. <i>Farmers' Loan and Trust Company</i>. </p>
<h2>1895/5/27</h2>"","",<p>The Supreme Court justifies the arrest of Eugene Debs, the leader of the Pullman Strike, upholding the government practice of using injunctions to break strikes in <i>Debs</i> v. <i>the United States</i>. </p>
<h2>1895/7/7</h2>"","",<p>Marion Cleveland, Grover's third child, is born at Gray Gables. </p>
<h2>1896/1/4</h2>"","",<p>Utah is admitted to the union as the forty-fifth state. </p>
<h2>1896/1/6</h2>"","",<p>A fourth bond sale of $100 million is announced. By month's end, it has restored gold reserves to a generally safe level of $124 million. The four bond sales between 1894 and 1896 create $262 million in federal debt. </p>
<h2>1896/6/16</h2>"1896/6/18","",<p>The Republican National Convention chooses William McKinley, on a gold-standard platform, as its candidate for the upcoming presidential election. </p>
<h2>1896/7/7</h2>"1896/7/11","",<p>The Democratic Convention meets and nominates William Jennings Bryan, a Nebraska congressman and champion of silver. The move signals the party's abandonment of the gold standard, upsetting many party members. Populists decide to back Bryan. </p>
<h2>1896/8/7</h2>"","",<p>Democrats unhappy with Bryan's nomination meet in Indianapolis and form the "Gold Democrats." They ask Cleveland to run again for President. When Cleveland turns down their appeal on September 3, the Gold Democrats nominate Senator John M. Palmer. </p>
<h2>1896/11/3</h2>"","",<p>William McKinley is elected President, carrying 51 percent of the popular vote and 271 electoral votes to Bryan's 176.  </p>
<h2>1897/1/11</h2>"","",<p>The United States and Britain sign a treaty of arbitration ending the Venezuelan dispute which began in December 1894. </p>
<h2>1897/2/9</h2>"","",<p>Cleveland vetoes a bill which would ban illiterate immigrants. </p>
<h2>1897/3/4</h2>"","",<p>William McKinley is inaugurated as the twenty-fifth President of the United States. </p>
