
<h2>3 4, 1885</h2>"","",<p>Former New York Governor Grover Cleveland is sworn in and takes office as the twenty-second President of the United States. Cleveland is the nation's first Democratic President since James Buchanan, who served prior to the onset of the Civil War. In his inaugural address, Cleveland promises to adhere to "business principals," indicative of his conservative outlook.</p>
<h2>11 25, 1885</h2>"","",<p>Vice President Thomas Hendricks dies. </p>
<h2>1 19, 1886</h2>"","",<p>Cleveland signs the Presidential Succession Act, specifying that in the absence of a President and vice president, heads of executive departments will succeed to the presidency in the order in which the departments were created. </p>
<h2>4 22, 1886</h2>"","",<p>In a message to Congress, Cleveland asserts that labor is a vital element of national prosperity and should be a concern of the federal government. He suggests the creation of a government committee to resolve disputes between labor and capital, making him the first President to do so. </p>
<h2>5 8, 1886</h2>"","",<p>Cleveland vetoes the first of several bills granting military pensions to Civil War Union veterans who had appealed to Congress after their claims were rejected by the Pensions Bureau. Hundreds of these claims are bogus. </p>
<h2>5 11, 1886</h2>"","",<p>Cleveland recommends to Congress that the nation accept France's gift of the Statue of Liberty. The gift commemorates the alliance between the two countries during the Revolutionary War. The statue will be placed on Liberty Island, adjacent to Ellis Island off the New Jersey coast. Ellis Island will serve as a welcoming center for the soaring number of immigrants to New York City. </p>
<h2>5 25, 1886</h2>"","",<p>Cleveland announces that he is to marry twenty-two year old Frances Folsom, touching off a media frenzy. </p>
<h2>6 2, 1886</h2>"","",<p>Cleveland and Francis Folsom marry. </p>
<h2>10 28, 1886</h2>"","",<p>The Statue of Liberty is dedicated. </p>
<h2>12 8, 1886</h2>"","",<p>Samuel Gompers forms the American Federation of Labor (AFL), a trade union. Gompers, the son of Jewish immigrants from London, arrives in New York City in 1863. The AFL grows for two decades; by 1904, its members comprise ten percent of all nonagricultural wageworkers. In 1912, the AFL will back presidential hopeful Woodrow Wilson in an effort to establish political coalitions. </p>
<h2>2 4, 1887</h2>"","",<p>Following complaints about railroad rates and policies, the Interstate Commerce Commission (ICC) is created to ensure fairness in the management of interstate railroads. Eventually, the scope of the ICC will expand to include all common carriers. The commission is the nation's first independent regulatory agency. Although Cleveland approves its creation, he has reservations about the agency. </p>
<h2>2 8, 1887</h2>"","",<p>Cleveland signs the Dawes General Allotment Act, which attempts to assimilate American Indians into the dominant culture by parceling out reservation land to individuals and families. The act also sets up a procedure by which Indians can become eligible for citizenship if they renounce tribal holdings. The bill successfully weakens traditional Native American culture but does little to increase acceptance for Native Americans in the larger society. </p>
<h2>2 11, 1887</h2>"","",<p>Cleveland vetoes the Dependent Pension Bill, which would have given a military pension to anyone serving a minimum of ninety days in any war. He argues that the bill will only encourage fraudulent assertions. </p>
<h2>2 16, 1887</h2>"","",<p>Cleveland vetoes the Texas Seed Bill, which was designed to provide relief to drought-stricken farmers. Cleveland believes the bill oversteps the powers of the federal government. </p>
<h2>3 3, 1887</h2>"","",<p>The Tenure of Office Act of 1867 is repealed after Cleveland challenges its constitutionality. The act had required that the President gain Senate approval to remove from office any individuals who had received Senate confirmation upon appointment. Congress had passed the bill in order gain control over President Andrew Johnson. </p>
<h2>9 20, 1887</h2>"10 22, 1887","",<p>Cleveland embarks on a tour that takes him to states in the southern and western United States. </p>
<h2>12 6, 1887</h2>"","",<p>In his annual address to Congress, the President argues against protective tariffs, which he claims are creating an excessive surplus. High tariffs were adopted during the Civil War to protect American industrial interests as a temporary measure; they remained in force, however, after the war. Following Cleveland's message, Representative Roger Q. Mills, a Texas Democrat, introduces a moderate bill that reduces rates and favors the South. The Senate rejects this bill and tariff reform becomes one of the divisive issues of the 1888 presidential election. </p>
<h2>1 16, 1888</h2>"","",<p>Cleveland appoints Lucius Q.C. Lamar of Mississippi to the Supreme Court. Previously, Lamar serves as Cleveland's secretary of the interior. </p>
<h2>2 2, 1888</h2>"","",<p>The Civil Service Commission announces amended rules, prompting Cleveland to respond with a letter containing detailed objections. Cleveland is a proponent of civil service reform, and by the time he leaves office in 1889, he will have expanded the list of classified positions filled under the merit system from sixteen thousand to twenty-seven thousand. </p>
<h2>4 30, 1888</h2>"","",<p>Cleveland appoints Melville W. Fuller chief justice of the U.S. Supreme Court. During his second term, the President will come in for significant criticism from political opponents as he will be associated with the conservative decisions of the Fuller Court. </p>
<h2>6 13, 1888</h2>"","",<p>The Department of Labor is established. </p>
<h2>6 25, 1888</h2>"","",<p>Republicans nominate Indiana senator Benjamin Harrison for President. He is the grandson of President William Henry Harrison. New York banker Levi P. Morton serves as Harrison's running mate. </p>
<h2>9 8, 1888</h2>"","",<p>Cleveland accepts the Democratic nomination for President. Ex-Ohio senator Allen G. Thurman is the vice-presidential nominee. </p>
<h2>10 8, 1888</h2>"","",<p>Cleveland renews the Chinese Exclusion Act, restricting Chinese immigration to United States. The law prohibits Chinese immigrants who return to China from coming back to America. President Chester Arthur passes the first such bill in 1882. Barriers to Chinese immigration are not eradicated until 1943. </p>
<h2>11 6, 1888</h2>"","",<p>Although Cleveland wins the popular vote in presidential election, he loses to Harrison in the electoral vote, 233 to 168. </p>
<h2>2 11, 1889</h2>"","",<p>Cleveland signs a bill creating the Department of Agriculture. </p>
<h2>2 22, 1889</h2>"","",<p>Cleveland signs a bill that turns the territories of North Dakota, South Dakota, Montana, and Washington into states. </p>
<h2>3 4, 1889</h2>"","",<p>Benjamin Harrison is inaugurated. In a prophetic statement, Frances Cleveland tells the White House staff that she and Grover will return in four years. </p>
<h2>3 4, 1893</h2>"","",<p>Cleveland is inaugurated, becoming the only President to serve two nonconsecutive terms.</p>
<h2>3 9, 1893</h2>"","",<p>Cleveland withdraws the Hawaiian annexation treaty, signed just prior to his inauguration. He takes the advice of a special commissioner who reports that proponents of the annexation are sugar planters; the majority of the population opposes such action. Cleveland advocates the restoration of the queen but the provisional government rejects this idea. </p>
<h2>4 22, 1893</h2>"","",<p>For the first time, the U.S. Treasury gold reserve falls below $100 million. This is partially due to the failure of an important British bank which discharges its American holdings in return for gold. </p>
<h2>4 23, 1893</h2>"","",<p>Cleveland vows to defend the gold standard. </p>
<h2>5 4, 1893</h2>"5 5, 1893","",<p>The Panic of 1893 begins after the National Cordage Company and the Philadelphia and Reading railroads go bankrupt on May 4. A sharp decline in the New York stock market follows the next day, known as "Industrial Black Friday." The panic also distresses farm regions. </p>
<h2>6 18, 1893</h2>"","",<p>A malignant growth is detected on the roof of Cleveland's mouth. </p>
<h2>6 30, 1893</h2>"","",<p>Cleveland calls a special session of Congress for August 7, with the intent of handling the economic crisis through tariff reform and the repeal of the silver-purchase law. Concerned about the low gold reserve, Cleveland wants to end the practice of issuing silver notes that can be redeemed in gold. </p>
<h2>7 1, 1893</h2>"","",<p>In a secret operation aboard the yacht <i>Oneida</i> in New York's East River, Cleveland's cancerous growth -- and a portion of his jaw -- are removed. </p>
<h2>8 8, 1893</h2>"","",<p>Congress begins debate on the silver issue and tariffs. On August 16, William Jennings Bryan delivers a speech in support of free silver coinage and on August 28, the House votes to repeal the silver clauses of the Sherman Act. </p>
<h2>9 9, 1893</h2>"","",<p>Esther Cleveland, Grover's second child, is born. Her birth is the first in the White House. </p>
<h2>11 1, 1893</h2>"","",<p>The Sherman Silver Purchase Act, implemented under President Harrison, is repealed. Cleveland supports this policy shift. </p>
<h2>1 17, 1894</h2>"","",<p>The United States offers treasury bonds for sale in an effort to increase gold reserves. The measure is unsuccessful, and a second bond sale is offered with similar results. </p>
<h2>2 1, 1894</h2>"","",<p>The House passes a tariff revisions bill. </p>
<h2>3 25, 1894</h2>"","",<p>Led by rich quarry owner and populist Jacob Coxey, the four hundred members of the "Army of the Commonwealth of Christ" departs from Massillon, Ohio, on a march to Washington. They come to demand that the government take action to alleviate economic depression by providing the unemployed with worthwhile jobs. </p>
<h2>4 29, 1894</h2>"","",<p>The "Army of the Commonwealth of Christ" arrives at Capitol Hill. Their arrival had been greatly anticipated and feared by many, but the event proves anti-climactic. Coxey and others are arrested for trespassing. </p>
<h2>May 1894</h2>"July 1894","",<p>Eugene Debs, president of the American Railway Union, organizes a strike by employees of the Pullman railway car company, beginning in Pullman, Illinois. Company workers find themselves forced to live in the company town where costs are higher than elsewhere. Additionally, George Pullman lowers wages, in light of the 1893 depression, but maintains rent and other charges. The strike spreads throughout the West and halts rail service, affecting twenty-seven states and territories. Following a recommendation by Attorney General Richard Olney, Cleveland sends federal troops to Chicago on July 3. Eventually, Debs and others are arrested, and the strike is broken. </p>
<h2>7 4, 1894</h2>"","",<p>Hawaii's provisional government declares the Republic of Hawaii. In its constitution, the body includes a provision for possible American annexation. On August 8, the U.S. government recognizes the Republic of Hawaii. </p>
<h2>8 28, 1894</h2>"","",<p>The Wilson-Gorman Tariff Bill becomes law without Cleveland's signature (he refuses to veto or sign the measure). The law includes an income tax of 2 percent on all personal income greater than $4,000 and on all corporate income above operating expenses. </p>
<h2>12 1894</h2>"6 1897","",<p>The United States intervenes in a boundary dispute between Venezuela and Britain, eventually invoking the Monroe Doctrine to assert its rights. Britain agrees to arbitration rather than going to war with the United States. </p>
<h2>2 8, 1895</h2>"2 20, 1895","",<p>A third treasury bond sale to a syndicate headed by J.P. Morgan restores gold reserves and validates the credit of the government.  </p>
<h2>2 24, 1895</h2>"","",<p>A revolution begins in Cuba against Spanish rule. By this point, the United States surpasses Spain in its trade with and investment in Cuba. American sympathy lies with the rebels. Under Cleveland, the United States adopts a policy of neutrality; this changes during the administration of President William McKinley. </p>
<h2>5 20, 1895</h2>"","",<p>The Supreme Court nullifies the income tax law in <i>Pollock</i> v. <i>Farmers' Loan and Trust Company</i>. </p>
<h2>5 27, 1895</h2>"","",<p>The Supreme Court justifies the arrest of Eugene Debs, the leader of the Pullman Strike, upholding the government practice of using injunctions to break strikes in <i>Debs</i> v. <i>United States</i>. </p>
<h2>7 7, 1895</h2>"","",<p>Marion Cleveland, Grover's third child, is born at Gray Gables, the Cleveland family's vacation home. </p>
<h2>1 4, 1896</h2>"","",<p>Utah is admitted to the union as the forty-fifth state. </p>
<h2>1 6, 1896</h2>"","",<p>A fourth bond sale of $100 million is announced. By month's end, it has restored gold reserves to a generally safe level of $124 million. The four bond sales between 1894 and 1896 create $262 million in federal debt. </p>
<h2>6 16, 1896</h2>"6 18, 1896","",<p>The Republican National Convention chooses William McKinley, on a gold-standard platform, as its candidate for the upcoming presidential election. </p>
<h2>7 7, 1896</h2>"7 11, 1896","",<p>The Democratic Convention meets and nominates William Jennings Bryan, a Nebraska congressman and champion of silver. The move signals the party's abandonment of the gold standard, upsetting many party members. Populists decide to back Bryan. </p>
<h2>8 7, 1896</h2>"","",<p>Democrats unhappy with Bryan's nomination meet in Indianapolis and form the "Gold Democrats." They ask Cleveland to run again for President. When Cleveland turns down their appeal on September 3, the Gold Democrats nominate Senator John M. Palmer. </p>
<h2>11 3, 1896</h2>"","",<p>William McKinley is elected President, carrying 51 percent of the popular vote and 271 electoral votes to Bryan's 176.  </p>
<h2>1 11, 1897</h2>"","",<p>The United States and Britain sign a treaty of arbitration ending the Venezuelan dispute which began in December 1894. </p>
<h2>2 9, 1897</h2>"","",<p>Cleveland vetoes a bill which would ban illiterate immigrants. </p>
<h2>3 4, 1897</h2>"","",<p>William McKinley is inaugurated as the twenty-fifth President of the United States. </p>