
<h2>1993/1/20</h2>"","",<p>William Jefferson Clinton is inaugurated as the forty-second President of the United States.</p>
<h2>1993/1/25</h2>"","",<p>President Clinton announces that First Lady Hillary Rodham Clinton will head the Task Force on National Health Care Reform. The President hopes to reform the nation's health care system so that all Americans have health insurance, ensuring what is called "universal coverage," and to control the sky-rocketing costs of health care. </p>
<h2>1993/2/5</h2>"","",<p>President Clinton signs the Family Medical Leave Act that requires companies to provide workers with up to three months of unpaid leave for family and medical emergencies. </p>
<h2>1993/2/26</h2>"","",<p>Six people are killed and more than a thousand suffer injuries after a bomb planted under the World Trade Center in New York City explodes. The bomb marks the beginning of a string of threats against the United States made during the Clinton administration by both foreign and domestic terrorists. </p>
<h2>1993/3/3</h2>"","",<p>President Clinton appoints Vice President Al Gore to head the National Performance Review, which will devise an initiative entitled "Reinventing Government." The initiative streamlines government by reducing the number of federal employees; it also cuts federal spending as a percentage of GDP to levels unseen since the Kennedy administration. </p>
<h2>1993/3/11</h2>"","",<p>The Senate confirms Janet Reno as attorney general, the first woman to serve in the position. Reno was Clinton's third choice for the position, after his first two selections were scuttled due to financial improprieties. </p>
<h2>1993/4/19</h2>"","",<p>In Waco, Texas, federal law enforcement officers, under the orders of Attorney General Janet Reno, end a 51-day standoff against a religious cult led by self-styled messiah David Koresh. In the ensuing confrontation, the fires that destroy the cult's compound kill at least seventy-five people, and bring Reno widespread criticism for her aggressive handling of the situation. </p>
<h2>1993/6/26</h2>"","",<p>The U.S. Navy, under President Clinton's orders, attacks Iraqi intelligence operations in downtown Baghdad after learning that Iraqis had plotted to kill former President Bush during his April 1993 visit to Kuwait. The twenty-three tomahawk missiles fired reportedly kill eight people. </p>
<h2>1993/7/19</h2>"","",<p>President Clinton announces an "honorable compromise" in the debate surrounding gays in the military. Homosexuals would be allowed to serve, but could face military investigations if they acknowledged their orientation, as well as be expelled for it. The policy is labeled "Don't Ask, Don't Tell." </p>
<h2>1993/7/20</h2>"","",<p>Vince Foster, deputy counsel to the President, is found dead in a Northern Virginia park. Authorities rule his death a suicide, but subsequent federal investigators will re-open the case in the future. </p>
<h2>1993/8/3</h2>"","",<p>The Senate confirms Ruth Bader Ginsburg's nomination to the Supreme Court. Ginsburg succeeds the retiring Byron White and become the second woman to sit on the high court. </p>
<h2>1993/8/10</h2>"","",<p>President Clinton signs the Omnibus Budget Reconciliation Act. The legislation, which passes both houses of Congress by slim majorities, lays out a plan to reduce the budget deficit by $496 billion through 1998, using a combination of spending cuts and tax increases. </p>
<h2>1993/9/13</h2>"","",<p>President Clinton presides over a ceremony in Washington, D.C., at which Israeli Prime Minister Yitzhak Rabin and PLO Chairman Yasser Arafat sign the Israeli-Palestinian Declaration of Principles, the first agreement between Jews and Palestinians, providing for Palestinian self-government in the Gaza Strip and the West Bank. </p>
<h2>1993/9/22</h2>"","",<p>President Clinton unveils a plan for universal health care that would fix what he called a "badly broken" system. Clinton emphasizes that under his plan, all Americans would have high quality health care and would be able to choose their physicians. </p>
<h2>1993/10/4</h2>"1993/10/3","",<p>An elite American special forces unit searching for Somali warlord Mohammed Farah Aidid in Somalia's capital city of Mogadishu is ambushed by Aidid's forces, leaving eighteen Americans dead. Three days later, President Clinton announces that all American military personnel in Somalia will be home by March 31, 1994. </p>
<h2>1993/11/30</h2>"","",<p>President Clinton signs the Brady Act, which requires a potential handgun purchaser to wait five days while a background check is performed by law enforcement officers. </p>
<h2>1993/12/8</h2>"","",<p>After a hard-fought battle in Congress, President Clinton signs the North American Free Trade Agreement (NAFTA), eliminating nearly every trade barrier between the United States, Canada, and Mexico, creating the world's largest free trade zone.  </p>
<h2>1994/1/10</h2>"1994/1/11","",<p>President Clinton attends the NATO summit meeting in Brussels, Belgium, at which he announces that the United States will maintain at least 100,000 troops in Europe. He also introduces the "Partnership for Peace" program aimed at building closer ties between NATO and former Warsaw Pact states.  </p>
<h2>1994/2/3</h2>"","",<p>President Clinton ends the nineteen-year old trade embargo against Vietnam, noting that Vietnam is indeed trying to locate 2,238 Americans listed as missing in action since the Vietnam War. </p>
<h2>1994/3/25</h2>"","",<p>The last American marines leave Somalia. </p>
<h2>1994/5/26</h2>"","",<p>President Clinton renews China's Most Favored Nation trade status, even though China has not made as much progress on human rights issues as he had hoped. </p>
<h2>1994/6/14</h2>"","",<p>President Clinton unveils his welfare reform initiatives. Clinton had campaigned in 1992 on the issue, promising to "end welfare as we know it." </p>
<h2>1994/7/25</h2>"","",<p>President Clinton meets with Prime Minister Yitzhak Rabin of Israel and King Hussein of Jordan. The talks result in Israel and Jordan agreeing in principle to end nearly fifty years of official antagonism. </p>
<h2>1994/8/26</h2>"","",<p>The White House and congressional leaders, including Senate Majority Leader George Mitchell (D-ME), announce that Clinton's ambitious plan for health care reform will not be acted upon in 1994.  Clinton's initiatives fail to find support in Congress.  </p>
<h2>1994/9/13</h2>"","",<p>President Clinton signs into law the Violent Crime Control and Law Enforcement Act that includes provisions providing for the hiring of 100,000 more policemen, and the expansion of the death penalty to cover more than 50 federal crimes. </p>
<h2>1994/9/18</h2>"","",<p>After a tense stand-off with the Clinton administration, Haiti's military government, led by General Raoul Cedras, agrees to cede power. The administration, along with the United Nations, had tried for over a year to restore the democratically elected president of Haiti, Jean-Bertrand Aristide, who had been overthrown in a coup on September 30, 1991. </p>
<h2>1994/10/9</h2>"","",<p>The Clinton administration announces plans to send more than 35,000 troops to the Persian Gulf to deter an Iraqi invasion of Kuwait. Less than three days after the announcement, Iraqi troops pull back from the Iraq-Kuwait border. </p>
<h2>1994/11/8</h2>"","",<p>In mid-term congressional elections, the Republican Party wins control of both houses of Congress for the first time in more than 40 years. It now holds a 53 to 47 advantage in the Senate and a 230 to 214 to 1 lead in the House. </p>
<h2>1994/12/1</h2>"","",<p>The Senate votes to approve the General Agreement on Tariffs and Trade (GATT) that 117 nations, including the United States, agree to in December 1993. The agreement cuts tariffs by more than a third on a wide-range of products and creates a freer international market for goods. </p>
<h2>1994/12/5</h2>"","",<p>President Clinton, along with the presidents of Belarus, Kazakhstan, Russia, and Ukraine, signs the Strategic Arms Reduction Treaty (START I) in Budapest, Hungary. The treaty eliminates more than 9,000 warheads. </p>
<h2>1995/1/23</h2>"","",<p>President Clinton signs the Congressional Accountability Act, requiring Congress to abide by the same anti-discrimination workplace rules that apply throughout the rest of the country. </p>
<h2>1995/1/31</h2>"","",<p>President Clinton authorizes the U.S. Treasury Department to make an emergency loan of up to $20 billion to Mexico to forestall a financial crisis threatening the interconnected Mexican and American economies. </p>
<h2>1995/4/19</h2>"","",<p>In an act of domestic terrorism, a bomb planted in a truck parked in front of the Alfred P. Murrah Federal Building in Oklahoma City, Oklahoma, kills 168 people and causes massive structural damage. In the days following the tragedy, Clinton, in widely-praised efforts, speaks with victims and to the country about how to recover physically, emotionally, and spiritually from the attack. </p>
<h2>1995/7/11</h2>"","",<p>The United States extended full diplomatic recognition of Vietnam, twenty-two years after the United States withdrew military forces from that country. </p>
<h2>1995/8/30</h2>"","",<p>NATO, with a strong contingent of American forces, begins two weeks of air attacks on Serbian positions. </p>
<h2>1995/10/23</h2>"","",<p>President Clinton and Russian president Yeltsin meet in Hyde Park, New York, and continue to discuss ways to improve relations between their two nations, especially with regard to the issue of nuclear arms. </p>
<h2>1995/11/1</h2>"1995/12/28","Month",<p>President Clinton and the Republican-controlled Congress, led by Speaker of the House Newt Gingrich (R-GA), engage in a political death struggle over how to balance the budget by 2002. Failure to reach an agreement leads to the shut-down of certain parts of the federal government, furloughing more than a quarter of a million government workers. </p>
<h2>1995/11/21</h2>"","",<p>In Dayton, Ohio, the representatives of Bosnia, Croatia, and Serbia agree in principle to a peace agreement, brokered by American Richard Holbrooke, to end three years of war in Bosnia.  The agreement establishes a unitary Bosnian state and allows refugees to return home. </p>
<h2>1995/11/29</h2>"1995/2/2","",<p>During a tour of Europe, President Clinton urges the continuation of peace efforts in Northern Ireland. </p>
<h2>1996/1/23</h2>"","",<p>President Clinton, in the annual State of the Union address, declares that "the era of big government is over."  More important, he positions himself as a centrist, moderate Democrat for the upcoming presidential election, hoping that these types of pronouncements will blunt Republican charges that he is too liberal.    </p>
<h2>1996/4/9</h2>"","",<p>President Clinton signs a bill giving him the power of the "line-item veto," which had been requested by Presidents Reagan and Bush. With this new power, Clinton can veto specific items in spending and tax bills without vetoing the entire measure. </p>
<h2>1996/4/10</h2>"","",<p>President Clinton vetoes a bill that would have outlawed certain types of late-term abortions, namely the partial birth abortion. Clinton emerges during his presidency as a strong advocate of the "right to choose," often stating his wish that abortions in the United States become "safe, legal, and rare." </p>
<h2>1996/4/29</h2>"","",<p>Vice President Al Gore attends a Democratic National Committee fundraising event at a Buddhist temple in Los Angeles. Gore and the DNC raise more than $60,000, but so through questionable interpretations of several campaign finance laws. The Clinton administration comes under increasing criticism in its second term for these alleged violations. </p>
<h2>1996/5/15</h2>"","",<p>President Clinton announces that American troops will likely remain in Bosnia as the major component of an international peacekeeping force for an additional eighteen months.  </p>
<h2>1996/5/28</h2>"","",<p>In the first trial to result from the Whitewater investigation, Jim and Susan McDougal, and Arkansas Governor Jim Guy Tucker--Clinton's friends and former business partners in the Whitewater affair--are convicted of fraud. </p>
<h2>1996/8/21</h2>"","",<p>President Clinton signs a health care reform bill that he expects to expand coverage for many Americans. The measure specifically allows workers who change or lose their jobs to keep their health insurance coverage. </p>
<h2>1996/8/22</h2>"","",<p>President Clinton signs a welfare reform bill that radically restructures the American welfare system. The provisions of the new law limit recipients of welfare benefits and enact a "welfare to work" initiative. </p>
<h2>1996/9/3</h2>"","",<p>President Clinton orders a cruise missile strike against Iraq after Saddam Hussein leads a siege against the Kurdish city of Irbil in northern Iraq. </p>
<h2>1996/9/24</h2>"","",<p>An overwhelming majority of United Nations members, including the United States, agree to a treaty banning all nuclear weapons testing. </p>
<h2>1996/11/5</h2>"","",<p>President Clinton, with 49 percent of the vote, defeats Senator Bob Dole (R-KS), with 41 percent of the vote, for the presidency. Clinton becomes the first Democratic President since Franklin Roosevelt to win reelection to a second term. </p>
<h2>1996/12/5</h2>"","",<p>President Clinton selects Madeline Albright, the American ambassador to the United Nations, to serve as his secretary of state. After winning Senate confirmation, Albright is sworn in on January 23, 1997, becoming the first women to hold the position. </p>
<h2>1997/3/11</h2>"","",<p>The Senate votes 99-0 to approve an investigation into the "improper" and "illegal" fund-raising tactics of both the White House and members of Congress. Allegations by Republicans and some Democrats of illegal fund raising by the Clinton White House spur the investigation. </p>
<h2>1997/3/21</h2>"","",<p>President Clinton and President Yeltsin of Russia meet at Helsinki, Finland, and agree to begin negotiations on another nuclear arms reduction treaty (START III) as soon as both nations ratify START II. The United States Senate had ratified START II in January 1996. </p>
<h2>1997/4/24</h2>"","",<p>The Senate ratifies the Chemical Weapons Convention, making illegal the production, acquisition, stockpiling, or use of chemical weapons. </p>
<h2>1997/5/2</h2>"","",<p>The Clinton administration and Republican congressional leaders agree in principle to a five-year budget plan to eliminate the budget deficit.  That goal would be accomplished, largely due to the strong economy of recent years.  </p>
<h2>1997/5/27</h2>"","",<p>In a decision affecting both the scope of presidential power and the immediate future of the Clinton presidency, the Supreme Court rules that Paula Jones can pursue her sexual harassment lawsuit against President Clinton, even while he is in office. </p>
<h2>1997/8/5</h2>"","",<p>President Clinton signs legislation providing for a balanced budget by 2002, ending years of partisan wrangling between Clinton and Republican leaders. </p>
<h2>1997/10/3</h2>"","",<p>Attorney General Janet Reno, in a letter to Congress, announces that the Justice Department's investigation into allegations that the Clinton administration violated campaign finance laws, especially in its efforts to finance the 1996 presidential campaign, has uncovered no major violations.  </p>
<h2>1997/10/28</h2>"1997/10/31","",<p>President Clinton welcomes President Jiang Zemin of China for a state visit. </p>
<h2>1997/10/31</h2>"","",<p>President Clinton orders the United States government to contribute $3 billion to an international bail-out of Indonesia totaling over $22 billion. The Clinton administration argues that the bailout will help stabilize the shaky financial situation in Southeast Asia. </p>
<h2>1998/1/20</h2>"","",<p>News breaks that President Clinton may have had a sexual relationship with a former White House intern named Monica Lewinsky. Clinton, adamantly denying the allegations, states, "I did not have sexual relations with that woman, Miss Lewinsky." </p>
<h2>1998/3/23</h2>"1998/4/2","",<p>President Clinton leaves on a six-country tour of Africa, the first for an American President since 1978. </p>
<h2>1998/4/2</h2>"","",<p>A judge dismisses Paula Jones's sexual harassment lawsuit against President Clinton. </p>
<h2>1998/4/10</h2>"","",<p>Catholic and Protestant leaders in Northern Ireland sign the "Good Friday Peace Accords," a substantial agreement in the Northern Ireland peace process. President Clinton had worked very hard, with several personal appeals to leaders on both sides, to bring about the agreement. </p>
<h2>1998/8/7</h2>"","",<p>Terrorists bomb American embassies in Kenya and Tanzania, killing 224 people, including 20 Americans. United States intelligence believes that Osama bin Laden, a Saudi exile and alleged terrorist leader, is behind the attacks. On August 20, the U.S. military, on orders from President Clinton, launch reprisal strikes on "terrorist related facilities" in Afghanistan, bin Laden's country of residence, and Sudan. The attacks on Sudan, however, come under particular scrutiny, as a number of international observers and members of the Sudanese government contend that the United States destroyed a civilian pharmaceutical facility, and not a chemical weapons plant, as the Clinton administration reported. </p>
<h2>1998/9/11</h2>"","",<p>The Office of the Independent Counsel releases its report on the Clinton-Lewinsky affair, commonly known as the Starr Report. Two days earlier, Independent Counsel Kenneth Starr tells the House that he has uncovered information that may be grounds for impeachment. </p>
<h2>1998/10/23</h2>"","",<p>After nine days of negotiations in rural Maryland, Israeli leader Benjamin Netanyahu and Palestinian leader Yasser Arafat sign the Wye River Memorandum. President Clinton mediates the negotiations, which result in an agreement highlighted by a three-stage withdrawal of Israeli troops from the West Bank. </p>
<h2>1998/12/16</h2>"","",<p>President Clinton orders a three-day bombing attack against Iraq after Saddam Hussein refuses to cooperate with United Nations weapons inspectors. </p>
<h2>1998/12/19</h2>"","",<p>The House of Representatives votes to impeach President Clinton on charges of perjury and obstruction of justice. </p>
<h2>1999/1/20</h2>"","",<p>President Clinton delivers his State of the Union address to a joint session of Congress under remarkable circumstances: six days earlier, the Senate had convened an impeachment trial against the President. Despite the impeachment process, public opinion polls show Clinton with his highest approval ratings. </p>
<h2>1999/2/12</h2>"","",<p>The Senate acquits President Clinton on both articles of impeachment, rejecting one article and splitting evenly on the second. </p>
<h2>1999/3/24</h2>"","",<p>In response to Serbian aggression in Kosovo and Albania, and reports of ethnic cleansing, the United States leads NATO attacks against Serbia. On February 23, Serbian and Kosovar representatives had agreed to a plan that would have granted more autonomy to Kosovo over a three-year period. Serbia reneged on the agreement, prompting U.S. and NATO military action. </p>
<h2>1999/6/10</h2>"","",<p>The NATO air campaign against Serbia ends after Serb forces agree on June 9 to withdraw from Kosovo. KFOR, an international peacekeeping force of 50,000 troops, enforces the agreement. </p>
<h2>1999/10/13</h2>"","",<p>The United States Senate votes down the Comprehensive Test Ban Treaty, which would have prevented the United States from conducting underground nuclear tests. </p>
<h2>1999/11/15</h2>"","",<p>The United States and China agree to a trade treaty reducing tariffs and other trade barriers. The treaty is to come into effect after China joins the World Trade Organization and Congress grants permanent normal trade relations between the two countries.    </p>
<h2>2000/2/1</h2>"","",<p>The Labor Department announces that the nation's business expansion has reached eight years and eleven months, marking the longest economic expansion in American history. </p>
<h2>2000/3/8</h2>"","",<p>President Clinton sends a bill to Congress asking for permanent normal trade relations with China. After securing House (May 24) and Senate (September 19) approval, Clinton signs the bill on October 10. </p>
<h2>2000/6/3</h2>"2000/6/5","",<p>President Clinton holds his first summit meeting with Russian president Vladimir Putin. They reaffirm their nations' commitment to strategic arms reductions, but disagree over American plans to research and develop a missile-defense system. </p>
<h2>2000/7/11</h2>"2000/7/26","",<p>President Clinton hosts Israeli leader Ehud Barak and Palestinian leader Yasser Arafat at Camp David in the hope of reaching a peace agreement. After two weeks of unsuccessful talks, the summit breaks up with no agreement. </p>
<h2>2000/8/14</h2>"","",<p>President Clinton speaks at the opening day of the Democratic National Convention. Vice President Al Gore wins the Democratic nomination for President. His challenger is Republican governor George W. Bush of Texas. </p>
<h2>2000/9/20</h2>"","",<p>Independent Counsel Robert Ray announces that his investigation has not discovered enough evidence to indict the Clintons for their Whitewater dealings. </p>
<h2>2000/10/7</h2>"","",<p>In Serbia, President Slobodan Milosevic declares that Vojislav Kostunica is the rightful president of Serbia. The announcement comes after disputed elections, which Milosevic had tried to rig, produce massive street protests. </p>
<h2>2000/11/7</h2>"","",<p>On election day, Vice President Gore and Governor Bush run so closely that no winner can be declared. Only after the Supreme Court rules on December 13 that there would be no recount of Florida's contested votes does Gore concede the election to Bush. </p>
<h2>2001/1/20</h2>"","",<p>Texas governor George W. Bush is inaugurated as the forty-third President of the United States. </p>
