
"1953/01/20","","Day","Dwight D. Eisenhower is inaugurated as the thirty-fourth President of the United States."
"1953/01/27","","Day","Ralph Ellison wins a National Book Award for Invisible Man. "
"1953/03/05","","Day","The Soviet Union announces the death of Josef Stalin. "
"1953/03/17","","Day","All price controls officially ended by the Office of Price Stabilization. "
"1953/04/01","","Day","The Department of Health, Education, and Welfare is created by joint congressional action. "
"1953/04/16","","Day","Eisenhower delivers his "Chance for Peace" speech to the American Society of Newspaper Editors. "
"1953/05/22","","Day","Eisenhower signs the Submerged Lands Act. "
"1953/06/19","","Day","Julius and Ethel Rosenberg are executed. "
"1953/07/26","","Day","Eisenhower addresses the American public and announces an armistice in Korea. "
"1953/08/01","","Day","Eisenhower proposes broadening the provisions of the Social Security Act to cover more than 10 million additional Americans. "
"1953/08/07","","Day","Eisenhower signs the Refugee Relief Act of 1953, admitting 214,000 more immigrants than permitted under existing immigration quotas. "
"1953/08/19","","Day","Iranians, with the backing of the CIA, overthrow the government of Prime Minister Mohammed Mossadegh, ensuring Mohammed Reza Shah Pahlavi's hold on power. "
"1953/09/10","","Day","Secretary of Labor Martin Durkin resigns, in large part to protest the failure of the Eisenhower Administration to propose amendments to the Taft-Hartley Act. "
"1953/09/30","","Day","Eisenhower appoints Earl Warren chief justice of the Supreme Court. "
"1953/10/08","","Day","Eisenhower announces that the Soviet Union has tested a hydrogen bomb. "
"1953/12/08","","Day","Eisenhower gives his "Atoms for Peace" speech to the U.N. General Assembly in New York. "
"1954/01/11","","Day","Eisenhower sends a special message to Congress asking for changes in the Taft-Hartley labor law. "
"1954/03/08","","Day","The United States and Japan sign a mutual defense agreement that provides for the gradual and partial rearmament of Japan. "
"1954/04/23","1954/06/17","Day","The Army-McCarthy hearings begin and continue for two months. "
"1954/05/07","","Day","France surrenders its garrison at Dien Bien Phu to the Vietminh. "
"1954/05/13","","Day","Eisenhower signs the St. Lawrence Seaway Bill. "
"1954/05/17","","Day","The Supreme Court announces a decision in <i>Brown v. Topeka Board of Education</i>, ruling that racial segregation in public schools is unconstitutional. "
"1954/06/18","","Day","A CIA-sponsored coup in Guatemala overthrows the government of Jacobo Arbenz Guzman. "
"1954/07/11","","Day","The first "White Citizens Council" is organized in Indianola, Mississippi. "
"1954/07/21","","Day","The Geneva Accords are signed, establishing a cease-fire and partition of Vietnam. The United States refuses to sign. "
"1954/09/08","","Day","The United States signs the SEATO (South East Asian Treaty Organization) Pact. "
"1954/11/02","","Day","The Democratic Party narrowly regains control of both houses of Congress. "
"1954/12/02","","Day","The United States signs a mutual defense pact with Taiwan. "
"1954/12/02","","Day","The Senate votes to censure Senator Joseph McCarthy (R-WI). "
"1955/01/10","","Day","Chinese Communist Air Force raid the nationalist-controlled Tachen Islands and seize Ichiang Island. "
"1955/01/19","","Day","The first filming of a presidential press conference. "
"1955/01/21","","Day","Eisenhower meets with Secretary of State Dulles and Secretary of Defense Wilson to discuss a resolution that would authorize the U.S. defense of Taiwan and the Pescadores. Congress approves the resolution on January 28. "
"1955/03/16","","Day","Eisenhower announces that the United States would use atomic weapons in the event of war with Communist China. "
"1955/04/11","","Day","Roy Wilkins becomes Executive Secretary of the NAACP, succeeding Walter White. "
"1955/05/31","","Day","In <i>Brown II</i>, the Supreme Court orders schools integrated "with all deliberate speed." "
"1955/07/12","","Day","Eisenhower tells congressional leaders that the Geneva Conference will not be another Yalta. "
"1955/07/18","","Day","The Geneva Conference opens, attended by the heads of state of Britain, France, the U.S.S.R, and the United States. "
"1955/07/21","","Day","Eisenhower makes his "open skies" proposal at Geneva. "
"1955/07/29","","Day","Plans for the first artificial satellites, scheduled to be launched in 1957, are announced by the United States. "
"1955/08/28","","Day","Fourteen-year old Emmett Till is kidnapped and murdered in Money, Mississippi. "
"1955/09/24","","Day","Eisenhower suffers a "moderate" heart attack in Denver, Colorado. "
"1955/10/10","","Day","The Supreme Court orders Autherine Lucy admitted to the University of Alabama. "
"1955/11/15","","Day","Adlai Stevenson announces that he will run for President in 1956. "
"1955/11/25","","Day"," The Interstate Commerce Commission bans racial segregation on interstate trains and buses. "
"1955/12/01","","Day","Rosa Parks is arrested in Montgomery, Alabama, for refusing to give up her seat on a bus to a white man. During the following week, the Montgomery African American community, led by Reverend Martin Luther King Jr., organizes a boycott of the city's buses that lasts for more than a year. "
"1955/12/05","","Day","The merger of the American Federation of Labor (AFL) and the Congress of Industrial Organizations (CIO) is ratified. "
"1955/12/26","","Day","Eisenhower tries to persuade Richard Nixon to take a cabinet post and not stand for re-election in 1956 as vice president. "
"1956/01/30","","Day","African American student Autherine Lucy is admitted to the University of Alabama following a court order. "
"1956/02/22","","Day","Eisenhower releases $1 billion worth of Uranium-235 for peaceful atomic purposes. "
"1956/02/29","","Day","Eisenhower announces that he will run for a second term as President. "
"1956/03/12","","Day","Nineteen senators and eighty-one representatives sign the "Southern Manifesto," promising to use "all lawful means" to reverse the <i>Brown</i> decisions. "
"1956/04/09","","Day","Eisenhower again urges Nixon to take a cabinet post. "
"1956/04/25","","Day","Eisenhower announces that Nixon will be his running mate in 1956. "
"1956/05/31","","Day","Eisenhower approves U-2 spy flights over the Soviet Union. "
"1956/06/04","","Day","In <i>Browder v. Gayle</i>, a three-judge district court rules that bus segregation in Montgomery, Alabama, is unconstitutional.  "
"1956/06/29","","Day","Eisenhower signs the Federal Aid Highway Act, providing federal funding for the construction of a system of interstate highways for transportation and national defense. "
"1956/07/26","","Day","Egyptian president Gamal Abdel Nasser nationalizes the Suez Canal. "
"1956/08/01","","Day","Eisenhower signs the Social Security Act, permitting women to retire at age sixty-two and disabled workers at age fifty. "
"1956/08/01","","Day","The recently discovered Salk Polio Vaccine is sold on the open market. "
"1956/08/17","","Day","The Democratic National Convention nominates Adlai Stevenson for President. "
"1956/08/21","","Day","Eisenhower attends the Republican National Convention and accepts nomination as the party's candidate for President. "
"1956/09/29","","Day","Eisenhower appoints William J. Brennan to the Supreme Court. "
"1956/10/22","","Day","The Hungarian Revolution begins. "
"1956/10/31","","Day","Israel, Britain, and France attack Egypt; Eisenhower condemns the attack. "
"1956/11/04","","Day","The Soviet Union crushes the Hungarian Revolution via armed intervention. "
"1956/11/05","","Day","A cease-fire is established in Egypt. "
"1956/11/06","","Day","Eisenhower defeats Stevenson by nine million votes to win a second term. Congress remains in the hands of the Democratic Party. "
"1956/11/13","","Day","<i>Browder v. Gayle</i> is upheld by the Supreme Court. "
"1956/12/20","","Day","The Montgomery Bus Boycott comes to an end. "
"1957/01/05","","Day","Eisenhower proposes the "Eisenhower Doctrine" regarding defense of the Middle East. "
"1957/01/06","","Day","Elvis Presley makes his third appearance on the Ed Sullivan Show; and concern that his gyrating dance style is too lewd lead network executives to show him only from the waist up. "
"1957/01/20","","Day","Eisenhower is inaugurated for a second term as President. "
"1957/02/14","","Day","The Southern Christian Leadership Conference (SCLC) is organized in New Orleans. Martin Luther King, Jr., is elected president of the organization. "
"1957/03/07","","Day","Congress sanctions the "Eisenhower Doctrine." "
"1957/05/06","","Day","John F. Kennedy wins a Pulitzer Prize for his book <i>Profiles in Courage</i>. "
"1957/05/29","","Day","Secretary of the Treasury George Humphrey resigns; Eisenhower selects Robert B. Anderson as his replacement. "
"1957/07/12","","Day","The Surgeon General reports that scientific research has established a link between cigarette smoking and lung cancer. "
"1957/08/30","","Day","Senator Strom Thurmond (D-SC) filibusters against pending civil rights legislation for a record twenty-four hours, twenty-seven minutes. "
"1957/09/09","","Day","Eisenhower signs the Civil Rights Act of 1957, the first civil rights bill since Reconstruction. "
"1957/09/24","","Day","Eisenhower orders federal troops to Little Rock, Arkansas, to end the school desegregation crisis. "
"1957/10/04","","Day","The Soviet Union launches <i>Sputnik</i>. "
"1957/11/25","","Day","Eisenhower suffers a vascular spasm. "
"1958/01/27","","Day","Eisenhower asks Congress for federal aid for education. "
"1958/04/01","","Day","Eisenhower signs legislation he hopes will stimulate housing construction and help combat a developing economic recession. "
"1958/04/02","","Day","Eisenhower recommends the formation of a civilian agency to direct space exploration. "
"1958/04/27","","Day","Vice President Nixon embarks on an eighteen-day tour of Latin America. "
"1958/05/13","","Day","Eisenhower orders 1,000 troops from Caribbean bases to rescue Nixon, if necessary, after the Vice President was threatened on his tour of Latin America. "
"1958/05/14","","Day","Eisenhower doubles the strength of the Sixth Fleet in the Mediterranean. "
"1958/06/23","","Day","Eisenhower meets with African American leaders Martin Luther King, Roy Wilkins, A. Philip Randolph, and Lester Granger. "
"1958/07/07","","Day","Eisenhower signs a bill making Alaska the forty-ninth state. "
"1958/07/15","","Day","Eisenhower orders the U.S. Marines into Lebanon. "
"1958/08/23","","Day","The People's Republic of China resumes the shelling of Nationalist Chinese islands Quemoy and Matsu. "
"1958/09/22","","Day","Eisenhower accepts the resignation of Sherman Adams, his chief of staff, after Adams is found to have accepted improper gifts from businessmen. "
"1958/10/25","","Day","Eisenhower orders the withdrawal of the last U.S. Marines from Lebanon. "
"1958/09/02","","Day","Eisenhower signs the National Defense Education Act. "
"1959/01/01","","Day","Fidel Castro's revolutionaries overthrow Cuban dictator Fulgencio Batista. "
"1959/03/18","","Day","Eisenhower signs a bill admitting Hawaii as the fiftieth state. "
"1959/04/13","","Day","Eisenhower asks Nikita Khrushchev for a partial test-ban agreement. "
"1959/04/15","","Day","Secretary of State John Foster Dulles resigns because of illness; he dies on May 24. "
"1959/04/18","","Day","Eisenhower names Christian Herter secretary of state. "
"1959/04/25","","Day","Eisenhower, with Queen Elizabeth, dedicates the St. Lawrence Seaway. "
"1959/07/15","","Day","Eisenhower refuses to seek a Taft-Hartley injunction to end the steelworkers strike. "
"1959/07/24","","Day","Nixon and Khrushchev have their "kitchen debate" in Moscow. "
"1959/09/14","","Day","Eisenhower signs the Landrum-Griffin Act, legislation meant to combat growing corruption in labor organizations. "
"1959/09/27","","Day","Khrushchev visits the United States and meets with Eisenhower at Camp David on September 25 and 26. "
"1959/10/06","","Day","Eisenhower invokes a Taft-Hartley injunction in the dockworkers strike. "
"1959/10/19","","Day","Eisenhower invokes a Taft-Hartley injunction in the steelworkers strike. "
"1960/01/02","","Day","Senator John F. Kennedy announces his candidacy for the Democratic presidential nomination. "
"1960/01/04","","Day","The Steelworkers strike ends with a settlement. "
"1960/01/09","","Day","Vice President Nixon announces his candidacy for the Republican presidential nomination. "
"1960/01/13","","Day","Eisenhower declares his support for Nixon. "
"1960/02/01","","Day","Civil rights sit-ins begin in Greensboro, North Carolina. "
"1960/03/17","","Day","Eisenhower authorizes the CIA to begin training exiles to invade Cuba. "
"1960/04/17","","Day","The Student Nonviolent Coordinating Committee (SNCC), a civil rights group born out of the sit-in demonstrations, organizes in Raleigh, North Carolina. "
"1960/05/05","","Day","The Soviet Union announces that is has shot down an American U-2 spy plane. "
"1960/05/06","","Day","Eisenhower signs the Civil Rights Act of 1960. "
"1960/05/07","","Day","Eisenhower acknowledges that the United States has been conducting U-2 spy flights over the Soviet Union. Khrushchev announces that Francis Gary Powers, a downed U-2 pilot, has admitted to spying on the Soviet Union. "
"1960/05/16","","Day","The Paris Summit between the Soviet Union and the United States ends when Eisenhower refuses to apologize for the U-2 flights and Khrushchev refuses to meet with the President. "
"1960/07/13","","Day","Kennedy receives the Democratic presidential nomination. "
"1960/07/27","","Day","Nixon receives the Republican presidential nomination. "
"1960/09/07","","Day","Eisenhower asks the Soviet Union to stop supporting Patrice Lumumba in the Congo. "
"1960/09/26","","Day","John F. Kennedy and Richard Nixon hold the first televised presidential debate. "
"1960/11/08","","Day","Kennedy defeats Nixon in the presidential election. "
"1961/01/03","","Day","Eisenhower severs diplomatic relations with Cuba. "
"1961/01/17","","Day","Eisenhower's farewell address warns the nation of the growing power of the American "military industrial complex." "
"1961/01/20","","Day","Eisenhower leaves Washington for his Gettysburg farm. "
