
"1973/10/10","","Day","Vice President Spiro T. Agnew resigns, pleading <em>nolo contendre</em> to a charge of income tax evasion."
"1973/10/11","","Day","President Richard Nixon offers Gerald Ford the nomination for vice president. Ford accepts."
"1973/12/06","","Day","Ford is sworn in as vice president in the House chamber. Ford remarks that he is a "Ford, not a Lincoln.""
"1974/08/08","","Day","In a televised address to the nation, Richard M. Nixon resigns the presidency."
"1974/08/09","","Day","Gerald R. Ford is sworn in as the thirty-eighth President of the United States."
"1974/08/12","","Day","Ford speaks to a joint session of Congress regarding inflation."
"1974/08/19","","Day","Ford selects Nelson A. Rockefeller, the former Governor of New York, as his vice president."
"1974/08/28","","Day","Ford holds his first press conference as President. When questioned about the possibility of a pardon for former President Nixon, he replies that he is "not ruling it out.""
"1974/09/08","","Day","Ford grants Richard Nixon a full pardon; his approval rating slips to 49 percent."
"1974/09/16","","Day","The government announces a clemency whereby draft evaders and military deserters could "earn their return to the mainstream of American society" by performing alternative services."
"1974/09/28","","Day","First Lady Betty Ford undergoes surgery for breast cancer (mastectomy)."
"1974/09/30","","Day","Ford forms the Economic Policy Board, which will oversee all aspects of economic policy."
"1974/10/08","","Day","Ford speaks to a joint session of Congress. He calls for a temporary 5 percent tax hike, cuts in federal spending, and the creation of a voluntary inflation-fighting organization, named "Whip Inflation Now" (WIN)."
"1974/10/15","","Day","Ford signs the Federal Elections Campaign Act of 1974, the most significant attempt at campaign finance reform since the 1920s."
"1974/11/05","","Day","In the off-year elections, Democrats are victorious all over the country. They gain 43 House seats and 3 Senate seats, giving them a majority in both Houses of Congress. They also gain 4 governorships."
"1974/11/11","","Day","The President announces his "WIN" campaign (Whip Inflation Now)."
"1974/11/17","","Day","Ford makes a visit to Japan, the first by an American President."
"1974/11/21","","Day","The Freedom of Information Act is passed over Ford's veto. It provides expanded access to government files and allows secrecy classifications to be challenged in court and justified by the appropriate federal authorities."
"1974/12/19","","Day","By a vote of 287-128, the House confirms Nelson A. Rockefeller as vice president; he is later sworn into office."
"1975/01/01","","Day","Ford signs the Privacy Act of 1974, ensuring the right of Americans to individual privacy."
"1975/01/04","","Day","Ford announces the creation of a presidential commission to review abuses by the Central Intelligence Agency ("The Rockefeller Commission")."
"1975/01/13","","Day","In his State of the Union Address, Ford proposes a $16 billion tax cut. "
"1975/03/11","","Day","The Commission on Civil Rights reports that the proportion of blacks in mostly white schools was higher in the South than in the North."
"1975/03/27","","Day","Following the fall of the city of Ban Me Thout, Hue, and Danang, the city of Saigon falls to the North Vietnamese. The Ford administration evacuates remaining Americans and troops from the capital city."
"1975/03/29","","Day","Ford tells the nation he will reluctantly sign the Tax Reduction Act of 1975, which calls for a $22.8 billion tax cut."
"1975/04/04","","Day","Unemployment rises to 8.7 percent, the highest since 1941. "
"1975/04/11","","Day","Cambodia falls to Khmer Rouge."
"1975/05/12","","Day","Cambodia seizes the U.S. merchant ship <em>Mayaguez</em> in the Gulf of Siam and takes its crew hostage. "
"1975/05/14","","Day","Marines move onto Koh Tang, an island off the shore of Cambodia believed to hold the captured sailors of the <em>Mayaguez</em>. Fierce fighting kills fifteen Marines, but the sailors are not found. Ford orders airstrikes on the Cambodian mainland. At 10:35 PM, the crew of the <em>Mayaguez</em> is released."
"1975/05/27","","Day","Ford addresses the nation on the U.S. energy policy."
"1975/06/06","","Day","Unemployment reaches its highest point at 9.2 percent."
"1975/06/19","","Day","The President establishes the President Ford Committee to run his 1976 nomination for the presidential election. "
"1975/07/08","","Day","Ford officially announces his candidacy for the 1976 presidential election. "
"1975/07/26","","Day","President Ford leaves on his second trip to Europe, where he will sign the Helsinki Accords on European security and cooperation. "
"1975/08/10","","Day","First Lady Betty Ford shocks the nation when on the "60 Minutes" television show, she speaks candidly on topics such as extra-marital affairs and marijuana and admits to strongly favoring the Supreme Court's ruling making abortion legal."
"1975/09/04","","Day","Egypt and Israel sign the second-stage Sinai withdrawal agreement."
"1975/09/05","","Day","Lynette "Squeaky" Fromme attempts to assassinate President Ford in San Francisco."
"1975/10/06","","Day","Ford addresses the nation via television asking for a reduction of $28 billion in taxes and spending."
"1975/10/29","","Day","Ford refuses to give federal economic aid to New York City. Instead he advises the city to use financial restraint. The next day, the headline of the New York <em>Daily News</em> reads: "Ford to City&mdash;Drop Dead.""
"1975/11/02","","Day","In what is dubbed by the press as the "Sunday Morning Massacre," Henry Kissinger gives up his position as national security adviser but retains the post of secretary of state; William Colby is fired as director of Central Intelligence, and James Schlesinger is fired as secretary of defense. "
"1975/11/04","","Day","Ford names Donald Rumsfeld secretary of defense, Eliot Richardson secretary of commerce, and George H.W. Bush director of the CIA. He also appoints Brent Scowcroft national security adviser and Richard Cheney White House chief of staff. "
"1975/11/04","","Day","Rockefeller withdraws his name for consideration for the vice presidency in the 1976 presidential election. "
"1975/11/20","","Day","Former California governor Ronald Reagan announces that he will challenge Ford for the Republican nomination for President."
"1975/11/27","","Day","Following a tax increase by the New York state legislature and an agreement by banks and teachers unions preventing New York City from falling into default, Ford requests $2.3 billion in U.S. loans for the city. "
"1975/12/22","","Day","Ford signs the Energy Policy Conservation Act."
"1976/01/19","","Day","Ford gives his State of the Union address. "
"1976/01/30","","Day","The Supreme Court rules on the Federal Election Campaign Act. "
"1976/02/07","","Day","The Labor Department reports that the unemployment rate dropped substantially from December to January, from 8.3 percent to 7.8 percent. "
"1976/02/17","","Day","Ford asserts that the government's intelligence community will undergo reorganization."
"1976/02/24","","Day","Ford beats Ronald Reagan in the New Hampshire primary, winning 51 percent of the vote."
"1976/03/01","","Day","Under pressure from Reagan and more conservative Republicans, Ford agrees not to use the word "d&eacute;tente." "
"1976/03/24","","Day","The Concorde supersonic jet makes its first flight between Europe and the United States. "
"1976/04/16","","Day","In resolving an inter-agency dispute, Ford decides to build up the country's strategic oil reserve in order to protect the United States from another foreign embargo."
"1976/04/20","","Day","During the first quarter of 1976, the GNP rises to 7.5 percent. Inflation is at 3.7 percent."
"1976/05/14","","Day","Ford asks Congress to accept a timetable for extensive reform of the government's regulatory program and agencies."
"1976/05/18","","Day","Ford approves congressional revisions in the Federal Elections Commission and Federal Election Campaign Act to permit resumption of federal check-off subsidies for all presidential campaigns. "
"1976/05/28","","Day","Fords signs a treaty with the Soviet Union limiting underground nuclear testing."
"1976/06/20","","Day","Following the murder of the American ambassador and his aide, Ford orders the evacuation of 116 Americans and 146 third-country nationals from Lebanon."
"1976/07/04","","Day","The nation celebrates its Bicentennial. President Ford speaks at Valley Forge and Independence Hall."
"1976/07/15","","Day","Former Georgia governor Jimmy Carter wins the Democratic nomination for the presidency."
"1976/07/21","","Day","Viking I lands on Mars."
"1976/07/21","","Day","The inflation rate drops from 12.2 in the latter months of 1974 to 4.6 in the first six months of 1976."
"1976/08/06","","Day","The Labor Department announces that employment has risen by 3.8 million people since March 1975."
"1976/08/19","","Day","After a hard fought battle against former Governor Ronald Reagan of California, the Republican National Convention nominates Ford as its presidential candidate (Ford wins with 1,187 votes to Reagan's 1,070). Ford selects Senator Robert Dole from Kansas as his running-mate."
"1976/08/25","","Day","James A. Baker becomes Ford's campaign manager."
"1976/09/09","","Day","Mao Zedong dies, leaving China in a state of unrest. "
"1976/09/13","","Day","Ford signs the "sunshine" law and vetoes government funding for a prototype electrical automobile engine, which Congress and the Senate override soon thereafter. The veto marks Ford's fifty-six while in office."
"1976/09/26","","Day","The first Ford-Carter Debate, held in Philadelphia's Walnut Theatre, centers on domestic policy."
"1976/10/06","","Day","Carter wins the second debate in San Francisco, with Ford making a large blunder, declaring that there "is no Soviet domination of Eastern Europe and never will be under a Ford administration.""
"1976/10/12","","Day","Ford is pelted with eggs by an antagonistic crowd while campaigning in New York City. "
"1976/10/21","","Day","A Gallup poll shows Ford reducing the gap between Carter and himself to 6 percent. "
"1976/10/22","","Day","The third presidential debate is held at the College of William and Mary in Williamsburg, Virginia. Carter edges ahead in the race. "
"1976/11/02","","Day","Jimmy Carter defeats Gerald Ford for the presidency, winning 49.9 percent of the popular vote to Ford's 47.9 percent, and capturing 297 electoral votes to Ford's 240."
"1976/11/07","","Day","Peace is declared in Lebanon after more than fifty ceasefires and 35,000 deaths. "
"1976/11/13","","Day","As many as ninety members of Congress are implicated in a scandal for accepting illegal gifts from an agent of the South Korean government."
"1976/12/15","","Day","The administration announces that it plans to store as many as 500 million barrels of crude oil in salt dunes on the Gulf Coast."
"1976/12/31","","Day","Ford proposes that Puerto Rico become the fifty-first state without consulting Congress; critics contend that the proposal violates the principle of self-determination."
"1976/12/31","","Day","Inflation holds steady at a low 4.8 percent, the best in four years, but high unemployment persists. "
"1977/01/20","","Day","Ford leaves Washington, D.C., after Jimmy Carter is inaugurated the thirty-ninth President of the United States."
