
<h2>3 4, 1881</h2>"","",<p>A self-made man, Republican James A. Garfield is sworn in as the twentieth President of the United States. Garfield served in the Union Army and in the House of Representatives before running for President. Winning the popular election by an very small margin -- only 10,000 votes -- Garfield owes his success partially to New York political boss and Senator William Conkling. In return, Garfield pledges to consult Conkling on government nominations.</p>
<h2>3 5, 1881</h2>"","",<p>Garfield completes his slate of cabinet members, naming James G. Blaine as secretary of state and Abraham Lincoln's son, Robert, as secretary of war. Garfield angers Conkling with his nomination of William Windom of Minnesota, a non-Eastern man, as secretary of treasury. Further, Garfield denies Conkling influence in New York politics by appointing William H. Robertson as collector of the port of New York and Thomas L. James postmaster of New York. </p>
<h2>3 22, 1881</h2>"","",<p>Garfield sends his list of nominations to the Senate, which includes New York senator Conkling's contingent. Conkling will continue to be a source of conflict for the President. </p>
<h2>3 23, 1881</h2>"","",<p>Garfield removes E. A. Meritt from the collectorship of the New York Customhouse after Conkling feels assured that the President would not make any such changes. Garfield then sends W. H. Robertson's name to the Senate as his replacement, intensifying the struggle between Garfield and Conkling. </p>
<h2>5 4, 1881</h2>"","",<p>A Democratic filibuster, which ties up the Senate beginning March 23, ends when Garfield agrees to remove certain appointments. The end of the filibuster allows Garfield to push for Robertson's confirmation to the New York Customhouse. Earlier, Senator Conkling threatens to publish the Hubbell letter, which appears to link Garfield to the Star Route Scandal, a scheme to skim money from the U.S. Post Office. The link is not a significant one, however, and the publication of the letter proves more damaging to Conkling than Garfield. </p>
<h2>5 5, 1881</h2>"","",<p>On the eve of the senatorial vote on the New York nominees, Garfield learns that Conkling intends to delay action on other nominees and moves for adjournment before Robertson can be considered. Garfield removes all of his nominations with the exception of Robertson. </p>
<h2>5 16, 1881</h2>"","",<p>New York senators Roscoe Conkling and Tom Platt resign to protest Garfield's removal of New York nominees to secure Robertson's confirmation. </p>
<h2>5 18, 1881</h2>"","",<p>The Senate confirms Robertson as collector of customs for the port of New York. </p>
<h2>5 21, 1881</h2>"","",<p>Clara Barton organizes the American Association of the Red Cross, modeled after the International Red Cross, in Washington, D.C. Barton serves as the organization's volunteer president until 1904. </p>
<h2>7 2, 1881</h2>"","",<p>Charles J. Guiteau, a mentally unstable Stalwart attorney who had been denied a consular post, shoots Garfield in a Washington railroad station. "I am a stalwart," Guiteau proclaims. "Arthur is now President of the United States." </p>
<h2>7 4, 1881</h2>"","",<p>Established in 1880, the Normal School for Colored Teachers, now Tuskegee University, officially opens its doors in Tuskegee, Alabama. Dr. Booker T. Washington serves as the school's first president. </p>
<h2>9 19, 1881</h2>"","",<p>James Garfield dies from blood poisoning and complications after surgeons search endlessly to find the lost bullet in his back, lodged in his pancreas. Vice President Chester A. Arthur becomes the twenty-first President of the United States The assassin, Guiteau, will be hanged on June 30, 1882. </p>
