
 
<h2>3 4, 1869</h2>"",""<p>Ulysses S. Grant, the Civil War hero and Republican candidate, is inaugurated as the eighteenth President of the United States.</p> 
<h2>5 </h2>"",""<p>The first transcontinental railroad is completed at Promontory Point, Utah, through the work of the Union Pacific and Central Pacific track crews. </p>
<h2>9 24, 1869</h2>"",""<p>The "Black Friday" financial panic takes place in New York City.  The panic results from the efforts of two railroad entrepreneurs, Jay Gould and James Fisk, Jr., to corner the gold market. Gould and Fisk, along with President Grant's brother-in-law, frame their argument by claiming that if the government refrains from selling gold, its value will increase and improve depressed farm prices. A suspicious Grant finally orders a large sale of $4 million in gold, ruining many speculators. The gold plot is the first of several scandals to take place during the Grant years. </p>
<h2>11 29, 1869</h2>"",""<p>President Grant's military aide and private secretary Orville Babcock signs a treaty to annex Santo Domingo of the West Indies, and a second document to lease Samana Bay. The Senate defeats the annexation treaty on June 30, 1870, and never votes on the Samana Bay treaty. </p> 
<h2>1 2, 1870</h2>"",""<p>Construction of the Brooklyn Bridge begins. It will be the longest suspension bridge in the world when completed thirteen years later. </p>
<h2>1 11, 1870</h2>"",""<p>Grant vetoes the Private Relief Bill and will continue to veto many additional relief bills during his two terms. </p>
<h2>1 26, 1870</h2>"",""<p>Virginia is readmitted to the Union after completing its reconstruction. </p>
<h2>2 9, 1870</h2>"",""<p>The United States Weather Bureau is established. Originally, the Bureau is part of the Signal Corps. </p>
<h2>2 23, 1870</h2>"",""<p>Mississippi is readmitted to the Union. </p>
<h2>3 30, 1870</h2>"",""<p>Texas is readmitted to the Union. </p>
<h2>3 30, 1870</h2>"",""<p>Black male suffrage becomes universal when the Fifteenth Amendment -- stipulating that no state shall deprive any citizen of the right to vote because of "race, color, or previous condition of servitude" -- is adopted with Grant's help and approval. The suffrage amendment is only partially successful. During Reconstruction, black men vote frequently; following Reconstruction, however, whites use discriminatory laws and taxes to disenfranchise black men. </p>
<h2>5 </h2>"",""<p>Grant issues a proclamation against the attempts of the Fenian Brotherhood to damage Anglo-United States relations by attacking Canada. The next day, the Fenian Army of Vermont attempts to invade Canada but is driven back. The British government agrees to handle compensation for Canada in the Treaty of Washington in 1871, which will be signed by both nations on May 8, 1871. </p>
<h2>5 </h2>"",""<p>Congress makes it a federal crime to deprive anyone of his civil or political rights by interfering with the right to vote. It is the first of three such enforcement acts the legislature will pass. The act is designed to allow the federal government to take action against the Ku Klux Klan when local authorities fail to prosecute crimes. The KKK, organized in 1866 in Pulaski, Tennessee, employs harassment and terror to dissuade African-Americans from voting. </p>
<h2>6 22, 1870</h2>"",""<p>Congress passes an act creating a Department of Justice under the direction of an attorney general. </p>
<h2>7 14, 1870</h2>"",""<p>A new tariff is passed following debates about tariff reduction. The new law maintains most existing protectionist features. </p>
<h2>2 28, 1871</h2>"",""<p>The Federal Election Law passes, calling for federal supervision of elections in cities with populations greater than 20,000. The act is designed to ensure fair treatment of black voters in the South and is the second of three enforcement acts. </p>
<h2>3 3, 1871</h2>"",""<p>An Indian Appropriation Act is passed with an amendment ending tribal recognition and the treaty system. All Indians are made wards of the state. </p>
<h2>3 4, 1871</h2>"",""<p>Grant establishes the first civil service commission. Without additional appropriations from Congress, however, the commission is rendered ineffective. </p>
<h2>4 20, 1871</h2>"",""<p>The third of the Enforcement Acts, the Ku Klux Klan Act, is passed to enforce the Fourteenth Amendment in the South. It outlaws activities such as wearing disguises, forming conspiracies, and intimidating officials. Grant has worked extensively to secure such legislation to fight the Klan and uses the provisions of the act to ensure fairness in the election of 1872. </p>
<h2>5 </h2>"",""<p>The Treaty of Washington is signed between the United States and Britain, initiating friendly relations between the two nations. The treaty provides for an arbitration procedure to settle the <i>Alabama</i> claims, in which the United States demands that Britain pay for damages to American shipping during the Civil War caused by Confederate vessels built and equipped in England. The treaty also renews Canadian-American fishing arrangements. </p>
<h2>9 4, 1871</h2>"",""<p>A citizen's commission is formed in New York to investigate corruption at William M. "Boss" Tweed's Tammany Hall. A major political power in the city since its formation in 1789, the organization had been associated with bribery and fraud. Tammany's dedication to the city's lower classes and immigrants explains its endurance on the political scene. </p>
<h2>10 8, 1871</h2>"10 11, 1871",""<p>The city of Chicago is nearly burned to the ground in one of the worst disasters in U.S. history. The rise of skyscrapers, as part of the city's rebuilding project, marks an innovation in urban architecture. </p>
<h2>10 12, 1871</h2>"",""<p>Grant issues a proclamation against the Ku Klux Klan in South Carolina. </p>
<h2>3 10, 1872</h2>"",""<p>Grant appoints a special Interoceanic Canal Commission to determine the best of three proposed canal plans connecting the Atlantic with the Pacific. In February 1876, the commission reports in favor of a route through Nicaragua. </p>
<h2>4 15, 1872</h2>"",""<p>Grant becomes the first President to veto a Private Pension Bill. He will veto five such bills while in office. </p>
<h2>6 5, 1872</h2>"6 6, 1872",""<p>The Republican National Convention nominates Grant for reelection and Senator Henry Wilson for vice president. </p>
<h2>7 9, 1872</h2>"",""<p>The Democratic National Convention nominates <i>New York Tribune</i> editor Horace Greeley for President and Missouri Governor Benjamin Gratz Brown for vice president. An avid reformer, Greeley is first approved by Liberal Republicans who favor free trade, civil service reform, and the restoration of former Confederates' rights. The Democratic Party opts to endorse Greeley as the only candidate who can possibly defeat Grant and the Radical Republicans. </p>
<h2>9 14, 1872</h2>"",""<p>After a meeting in Geneva, the five-person arbitration panel established by the Treaty of Washington issues its report. The panel dismisses the "indirect claims" first proposed by irate Senator Charles Sumner. Secretary of State Hamilton Fish had expected this rejection and submitted claims to the panel in order to settle the issue and silence Sumner. The panel does, however, require that Britain pay the United States $15.5 million in gold. The payment is made within one year without protest. </p>
<h2>11 5, 1872</h2>"",""<p>Grant is reelected in the largest popular-majority victory for a Republican in the nineteenth century. He wins 55.6 percent of the popular vote and 214 electoral votes to Greeley's 80. The result is more an expression of dislike for Greeley than support for Grant. </p>
<h2>1 6, 1873</h2>"",""<p>The House of Representatives adopts a resolution to investigate the relations of Credit Mobilier in conjunction with the Union Pacific Railroad. In 1872, the <i>New York Sun</i> published the story of a scandal in which Union Pacific Railroad directors used the dummy Credit Mobilier Corporation to pay themselves from the railroad treasury; additionally they had bribed congressmen to avoid an investigation. Thirteen Senators are involved, although only two receive censure. </p>
<h2>2 12, 1873</h2>"",""<p>A coinage act passed by Congress omits silver currency due to scarcity. When Nevada mines begin producing greater quantities of silver, they demand renewed coinage, referring to the coinage act as the "Crime of '73." </p>
<h2>2 27, 1873</h2>"",""<p>A House resolution censures Oakes Ames of Massachusetts and James Brooks of New York for connections with the Credit Mobilier scandal. </p>
<h2>3 3, 1873</h2>"",""<p>Congress passes an appropriations bill raising senior government salaries and providing two years' back pay for members of Congress. The "back-pay grab" or "salary grab bill" generates significant public criticism of Congress. </p>
<h2>3 4, 1873</h2>"",""<p>Grant is inaugurated for his second term as President, and Vice President Henry Wilson is sworn in. </p>
<h2>9 18, 1873</h2>"",""<p>The failure of the prominent brokerage firm Jay Cooke & Company initiates the Panic of 1873. The underlying causes for the panic are rapidly expanding railroads, over-speculation in land and securities, and excessive issuance of paper money and inflation. As rampant selling takes place, the panic will cause the New York Stock Exchange to close for ten days on September 20. The Panic initiates six years of depression. </p>
<h2>10 31, 1873</h2>"",""<p>A Spanish cruiser near Cuba captures an alleged U.S. ship, the <i>Virginius</i>, and argues that the ship was sent to provide armaments for an invasion of the island. Before Spain's instructions not to impose the death penalty could reach Cuba, fifty-three of the men captured on the ship are executed. Tensions are calmed when Secretary of State Fish and the Spanish minister to the United States sign an agreement providing for the return of the remaining prisoners and the payment of an indemnity. </p>
<h2>11 19, 1873</h2>"",""<p>William M. "Boss" Tweed of New York's Tammany Hall is convicted on 204 charges of fraud, having relieved New York City of roughly $200 million through corrupt enterprise. He is sentenced to twelve years in prison and fined $12,550. The court of appeals will reduce his sentence, but Tweed will be arrested again in connection with other charges after his release. Tweed escapes from prison in1875 and flees to Cuba and then Spain before being recaptured. Samuel J. Tilden gains recognition for his role in breaking up the Tweed ring and reasserting control of the Democratic organization in the city. </p>
<h2>1 20, 1874</h2>"",""<p>The "salary grab bill" of March 3, 1873, is repealed, with the exception of sections pertaining to the President and Supreme Court justices. </p>
<h2>4 22, 1874</h2>"",""<p>After vacillating on the issue, Grant vetoes the inflation bill, passed by Congress, which would have increased the money supply by $100 million to alleviate the effects of the depression. Grant understands the motivation behind the measure but believes that inflating the currency is a dangerous strategy. </p>
<h2>9 15, 1874</h2>"",""<p>Grant issues a presidential proclamation calling for the dispersal of the rebellious "White League" in Louisiana. Grant sends five thousand troops and three gunboats to New Orleans; the resistance ends two days later. Grant and the Republicans are criticized severely for the intervention. </p>
<h2>11 18, 1874</h2>"11 20, 1874",""<p>The Women's Christian Temperance Union (WCTU) is established in Cleveland, Ohio. The group is founded after a massive movement to protest the traffic of liquor in the Midwest spreads across the country. </p>
<h2>Fall 1874</h2>"",""<p>Benefiting from public discomfort over the economy and governmental corruption, Democrats enjoy success in midterm congressional elections, gaining seats in the Senate and a majority in the House. These legislators will take a more aggressive approach to the Grant scandals. </p>
<h2>1 10, 1875</h2>"",""<p>The Hawaiian Reciprocity Treaty is signed, making the islands a virtual protectorate of the United States. The treaty gives preferential and exclusive trade status to Hawaii and prevents the Hawaiians from giving any territory to a third power. </p>
<h2>1 14, 1875</h2>"",""<p>The Specie Resumption Act is passed, allowing fractional currency and legal-tender notes to be redeemed for coin, beginning January 1, 1879. Sponsored by John Sherman, the bill also increases the number of national banks throughout the country. Grant sends a special message to Congress approving the bill. </p>
<h2>3 1, 1875</h2>"",""<p>Grant signs the Civil Rights Act of 1875, guaranteeing blacks equal rights in public places and prohibiting the exclusion of blacks from jury duty. The act includes no enforcement provisions and will be declared unconstitutional by the Supreme Court in 1883. School integration, championed by the now-deceased Charles Sumner, is not included in the bill. The act, nevertheless, creates an important precedent. </p>
<h2>5 </h2>"",""<p>Two-hundred thirty-eight people are indicted in connection with the "Whiskey Ring Scandal," in which distillers conspired with Treasury Department officials to defraud the government of millions of dollars in liquor taxes. Distillers had bribed Treasury officials to evade the taxes. Grant's private secretary, Orville E. Babcock, will be indicted later in the year, another example of Grant's poor choice of appointees. </p>
<h2>11 22, 1875</h2>"",""<p>Vice President Henry Wilson dies. </p>
<h2>12 7, 1875</h2>"",""<p>In his annual message to Congress, Grant advocates nonsectarian and compulsory education. </p>
<h2>12 15, 1875</h2>"",""<p>A resolution against third presidential terms receives overwhelming support in the House and is directed at Grant. The President, however, has already stated in May that he does not intend to run for reelection. </p>
<h2>4 4, 1876</h2>"",""<p>Impeachment articles against Secretary of War William W. Belknap are presented to the Senate. Belknap and his late wife had engaged in a scandal involving bribes from traders at Indian trading posts. Belknap resigns. </p>
<h2>6 14, 1876</h2>"6 16, 1876",""<p>The Republican National Convention nominates Rutherford B. Hayes of Ohio for President and William A. Wheeler for vice president. </p>
<h2>6 25, 1876</h2>"",""<p>General George A. Custer and 265 men of the Seventh Cavalry are killed in a battle with Sitting Bull's Sioux Indians at Little Big Horn. </p>
<h2>6 27, 1876</h2>"6 29, 1876",""<p>The Democratic National Convention nominates Samuel J. Tilden for President and Thomas A. Hendricks for vice president. Tilden, a millionaire corporate lawyer and reform governor of New York, overthrew the corrupt Tweed Ring. </p>
<h2>7 22, 1876</h2>"",""<p>Congress authorizes the minting of $10 million in silver for coinage to be exchanged for legal tender notes. The trade dollar is no longer to be legal tender. </p>
<h2>8 1, 1876</h2>"",""<p>Colorado is admitted to the Union as the thirty-eighth state. </p>
<h2>8 1, 1876</h2>"",""<p>The Senate acquits Secretary of War Belknap. While few Senators doubt his guilt, Belknap has already resigned, and therefore most Senators believe he is not constitutionally impeachable as a result. </p>
<h2>11 7, 1876</h2>"",""<p>The presidential election results are inconclusive. Tilden appears to have a 300,000 edge in the popular vote as well as 184 electoral votes to Hayes's 165. But the returns from Florida, Louisiana, and South Carolina, representing 19 electoral votes, are disputed. </p>
<h2>1 29, 1877</h2>"",""<p>Both parties in Congress agree to establish a commission to determine results of the contested presidential election. The commission will be composed of five members of each house of Congress and five members of the Supreme Court. The commission contains eight Republicans and seven Democrats. </p>
<h2>2 26, 1877</h2>"",""<p>Ohio Republicans and southern Democrats meet in Washington, D.C., and forge the Compromise of 1877. The Democrats promise to withdraw opposition to Hayes, who will in turn remove federal troops from Louisiana and South Carolina. Following the troops' removal, the Republican governments in both states collapse, marking the end of Reconstruction. </p>
<h2>3 2, 1877</h2>"",""<p>The Senate accepts the decision of the electoral commission, which awards the contested electoral votes and the presidency to Rutherford B. Hayes in an 8-7 vote along party lines. Though the House disagrees, the Senate's approval proves sufficient to justify the findings of the electoral commission; the House votes to accept the report. </p>
<h2>3 3, 1877</h2>"",""<p>Rutherford B. Hayes is privately sworn in as the nineteenth President of the United States. Because March 4 falls on a Sunday, he will be publicly sworn in on March 5. </p> 
