
"1921/03/04","","Day",<p>Warren G. Harding is inaugurated as the twenty-ninth President of the United States. Described by one contemporary as a "great looking President," Harding lacks experience in international affairs, reflecting the general disinterest of the American public toward such issues.</p>
"1921/04/20","","Day",<p>The Thompson-Urrutia Treaty with Colombia is ratified. The treaty grants Colombia $25 million as compensation for the loss of Panama, which had gained its independence in 1903 with the help of the United States. </p>
"1921/05/19","","Day",<p>Harding signs the Emergency Quota Act into law, limiting the number of immigrants from any given country to 3 percent of that nationality already in the United States by 1910. The temporary act lasts three years and serves as the precursor to the harsher and permanent 1924 act. The law represents the growing nativism of the 1920s, motivated, in part, by the massive influx of south and east European immigrants into the United States following the end of World War I. </p>
"1921/05/27","","Day",<p>In response to American public opinion, Harding and Congress pass the Emergency Tariff Act. Raising tariffs, especially on farm products, the temporary bill will be replaced one year later by the Fordney-McCumber Tariff Act, a permanent bill with even higher tariff rates. Designed to protect American products and end the post-war recession, such protectionist legislation ultimately destabilizes international commerce by heightening economic nationalism. </p>
"1921/05/31","","Day",<p>In a relatively unnoticed move, Secretary of the Navy Edwin Denby transfers control of the naval oil reserves in California and Wyoming to the Department of the Interior, headed by Albert B. Fall. The reserves at Teapot Dome, Wyoming, will later figure prominently in the scandals that stain the Harding administration. </p>
"1921/06/10","","Day",<p>Harding signs the Budget and Accounting Act in order to better organize the federal government's accounts. The act establishes the Bureau of the Budget and the General Accounting Office under the Treasury Department. </p>
"1921/06/20","","Day",<p>Alice Robertson of Oklahoma becomes the first woman to preside over the House of Representatives. Her session lasts thirty minutes. </p>
"1921/06/30","","Day",<p>Harding appoints former President William Howard Taft as chief justice of the Supreme Court. </p>
"1921/07/02","","Day",<p>Harding signs a joint congressional resolution declaring the official end of war with Germany. The question of reparations will continue to be debated over the next few years. </p>
"1921/09/26","","Day",<p>Secretary of Commerce Herbert Hoover presides over a conference on unemployment in Washington, D.C., as unemployment reaches a post-war high of 5.7 million. In addition, the nation witnesses a wave of violence by a revitalized Ku Klux Klan. Blacks, returning from the war, are not as ready to return to their previous condition of subservience and are met by whippings, brandings, and lynchings by the KKK. </p>
"1921/11/12","1921/02/06","Day",<p>The United States convenes the Washington Naval Armament Conference.  Along with major naval powers Britain, France, Italy, and Japan, the United States signs a treaty limiting capital ship tonnage. The conference will also produce a larger agreement that also includes China, the Netherlands, Belgium, and Portugal which recognizes America's Open Door Policy toward China as international policy. </p>
"1921/11/23","","Day",<p>In response to reports indicating that fully 80 percent of American women do not receive adequate prenatal care, Harding signs the Sheppard-Towner Maternity and Infancy Act, granting matching federal funds to states for maternal and child care. The legislation also recognizes the emergent political power of women, a constituency which gained the right to vote during the previous year. </p>
"1921/12/23","","Day",<p>Harding pardons Eugene Debs along with twenty-three others found guilty under the wartime Espionage Act. </p>
"1922/02/18","","Day",<p>Responding to the continuing problems facing American farmers, which force 300,000 farm foreclosures during the Harding administration alone, the President signs the Capper-Volstead Act. The bill allows farmers to buy and sell cooperatively without the risk of prosecution under anti-trust laws. </p>
"1922/02/27","","Day",<p>The Supreme Court unanimously finds the Nineteenth Amendment, providing for women's suffrage, constitutional. </p>
"1922/04/07","","Day",<p>Interior Secretary Albert B. Fall leases the Teapot Dome oil reserves to Harry Sinclair, setting in motion what comes to be known over the next two years as the Teapot Dome scandals. </p>
"1922/05/26","","Day",<p>Harding signs into law the creation of the Federal Narcotics Control Board. </p>
"1922/06/05","","Day",<p>In <i>United Mine Workers v. Coronado Coal Co.</i>, the Supreme Court rules, under the Sherman Act, that striking miners are liable for damage inflicted upon company property. The ruling is the first in a number of federal efforts to control organized labor that have become increasingly volatile during the postwar recession. The next month, another strike will break out after the Railroad Labor Board reduces wages. In September, the attorney general will win an injunction against the striking railroad workers as the two sides continue to battle. </p>
"1922/09/19","","Day",<p>Harding vetoes the Soldiers' Bonus Bill, arguing that balancing the budget takes precedence over the nation's debt to veterans of the Great War. The bill will later pass over the veto of then-president Calvin Coolidge. </p>
"1922/09/22","","Day",<p>The Cable Act, which allows an American woman to maintain her citizenship following marriage to an alien, is signed by Harding. </p>
"1922/10/03","","Day",<p>Filling a vacancy caused by death, Rebecca L. Felton becomes the first female senator following her appointment by the Governor of Georgia. The appointment is more symbolic than real as the term ends the following day. </p>
"1923/01/02","","Day",<p>As the Teapot Dome scandal begins to unfold, Harding accepts the resignation of Interior Secretary Fall. </p>
"1923/01/10","","Day",<p>The final American troops leave Germany as Harding issues an executive order halting U.S. occupation of the Rhine. </p>
"1923/01/29","","Day",<p>Charles Forbes, head of the Veterans' Bureau, resigns in anticipation of the Senate investigation of his department. He will later be indicted and convicted on charges of fraud, conspiracy, and bribery. The case will speed inquiries into Teapot Dome and set off a media frenzy against what is increasingly viewed as a corrupt presidency. Over the next few months, two different officials will commit suicide, further discrediting the administration. </p>
"1923/04/09","","Day",<p>The federal government's battle with organized labor continues as the Supreme Court rules in <i>Adkins v. Children's Hospital</i> that the minimum wage law for women and children adopted in Washington, D.C., is unconstitutional. </p>
"1923/05/04","","Day",<p>In what many regard as the beginning of the end for prohibition, New York State disregards Harding's warnings and repeals its enforcement act. </p>
"1923/06/20","","Day",<p>Harding and his wife leave for his "voyage of understanding," a transcontinental speaking tour across Alaska and the West designed to bolster faith in the Harding administration amid the various scandals emerging seemingly daily. </p>
"1923/08/02","","Day",<p>In late July, Harding, traveling from Alaska to San Francisco, suffers an attack of ptomaine poisoning and develops pneumonia. Although he initially appears to recover, Harding's health had been in decline for at least six months and the grueling schedule of his speaking tour appears to be too much for him. He dies with his wife by his side in a San Francisco hotel room on the evening of August 2. The scandals surrounding his presidency initially lead to rumors that foul play was involved in his death. While these claims will be disproved and Harding himself is never found to be directly involved in his administration's corruption, the scandals will nonetheless tarnish his presidential legacy. </p>
"1923/08/03","","Day",<p>In a simple 2:30 a.m. ceremony, presided over by his father at his home in Plymouth, Vermont, Calvin Coolidge is sworn in as the thirtieth President of the United States. </p>
