
<h2>3 5, 1877</h2>"","",<p>Republican Rutherford B. Hayes, previously a Union soldier, as well as a representative and governor of Ohio, is publicly sworn in as the nineteenth President of the United States. He takes the oath privately on March 3rd. In the race against Democrat Samuel Tilden, Hayes secures only 48 percent of the popular vote and 164 electoral votes to Tilden's 184. However, voter fraud and unclear results are reported in several states. A controversial decision of a special electoral commission ultimately proclaims Hayes President, with some Democrats referring to Hayes as "Rutherfraud." In return for the presidency, the Republicans make various concessions, including the removal of federal troops from the South. These actions are labeled the "Compromise of 1877"; African-Americans refer to it as "The Great Betrayal."</p>
<h2>3 20, 1877</h2>"","",<p>At a cabinet meeting, Hayes agrees to send a commission to Louisiana to report on the conditions in the southern state. In reality, he plans to use the action to sanction his decision to allow Democrat Francis T. Nicholls to take over the states by removing federal aid from federally appointed governor Stephen B. Packard. Meanwhile, Hayes's cabinet includes staunch liberal Republican William Evarts as secretary of state and a former Confederate as postmaster general; the nomination of the latter appeases Southern Democrats as part of the Compromise of 1877. </p>
<h2>4 10, 1877</h2>"","",<p>Troops depart the statehouse in South Carolina following a meeting at the White House with Daniel H. Chamberlain and Wade Hampton; without support, Chamberlain gives in, and Hampton becomes governor. </p>
<h2>4 24, 1877</h2>"","",<p>As in South Carolina, Hayes officially withdraws soldiers from Louisiana. Governor Packard has no choice but to submit, declaring, "One by one, the Republican state governments of the South have been forced to succumb to force, fraud or policy." Hayes's withdrawal of troops from the South marks the end of Reconstruction. At the same time, Hayes will also oversee the appropriation of federal funds for internal improvements in the South. </p>
<h2>6 1, 1877</h2>"","",<p>With Mexican-Texas border incursions continuing, Hayes sends troops to patrol the nearly lawless Mexican border and cross it if necessary to pursue bandits. Mexican president Diaz protests and sends troops to the border as well. Ultimately, economic concerns motivate both parties to work towards a settlement. </p>
<h2>6 22, 1877</h2>"","",<p>Following John Jay's investigation of the New York Customhouse, Hayes issues an Executive Order that forbids the involvement of federal employees in political activities. The President takes such action in the hope that it will curtail corruption; the Executive Order stipulates that those in office can no longer be dismissed for political reasons. Congress rejects additional proposals. These events testify to Hayes's interest in civil service reform. </p>
<h2>7 16, 1877</h2>"","",<p>Following pay cuts, the first major interstate strike -- the Great Railroad Strike of 1877 -- begins on the Baltimore and Ohio (B&O) line at Camden Junction, Maryland; additional strikes will follow, lasting a month. Lacking organization, the strikes frequently degenerate into mob activity. Hayes sends federal troops to protect mail and quell the riots that take place in numerous cities, angering many workers. The strike will lead to anti-Chinese attacks in San Francisco during the fall. </p>
<h2>9 6, 1877</h2>"","",<p>Hayes challenges the political power of New York Senator Roscoe Conkling when the President announces he will replace Collector of the Port of New York Chester A. Arthur, as well as naval officer Alonzo Cornell, during the reorganization of the New York Customhouse. Although Arthur has overseen improvement in the Customhouse, he also uses it to further Conkling's political interests. Incensed by Hayes's decision, Conkling, Hayes's opponent for the Republican presidential ticket in 1876, blocks Hayes's nomination of Theodore Roosevelt, Sr., for the position. </p>
<h2>9 , 1877</h2>"","",<p>Hayes goes on a tour of the South, pledging reconciliation and solidarity through a policy of pacification. </p>
<h2>1 1, 1878</h2>"","",<p>Founded in 1869 by Uriah S. Stephens, a tailor in Philadelphia, the Knights of Labor is established as a national organization. It is the first labor union to attempt to organize all workers and hopes to establish a worker-owned factory system. With rapid growth in the 1880s, the Knight membership peaks in 1886 and then goes into rapid decline. </p>
<h2>1 17, 1878</h2>"","",<p>A U.S.-Samoan treaty is signed in Washington which gives the United States the right to establish a naval and coaling station at the port of Pago Pago; it also pledges American assistance to Samoa if a third country interferes with Samoan chiefs. The Senate ratifies the treaty on January 30. </p>
<h2>2 28, 1878</h2>"","",<p>Hayes vetoes the Bland-Allison Act, advocated by farmers and debtors, but Congress passes the measure over his veto. The act calls for the resumption of silver coinage at a rate between $2 and $4 million per month. </p>
<h2>3 1, 1878</h2>"","",<p>Hayes vetoes a bill which bans incoming vessels from carrying more than fifteen Chinese passengers. Hayes then works to negotiate changes to the Burlingame Treaty with China in order to set limits on Chinese immigration. </p>
<h2>3 23, 1878</h2>"","",<p>America recognizes the Diaz regime in Mexico in an effort to avoid greater conflict. </p>
<h2>5 1878</h2>"","",<p>House Democrats begin an investigation of the controversial presidential election of 1876, much to the chagrin of Hayes, who fears that the investigation may be an attempt to replace him with Tilden. </p>
<h2>11 , 1878</h2>"","",<p>Following congressional midterm elections, the Democratic Party controls both houses of Congress for the first time since the Civil War. Consequently, Hayes will have little sway in Congress. </p>
<h2>1 1, 1879</h2>"","",<p>Hayes allows the resumption of gold payments for Civil War greenbacks, paper money not backed by specie, silver, or gold. This is a continuation of the Specie Act begun under President Grant. During the Hayes administration, as the government's gold supply grows and the issuance of silver coins increases, the economy begins to recover. By the spring of 1879, the government has retired all Civil War bonds. </p>
<h2>2 3, 1879</h2>"","",<p>After a political struggle between Hayes and Senator Conkling, the Senate approves Hayes's appointments for the New York Customhouse. Although these fail to end inefficiency in the civil service system, the country largely supports Hayes's commitment to reform. </p>
<h2>4 29, 1879</h2>"","",<p>Congress passes the Army Appropriations Bill. The law includes a "rider" which forbids the use of federal troops at polls, which many regard as an attempt to nullify black voting rights. Hayes vetoes the bill, but the House sustains the veto. Hayes again vetoes the rebuffed version, and many Republicans feel the veto secures the election of 1880. </p>
<h2>5 29, 1879</h2>"","",<p>Hayes vetoes a version of the appropriations bill for the third time; a later bill excludes "certain judicial expenses" forbidding the army to "police the polls"; Hayes will  agree to this language. </p>
<h2>6 , 1879</h2>"","",<p>The appropriations designated by Democrats exclude implementation of election law funds; Hayes vetoes the bill. </p>
<h2>3 8, 1880</h2>"","",<p>In a speech to Congress, Hayes continues to support a Central American canal to unite the Atlantic and Pacific oceans. Following the trip to America by French diplomat Ferdinand de Lesseps -- the builder of the Suez Canal in Egypt -- Hayes states that "the policy of this country is a canal under American control." A canal running through Panama will be completed in 1914. </p>
<h2>6 7, 1880</h2>"","",<p>The Republican National Convention meets in Chicago. Hayes had already pledged, in 1876, not to run for a second term; by the time the convention begins, the party has split into two factions: James G. Blaine's "Half-breeds" and Roscoe Conkling's "Stalwarts." The Stalwarts nominate Ulysses S. Grant against the nominations of Blaine and John Sherman. After 36 ballots, Blaine unexpectedly lends his support to James A. Garfield, the Speaker of the House, giving Garfield the presidential nomination. In order to maintain party unity, Chester A. Arthur, a Stalwart, is nominated for vice president. </p>
<h2>6 24, 1880</h2>"","",<p>The Democratic National Convention meets in Ohio and nominates Winfield S. Hancock, a Union commander, for President and William H. English for vice president. </p>
<h2>11 2, 1880</h2>"","",<p>James A. Garfield is elected President by a narrow popular margin (with only 48.5 percent) but with a comfortable majority of electoral votes, 214-155. </p>
<h2>11 17, 1880</h2>"","",<p>The United States and China sign a treaty which repeals a section of the 1868 Burlingame treaty. The move gives the United States the power to "regulate, limit or suspend" but not completely prohibit Chinese immigration. The treaty also includes a clause banning the opium trade. In return, the United States grants China trading privileges. </p>
<h2>3 4, 1881</h2>"","",<p>Republican James A. Garfield is sworn in as the twentieth President of the United States.</p>
