
<h2>3 4, 1929</h2>"","",<p>Herbert Hoover is inaugurated as the thirty-first President of the United States. </p>
<h2>3 5, 1929</h2>"","",<p>Hoover appoints Henry L. Stimson Secretary of State. </p>
<h2>3 28, 1929</h2>"","",<p>The State Department begins its effort to help Standard Oil of California (SOCAL) attain oil rights in Bahrain from the Gulf Oil Company. Since the 1880s, the Sheikhdom of Bahrain had been a British protectorate and by treaty was required to sell its oil to British companies. Through a Canadian subsidiary the two sides were able to agree to terms and by 1935, SOCAL would have 16 operating oil wells in Bahrain. </p>
<h2>4 15, 1929</h2>"","",<p>New York City police raid the Birth Control Clinical Research Center established by Margaret Sanger, arresting two doctors and three nurses, and confiscating numerous records. Physicians and private citizens are outraged by the incident and a month later the case will be thrown out of court as a violation of a physician's right to practice medicine. </p>
<h2>5 16, 1929</h2>"","",<p>The first annual Academy Awards are presented by the Academy
of Motion Picture Arts and Sciences. </p>
<h2>5 27, 1929</h2>"","",<p>The U.S. Supreme Court upholds the use of the pocket veto by the
President for the purpose of blocking legislation. </p>
<h2>6 15, 1929</h2>"","",<p>Hoover signs the Agricultural Marketing Act to revitalize the
increasingly poor market for farm products. It represents a marked reversal in federal policy; Coolidge had vetoed a number of similar bills designed to aid farmers during his presidency. The act creates the Federal Farm Board, designed to promote the sale of agricultural products through cooperatives and stabilization corporations. In addition, it provides for the purchase of surplus goods by the federal government to maintain price levels, and a $500,000,000 fund to aid the cooperatives. </p>
<h2>9 3, 1929</h2>"","",<p>The index of common stock prices reaches an average of 216, more than double what it had been three years earlier. The increase represented the largest bull market the country had ever seen. At the same time, national income statistics indicate that roughly 60 percent of Americans have annual incomes below the poverty line, estimated at $2000.  </p>
<h2>9 22, 1929</h2>"","",<p>The construction contract for the Empire State Building is awarded. It will be completed in 1931. </p>
<h2>10 24, 1929</h2>"","",<p> On "Black Thursday," the New York Stock Exchange (NYSE) experiences a collapse in stock prices as 13 million shares are sold. Even wealthy investors J. P. Morgan and John D. Rockefeller, in an effort to save the market by furiously buying stock, cannot check the fall. </p>
<h2>10 29, 1929</h2>"","",<p>On "Black Tuesday," a record 16.4 million shares of stock are traded on the NYSE as large blocks of equities are sold at extremely low prices. The trading continues the sharp downward trend of the previous week. It is an abrupt change from the over-speculation of the previous months. By December 1, NYSE stocks will have lost $26 billion in value. </p>
<h2>12 2, 1929</h2>"","",<p>Secretary of State Henry Stimson invokes the Kellogg-Briand Pact, ratified earlier that year, in an effort to prevent a Sino-Soviet war.  Five months earlier, Chinese Nationalist troops had seized the Chinese Eastern Railroad in Manchuria in an effort to end Soviet control of the railroad. While the Pact is ignored, neither country is prepared to fight a war and they reach a peaceful settlement three weeks later. </p>
<h2>1 , 1930</h2>"","",<p>The U.S. Census reports a population of nearly 123 million, illiteracy hitting a new low of 4.3 percent of the population--down 1.7 percent from 1920--with about one in five Americans owning an automobile. </p>
<h2>2 3, 1930</h2>"","",<p>Hoover names Charles Evans Hughes, former secretary of state
under Harding and Coolidge, chief justice of the Supreme Court.  Hughes replaces former President William Howard Taft. </p>
<h2>2 10, 1930</h2>"","",<p>A major bootlegging operation in Chicago is shut down with the
arrest of 158 people from 31 organizations. Together, these groups were estimated to have distributed more than seven million gallons of whiskey nationwide with an estimated worth of around $50 million. </p>
<h2>4 22, 1930</h2>"","",<p>The London Naval Treaty is signed by the United States, Britain, and Japan. France and Italy refuse to sign major provisions of the treaty, which remains in effect until 1937. </p>
<h2>6 17, 1930</h2>"","",<p>Against the urgings of many economists, Hoover signs the Smoot-Hawley Tariff Act, raising duties prohibitively high on many imports. Rather than solve the economic crash, the act causes other countries to follow America's lead by raising their tariffs. Such "economic nationalism" exacerbates both the international depression and nationalist tensions. </p>
<h2>7 3, 1930</h2>"","",<p>Hoover signs the Veterans Administration Act, establishing the Veterans Administration. The act consolidates all existing federal agencies handling benefits for former servicemen into a single department. </p>
<h2>9 , 1930</h2>"","",<p>A bank panic begins as 305 banks across the country close before the month is out. More than 500 will follow in October. </p>
<h2>9 17, 1930</h2>"","",<p>Construction of the Hoover Dam begins in Las Vegas, Nevada; the dam will be completed in 1936. </p>
<h2>11 14, 1930</h2>"","",<p>Japanese Premier, Yuko Hamaguchi, is assassinated by a military fanatic. Hamaguchi had supported the London Naval Treaty signed in April, and his death opens the government to the increasing influence of military groups. Eighteen months later, Hamaguchi's replacement, Ki Inukai, will also be assassinated, with these groups assuming full control of the government. </p>
<h2>11 27, 1930</h2>"","",<p>Frank B. Kellogg is awarded the Nobel Peace Prize for his work in drafting the 1928 Kellogg-Briand Peace Pact while secretary of state during the Coolidge administration. </p>
<h2>12 2, 1930</h2>"","",<p>Hoover asks Congress to fund for public works projects in order to stem the growing tide of unemployment. Congress complies weeks later, providing $116 million in jobs for the estimated 4.5 million unemployed. </p>
<h2>12 11, 1930</h2>"","",<p>The Bank of the United States in New York City, with 60 branches and 400,000 depositors, closes. It is merely the largest of the more than 1300 bank closings across the country as the economic depression worsens. </p>
<h2>1 7, 1931</h2>"","",<p>The President's Emergency Committee reports that the number of unemployed is nearly five million. </p>
<h2>2 27, 1931</h2>"","",<p>Over Hoover's veto, Congress passes the Bonus Loan Bill. The act allows veterans to obtain cash loans of up to 50 percent of their bonus certificates issued in 1924. </p>
<h2>3 3, 1931</h2>"","",<p>"The Star Spangled Banner" officially becomes the national anthem. </p>
<h2>3 25, 1931</h2>"","",<p>Nine black youths are arrested in Scottsboro, Alabama, and charged with raping a white woman. Although the group is initially found guilty on the basis of questionable evidence, the Supreme Court will overturn the conviction of the "Scottsboro Boys" in 1935. </p>
<h2>6 20, 1931</h2>"","",<p>In an effort to ease the worldwide depression, Hoover proposes a one-year moratorium on debt payments owed America in return for Europe returning the favor on U.S. debts. Passed by Congress in December, the policy does little to ameliorate the economic crisis. </p>
<h2>9 18, 1931</h2>"","",<p>The Japanese military stages an incident in the Manchurian town of Mukden, creating a pretext for the Japanese invasion of the region. The action is in direct violation of the Kellogg-Briand Pact signed in 1928. </p>
<h2>9 21, 1931</h2>"","",<p>Britain goes off the gold standard in an effort to solve the continuing economic crisis. Americans, fearing that the United States will soon do the same, begin to withdraw their money from banks and hoard gold. Over the next month, 827 more banks will close. </p>
<h2>10 17, 1931</h2>"","",<p>The notorious gangster Al Capone is convicted of income tax evasion and sentenced to 11 years in prison and a $50,000 fine. For most of the 1920s, Capone ruled the Chicago underworld, taking in $105 million in 1927 alone, primarily from the lucrative and illegal business of bootlegging. He would be released in 1939, mortally ill from syphilis. </p>
<h2>12 7, 1931</h2>"","",<p>In response to the Great Depression, hundreds of "hunger marchers" descend on the nation's capitol.  They are turned away at the White House, however, unsuccessful in their attempt to present a petition to Hoover asking for jobs. </p>
<h2>12 9, 1931</h2>"","",<p>After more than a decade of military dictatorship, Spain adopts a Republican constitution, abolishing its monarchy. King Alfonso XIII had used the military to remain in power, but the international depression produced mutinies within the army and he had been forced to flee the country that April. </p>
<h2>1 7, 1932</h2>"","",<p>Secretary of State Stimson delivers a diplomatic note to Japan, condemning its actions in Manchuria. The "Stimson Doctrine" indicates America's refusal to recognize territory seized by force of arms. </p>
<h2>1 22, 1932</h2>"","",<p>Hoover establishes the Reconstruction Finance Corporation, an agency designed to lend money to banks, insurance companies, and other institutions to stimulate the economy. It will have $2 billion at its disposal. </p>
<h2>3 1, 1932</h2>"","",<p>In one of the most publicized crimes of the century, the twenty-month-old son of Charles Lindbergh is kidnapped. After paying a $50,000 ransom, the boy is found dead on May 12. The public outcry against the crime will help to make kidnapping a federal crime punishable by death. </p>
<h2>5 20, 1932</h2>"","",<p>Amelia Earhart becomes the first woman to complete a solo flight across the Atlantic Ocean. </p>
<h2>5 29, 1932</h2>"","",<p>The first of nearly 20,000 veterans arrive in Washington, D.C., setting up camp in open or unused buildings near the capitol. They hope to pressure Congress into granting them the full value of their bonus certificates, which were not to mature until 1944. The "Bonus Army" fails in its objective, however, as they are eventually forced out of the city by U.S. Army troops in late July. </p>
<h2>7 2, 1932</h2>"","",<p>In his acceptance speech for the Democratic presidential nomination, Franklin Delano Roosevelt pledges "a new deal for the American people," marking his first public use of that term. </p>
<h2>11 8, 1932</h2>"","",<p>Franklin D. Roosevelt wins the presidential election over Hoover in dramatic fashion. Roosevelt wins 472 electoral votes (22.8 million popular) to Hoover's 59 (15.8 million popular). The election illustrates the widespread public opinion that Hoover is largely to blame for the continuing economic crisis. By the end of the year, 13 million Americans are unemployed, total wages are 60 percent less than they were in 1929, and business losses are estimated to be as much as $6 billion. </p>
