
<h2>3 4, 1829</h2>"",""<p>Military hero and self-made man Andrew Jackson is sworn in as the seventh President of the United States. In his inaugural speech, Jackson articulates the principle of federal office rotation, ushering in the "spoils system" for loyal supporters of presidential candidates. Additionally, Jackson declares that government officials should not be allowed to serve inefficiently for excessive and indeterminate amounts of time; although his words are cause for concern, Jackson will replace only 9 percent of appointed federal officials during his first year in office. Meanwhile, his address is vague on issues such as the Second Bank of the United States, internal improvements, and tariffs. </p>
<h2>4 13, 1830</h2>"",""<p>Following his anonymous printing of the <i>South Carolina Exposition and Protest</i> in 1828, Vice President John C. Calhoun suggests that his state of South Carolina annul the federally imposed protective cotton tariff. Jackson threatens to deploy federal troops to occupy the state in the event of nullification. On April 13, at the Jefferson Day Dinner in Washington, D.C., Jackson denounces Calhoun and his theory of nullification, declaring, "Our Union—it must be preserved!" Calhoun responds, "The Union, next to our liberty most dear!" The following month, Jackson will receive confirmation that in 1818, Calhoun supported a measure to discipline Jackson for his military involvement in Florida. This discovery generates terse correspondence between the two. </p> 
<h2>5 </h2>"",""<p>Congress passes the Indian Removal Act, sanctioning the forcible relocation of Creek, Chickasaw, Cherokee, Choctaw, and Seminole tribes to land allotments west of the Mississippi river. Ninety-four removal treaties follow the bill's enactment. From 1835 to 1838, Cherokee and Creek are forcibly removed from the Southeast onto reservations. Nearly one quarter die along what became known as the "Trail of Tears." </p>      
<h2>5 </h2>"",""<p>Jackson vetoes the Maysville Road bill, which would have sanctioned the federal government's purchase of stock for the creation of a road entirely within Kentucky, the home state of longtime foe Henry Clay. Jackson regards the project as a local matter and thinks its funding should come from local sources. Jackson is not entirely opposed to the federal financing of such projects, supporting the allocation of federal monies for the National Road. Nevertheless, his veto of the Maysville Road bill indicates a shift in how the federal government intends to pay for internal improvements. Meanwhile, opponents interpret the move as an abuse of power. </p>
<h2>4 , 1831</h2>"",""<p>Jackson reshuffles his cabinet following the divisive and ongoing "Peggy Eaton Affair." The woman's first husband supposedly committed suicide after discovering her dalliance with Tennessee senator John Eaton, whom Jackson later names secretary of war. Members of Jackson's inner circle and their wives feud over accusations about the woman's alleged behavior. Jackson supports the Eatons and is outraged by the charges. </p>
 
<h2>7 4, 1831</h2>"",""<p>The French government agrees to a treaty settling spoliation claims by the United States dating back to the Napoleonic Wars. France agrees to pay $5 million but initially declines to make the payment. When U.S. representatives warn the French of American naval superiority, monies flow from French to U.S. coffers, beginning in 1836. </p>
<h2>7 10, 1832</h2>"",""<p>Jackson vetoes a bill that would have extended the life of the Second Bank of the United States. Henry Clay, running against Jackson in the presidential election, proposes the bill to bring the issue of the Bank to the forefront in the election. Jackson's opposition to the Bank actually garners him additional popular support. </p>
<h2>11 , 1832</h2>"",""<p>Running on the Democratic ticket, Jackson wins reelection to the presidency, soundly defeating Henry Clay and William Wirt. Jackson scores an impressive victory, amassing 219 electoral votes to Clay's 49. The election marks the entrance of third parties onto the national scene, with Wirt running on the Anti-Masonic ticket. It also features the use of national nominating committees. </p>
<h2>11 24, 1832</h2>"",""<p>A South Carolina state convention adopts the Ordinance of Nullification, an decree nullifying congressional acts involving duties and imposts on the importation of foreign commodities. Calhoun resigns as vice president and immediately takes his elected position as senator. No other states join South Carolina in this action. </p>
<h2>12 10, 1832</h2>"",""<p>Jackson issues the Nullification Proclamation, reaffirming his belief that  states and municipalities are forbidden from nullifying federal laws. </p> 
<h2>3 1, 1833</h2>"",""<p>Pressed by Jackson, Congress passes the Force Bill, authorizing Jackson's use of the army to gain compliance for federal law in South Carolina. Vice President Calhoun voices his dissent. </p>
<h2>3 20, 1833</h2>"",""<p>Jackson commissions Edmund Roberts as a "special agent" of the United States to negotiate commercial trade treaties abroad. Roberts's efforts result in the first treaties between the United States and a number of far eastern governments, including Siam (now Thailand). </p>
<h2>3 28, 1834</h2>"",""<p>Viewing his reelection as a mandate to continue his war against the Second Bank of the United States, Jackson issues an order for the Treasury Department to withdrawal federal deposits from the Bank of the United States and place them in state banks. When Secretary of the Treasury William Duane refuses, Jackson fires him. On March 28, the Senate, led by Clay, Calhoun and Daniel Webster, passes a resolution of censure admonishing Jackson. The censure will be officially expunged from the record on January 16, 1837, the result of political bargaining. Jackson will continue to take action against the Bank, which closes its doors in 1841. </p>
<h2>12 , 1834</h2>"",""<p>Jackson announces he will terminate the national debt, freeing the United States of foreign and domestic obligations beyond the reserves of the Treasury. </p>  
<h2>3 2, 1836</h2>"",""<p>In Washington, D.C., the delegates of the people of Texas officially and unanimously declare their independence. </p> 
<h2>7 11, 1836</h2>"",""<p>Jackson, along with Treasury Secretary Levi Woodbury, introduces the Specie Circular, revealing that the government will accept only gold and silver for land payments. The act serves as an attempt to check rising inflation precipitated by unprecedented land speculation and irresponsible lending. </p>
  <p>Hand-picked by Jackson to be his successor, Vice President Martin Van Buren wins the presidential election, running against three Whigs. The Whig Party hoped to split the popular vote so that the House of Representatives would decide the election's outcome. Van Buren, however, emerged with more votes than his opponents combined. </p>
 
<h2>3 , 1837</h2>"",""<p>Jackson recognizes the independence of Texas but declines to address annexation in light of threats by Mexico and its concerns about security. </p>
<h2>3 4, 1837</h2>"",""<p>Martin Van Buren is sworn in as the eighth President of the United States. His inaugural address serves largely as a commemoration of his predecessor, President Andrew Jackson.</p>
