
<h2>1865/4/15</h2>"","",<p>Vice President Andrew Johnson takes the presidential oath of office in his hotel room at the Kirkwood House following the assassination of President Abraham Lincoln. Chief Justice Salmon P. Chase oversees the proceeding. Lincoln chose Johnson, a racist and uneducated Southerner from Tennessee, as his vice president to balance the 1864 ticket.</p>
<h2>1865/4/18</h2>"","",<p>Johnson declares that the terms agreed on between Union General William Tecumseh Sherman and Confederate General Joseph E. Johnston are too lenient to the Confederates and orders that they be set aside. Johnston surrenders to Sherman on April 26 on harsher terms. </p>
<h2>1865/4/21</h2>"","",<p>Lincoln's funeral train departs from Washington, D.C., on its journey to Springfield, Illinois. </p>
<h2>1895/5/29</h2>"","",<p>Johnson issues two proclamations summarizing his recommendations for the restoration of Confederate states to the Union. First, he grants amnesty to all white southerners who take a loyalty oath; by doing so, the southerners will regain their property. (High Confederate officials and southern planters owning property worth more than $20,000 are excluded from this option.) Second, Johnson outlines a reconstruction plan for North Carolina which becomes the blueprint for other Southern states. Johnson proposes to appoint provisional governors to the defeated states; under their direction, new constitutions would be drafted abolishing slavery and renouncing secession. Following the authorization of these new laws, the states would be accepted back into the Union. </p>
<h2>1865/5/2</h2>"","",<p>Johnson issues a proclamation offering rewards for the arrests of Jefferson Davis, Jacob Thompson, and Clement C. Clay, Jr. </p>
<h2>1865/5/23</h2>"1865/5/24","",<p>The close of the Civil War is celebrated in Washington, D.C.  Johnson presides over a series of reviews of the Army of the Potomac and the Army of Tennessee. </p>
<h2>1865/6/9</h2>"","",<p>Johnson officially takes residence in the White House. </p>
<h2>1865/6/13</h2>"","",<p>Johnson appoints William L. Sharkey as the provisional governor of Mississippi. Over the next few weeks, Johnson appoints provisional governors for Georgia, Texas, Alabama, South Carolina, and Florida, and assigns to each the task of overseeing his reconstruction plans in the South. </p>
<h2>1865/12/2</h2>"","",<p>Mississippi enacts a Black Code, which restricts the newly won rights of African Americans and attempts to keep the freedmen in a separate and inferior position. Throughout December and into 1866, other ex-Confederate states follow suit, enacting their own black codes. The codes of Mississippi and South Carolina prove most stringent. </p>
<h2>1865/12/4</h2>"","",<p>Johnson addresses the Thirty-Ninth Congress for the first time with his annual message; Congress had been in recess for the duration of Johnson's presidency. The Republican majority remains suspicious of Johnson and his policies. </p>
<h2>1865/12/12</h2>"","",<p>Johnson orders provisional Governor Sharkey to turn over governorship of Mississippi to his elected successor. Over the next five weeks, Johnson issues similar orders to the provisional governors of Alabama, Georgia, South Carolina, and Florida.  These newly elected governments are populated with numerous ex-Confederate officials. </p>
<h2>1866/2/19</h2>"","",<p>Johnson vetoes a bill calling for the extension of the Freedmen's Bureau. The bill, a response to the repressive black codes of the South, would expand the power of the Bureau, the organization formed for the freedmen's protection. </p>
<h2>1866/2/22</h2>"","",<p>Following Congress's attempt to expand the Freedmen's Bureau, Johnson denounces the so-called "Radical Republicans," specifically Representative Thaddeus Stevens, Senator Charles Sumner, and reformer Wendell Phillips, as traitors. The Radicals, a minority within the party, believe that few white southerners are truly unionist. They will work assiduously, hoping to improve the lot the freedmen and trying to bar former Confederate leaders from politics. </p>
<h2>1866/3/27</h2>"","",<p>Johnson vetoes the Civil Rights Act, a second attempt by Congress to provide freedmen with federal citizenship after the failed Freedmen's Bureau bill. The act sanctions the employment of federal troops for enforcement. The Senate overrides Johnson's veto on April 6. Three days later, the House of Representatives also overrides the veto. </p>
<h2>1866/6/1</h2>"1866/6/3","",<p>The Fenian Raid and the Battle of Ridgeway in Canada takes place between Canadian militiamen and members of the Fenian Brotherhood, an Irish-American organization lobbying for a free Ireland. The Brotherhood, founded in New York in 1858, hopes to capture Canada and use it as a bargaining tool against Britain; their attempt fails. Many of the Fenian participants are Civil War veterans. </p>
<h2>1866/6/19</h2>"","",<p>Unhappy with what it views as Johnson's lenient approach to the South, Congress passes and sends the Fourteenth Amendment to the Constitution to the states for ratification. Not only does the amendment seek to prevent ex-Confederates from holding office, it also establishes the citizenship of African Americans, affirming that "all persons born or naturalized in the United States, and subject to the jurisdiction thereof, are citizens of the United States and of the State wherein they reside." The amendment, when passed, will overturn the <i>Dred Scott</i> decision of 1857. </p>
<h2>1866/7/1</h2>"","Month",<p>William Dennison, James Speed, and James Harlan, all possessing ties to the "Radical Republicans," resign from the cabinet. President Johnson replaces them with Republicans who support his policies. </p>
<h2>1866/7/16</h2>"","",<p>Congress overrides Johnson's veto of the Freedmen's Bureau Renewal Act. </p>
<h2>1866/7/24</h2>"","",<p>Congress readmits Tennessee to the Union after the state ratifies the Fourteenth Amendment. </p>
<h2>1866/8/28</h2>"","",<p>Johnson begins his "swing around the circle" speaking tour of the eastern and midwestern United States. Hoping to gather popular support, he campaigns against several "Radical Republicans" running in the fall congressional elections. He returns to Washington, D.C., on September 15. </p>
<h2>1866/11/1</h2>"","Month",<p>Johnson suffers losses in congressional elections as Radical Republicans score major victories. Northerners are not convinced by the President's assertions that white Southerners are fully remorseful over the Civil War and have become unionist.  (During the summer, white rioters in both Memphis and New Orleans attack residents in predominantly black sections of the cities, further heightening Northern concern). Following the election, Republicans enjoy a more-than two-thirds majority in both houses of Congress. </p>
<h2>1867/3/1</h2>"","",<p>Nebraska joins the Union. </p>
<h2>1867/3/2</h2>"","",<p>With the mandate of the 1866 election, Congress (despite Johnson's veto) passes the First Reconstruction Act, setting up five military districts in the South, each under the direction of a presidentially-appointed military commander. The legislative body also passed the Army Appropriations Act, which lessens Johnson's control of the Army. Finally, Congress passes -- again over Johnson's veto -- the Tenure of Office Act, prohibiting Johnson from removing cabinet officers without the Senate's consent. In this final piece of legislation, Congress hopes to protect Secretary of War Edwin Stanton, the sole Radical Republican in Johnson's cabinet. </p>
<h2>1867/3/23</h2>"","",<p>Johnson vetoes the Second Reconstruction Act, which orders military commanders to call elections in the South. Congress overrides Johnson's veto that very day. </p>
<h2>1867/3/30</h2>"","",<p>Secretary of State William H. Seward, appointed by Lincoln, agrees to a treaty with Russia allowing the United States to purchase Alaska for $7.2 million. The land purchased is referred to as "Seward's icebox." </p>
<h2>1867/7/19</h2>"","",<p>Johnson vetoes the Third Reconstruction Act, which spells out election procedures in the South and reasserts congressional control over Reconstruction. Congress again overrides Johnson's veto on the same day the President delivers it. </p>
<h2>1867/8/5</h2>"","",<p>Johnson asks Secretary of War (and Radical Republican) Edwin Stanton to resign. The two disagree over Reconstruction plans; Stanton refuses. </p>
<h2>1867/8/12</h2>"","",<p>Johnson suspends Secretary Stanton from his position and commissions Ulysses S. Grant as ad interim secretary of war. </p>
<h2>1867/8/28</h2>"","",<p>The United States takes possession of the Midway Islands in the Pacific Ocean. </p>
<h2>1867/12/3</h2>"","",<p>In his annual message to Congress, Johnson defends his policies toward the ex-Confederate states. </p>
<h2>1867/12/12</h2>"","",<p>Johnson submits his reasons for suspending Secretary Stanton to the Senate. </p>
<h2>1868/1/13</h2>"","",<p>The Senate refuses to concur with Johnson's removal of Stanton. </p>
<h2>1868/1/14</h2>"","",<p>Ad Interim Secretary of War Grant informs Johnson that he will vacate his post and return it to Stanton. </p>
<h2>1868/2/21</h2>"","",<p>Johnson formally removes Stanton and gives control of the War Department to General Lorenzo Thomas. Stanton, however, refuses to adhere to Johnson's decision and barricades himself in his cabinet office for roughly two months.  Johnson's actions violate the Tenure of Office Act and begin the impeachment crisis. </p>
<h2>1868/2/24</h2>"","",<p>The House of Representatives votes to impeach Johnson, focusing on his breach of the Tenure of Office Act. The 126-47 vote is along party lines. </p>
<h2>1868/3/4</h2>"","",<p>The House appoints seven managers to go before the Senate with eleven articles of impeachment. Eight of these articles relate to the Tenure of Office Act and the removal of Secretary of War Stanton. </p>
<h2>1868/3/5</h2>"","",<p>The Senate begins its impeachment trial. Chief Justice Salmon P. Chase presides. </p>
<h2>1868/5/16</h2>"","",<p>The Senate votes 35-19 to convict President Johnson, falling one vote short of the necessary two-third majority. Seven moderate Republicans vote against impeachment. The vote serves as a precedent for standard necessary to convict in impeachment hearings. </p>
<h2>1868/5/20</h2>"1868/5/21","",<p>The Republican National Convention meets in Chicago. After declaring Johnson guilty, it nominates national hero General Ulysses S. Grant for President and Schuyler Colfax for vice president. Grant has no political experience. </p>
<h2>1868/5/26</h2>"","",<p>The Senate votes to acquit President Johnson on impeachment charges two and three. The Senate then adjourns and fails to vote on the remaining eight articles of impeachment. </p>
<h2>1868/6/1</h2>"","Month",<p>President Johnson vetoes bills that would have readmitted several ex-Confederate states to the Union. Congress overrides these vetoes. </p>
<h2>1868/7/9</h2>"","",<p>Johnson submits the Burlingame Treaty between the United States and China to the Senate for approval. </p>
<h2>1868/11/1</h2>"","Month",<p>Republican Presidential candidate General Ulysses S. Grant defeats Democrat Horatio Seymour by only 300,000 votes. With 450,000 black Republican votes, the party becomes convinced that black suffrage is politically necessary. </p>
<h2>1868/12/8</h2>"","",<p>President Johnson delivers his final annual message to Congress, again requesting the repeal of the Reconstruction Acts. </p>
<h2>1869/3/4</h2>"","",<p>Ulysses S. Grant takes the oath of office as President of the United States.  President Johnson refuses to attend the inauguration. </p>
