
 
<h2>2 9, 1825</h2>"","",<p>The House of Representatives elects John Quincy Adams President of the United States. The election of 1824 produces an outcome in which none of the four candidates achieve a majority of electoral endorsements. Andrew Jackson receives 99, John Quincy Adams 84, William Crawford 41, and Henry Clay 37. Because no one obtains the required constitutional majority, the election is remanded to the House of Representatives. In what Jackson proponents denounce as the "corrupt bargain," Speaker Henry Clay resolves to throw his votes behind Adams, presumably, to secure the helm of the State Department. As President, Adams nominates Clay to be secretary of state. Jackson is furious, abdicates his Senate seat, and vows to run again in 1828.</p>
<h2>3 4, 1825</h2>"","",<p>John Quincy Adams, the sixth President of the United States and son of John Adams, the second President, makes his inaugural address. An intellectual, Adams will fail to assemble public support during his one term in office, often denounced as an aristocrat. In this address, Adams sets forth his policies bluntly, alienating many in Congress. A central feature of the Adams administration will be the opening and expansion of trade relationships with South America and the Caribbean colonies, which are formalized between the United States and several European powers in the General Reciprocity Act of 1824. </p>
<h2>7 7, 1825</h2>"","",<p>Captain David Porter, a perennial thorn in the side of the United States Navy, is court-martialed for overstepping his powers when he chooses to land 200 troops at Fajardo, Puerto Rico, in November 1824. Porter demands an apology from the port's captain for the detention of two errant U.S. officers. Despite the court martial, the American public proves largely sympathetic to Porter's insubordination. The court martial fails to reach a decision. </p>
<h2>10 , 1825</h2>"","",<p>The Tennessee legislature nominates Andrew Jackson their presidential challenger for the 1828 election. </p>
<h2>10 26, 1825</h2>"","",<p>The first passage on the 363 mile-long Erie Canal is completed from Lake Erie to New York City, linking the Atlantic and trans-Atlantic marketplaces with growing agricultural production in the Northwest states. Construction of the canal began in 1817. During his presidential term, Adams strongly supports national planning of and the use of national funds for an improved transportation infrastructure. </p>
<h2>5, 1826</h2>"","",<p>Military standardization and integration of Union and state militias is a foremost concern during the Adams administration. In response to a proposal by the secretary of war to revamp military organization and seniority systems, a joint House and Senate resolution calls for the production and dispersal of training manuals. </p>
<h2>7 4, 1826</h2>"","",<p>Thomas Jefferson and John Adams, founding fathers and former Presidents, both die. </p>
<h2>11 , 1826</h2>"","",<p>Under the mediation of Czar Nicholas I, President Adams finalizes a settlement with the British over restitution for damages incurred during the War of 1812, left unresolved by the Treaty of Ghent. </p>
<h2>3 , 1827</h2>"","",<p>Adams proclaims all American ports closed to trade with British colonies, suspending disagreements from an era of protracted contention with the British over tariffs, navigation and duties. Adams's declaration embodies his response to a rising Continental cartel of exclusive trading relationships. </p>
<h2>12 , 1827</h2>"","",<p>Additional European states are incorporated into the MFN trade system, the pre-conditions of commercial growth being ëneutral rights,' which began in April 1826. </p>
<h2>1 , 1828</h2>"","",<p>Nicholas Biddle of the Bank of the United States implements the sale of government securities to curtail the outward flow of specie. This policy results in propositions by Congress for the public sale of United States Bank stock. </p>
<h2>1 , 1828</h2>"","",<p>Joel Poinsett accedes to a Mexican boundary settlement on behalf of the United States. This concludes a slew of unsuccessful efforts by Adams to negotiate more favorable borders than the existing Sabine River. </p>
<h2>2 , 1828</h2>"","",<p>Antonio José Caóaz, Guatemalan minister to the United States, proposes the construction of a canal adjoining the Pacific and Atlantic through Nicaragua. The United States is receptive, spearheading a flurry of American and international bids for surveying, building, and operation contracts. Although local instability derails the experiment, the effort is an important demonstration of the supremacy of the United States's influence in Central America. </p>
<h2>5 11, 1828</h2>"","",<p>Proposed by South Carolinian and Vice President John Calhoun in an attempt to bolster support for Andrew Jackson's bid for President, Congress passes a new tariff bill. The plan calls for incredibly high tariffs on raw materials to accommodate Western interests and on British woolens to appease New England interests. Calhoun believed Jackson supporters in the Northeast would back the bill while Jackson men in the South and Southwest, generally opposed to protectionism, would oppose it; he expects the bill to fail. The Tariff angers many, including the Virginia state legislature, which terms the law the "Tariff of Abominations." The bill's passage effectively ends Adams's hopes for reelection and increases support for Jackson who appears as a free-trade advocate to the South and a protectionist to the North. Calhoun, meanwhile, anonymously pens the <i>South Carolina Exposition and Protest</i>, which advocates a state's right to nullify federal laws which it opposes and deems unconstitutional. </p>
<h2>11 , 1828</h2>"","",<p>Andrew Jackson, running on the Democratic ticket, ends Adams's bid for reelection. The Tennessee native wins the election with 56 percent of the popular vote and 178 electoral votes to Adams's 83. </p>
<h2>3 4, 1829</h2>"","",<p> Andrew Jackson is sworn in as the seventh President of the United States.  </p>
