
"1963/11/22","","Day","Lyndon Baines Johnson is sworn in as the thirty-sixth President of the United States following the assassination of John F. Kennedy."
"1963/11/27","","Day","Johnson addresses a joint session of Congress calling on legislators to fulfill Kennedy's legacy and pass civil rights and tax legislation. "
"1963/11/29","","Day","Johnson creates a special commission chaired by Chief Justice Earl Warren to investigate the Kennedy assassination. "
"1964/01/23","","Day","The Twenty-Fourth Amendment to the Constitution is ratified, abolishing poll taxes. "
"1964/02/07","","Day","The Beatles arrive in New York for their first U.S. tour. "
"1964/03/14","","Day","Jack Ruby is convicted of the murder of Lee Harvey Oswald and sentenced to death. "
"1964/05/22","","Day","In a speech at the University of Michigan, Johnson announces his intention to create a Great Society by extending American prosperity to all its citizens. "
"1964/07/02","","Day","Johnson signs The Civil Rights Act of 1964. "
"1964/07/15","","Day","Sen. Barry Goldwater (R-AZ) receives the Republican nomination for President. "
"1964/07/19","","Day","Governor George Wallace of Alabama drops out of the presidential race despite strong showings in several Democratic primaries. "
"1964/08/04","","Day","Three civil rights workers are found dead in Mississippi. James Chaney, Andrew Goodman, and Michael Schwerner were all participating in the Mississippi Freedom Summer. "
"1964/08/07","","Day","Congress passes the Gulf of Tonkin Resolution giving the President power to pursue military action in Vietnam. "
"1964/08/26","","Day","Johnson receives the Democratic nomination for President. Senator Hubert H. Humphrey (D-MN) is nominated as the vice-presidential candidate. "
"1964/08/30","","Day","Johnson signs the Economic Opportunity Act, creating the Office of Economic Opportunity and beginning the War on Poverty. "
"1964/09/27","","Day","The Warren Commission releases its report, rejecting the notion that Kennedy was assassinated as part of a conspiracy. "
"1964/10/14","","Day","Martin Luther King Jr. is awarded the Nobel Peace Prize. "
"1964/10/15","","Day","Nikita Khrushchev is forced to resign as leader of the Soviet Union and is replaced by Leonid Brezhnev. "
"1964/11/03","","Day","Lyndon B. Johnson is elected President of the United States. "
"1965/01/20","","Day","Johnson is inaugurated President of the United States. "
"1965/02/09","","Day","Nine American soldiers are killed in an attack on U.S. barracks in Pleiku, Vietnam. Johnson begins the bombing of North Vietnam. "
"1965/02/21","","Day","Malcolm X is assassinated by other black Muslims in New York City. "
"1965/03/15","","Day","Johnson calls for voting rights legislation. "
"1965/03/21","","Day","Martin Luther King Jr. leads a march from Selma to Montgomery, Alabama. "
"1965/04/11","","Day","Johnson signs the Elementary and Secondary Education Act. "
"1965/04/28","","Day","Johnson sends U.S. marines to the Dominican Republic to protect U.S. citizens after a military coup. "
"1965/06/07","","Day","The U.S. Supreme Court finds a Connecticut law banning the use of contraceptives unconstitutional. "
"1965/07/26","","Day","Martin Luther King Jr. leads a demonstration in Chicago in an attempt to bring the Civil Rights Movement to the North. "
"1965/07/28","","Day","Johnson increases the number of troops sent to Vietnam, indicating his determination to engage in a ground war. "
"1965/07/30","","Day","Johnson signs legislation creating Medicare and Medicaid. "
"1965/08/01","","Month","A paper by Daniel Patrick Moynihan, entitled, <i>The Negro Family: The Case For National Action</i>, is released. The conclusions of the "Moynihan Report" create heated controversy. "
"1965/08/05","","Day","Johnson signs the Voting Rights Act into law. "
"1965/08/11","1965/08/16","Day","The Watts Riots break out in Los Angeles. "
"1966/02/21","","Day","Fearing that American involvement in Vietnam will draw France into a world war, French president Charles de Gaulle announces that France will withdraw from NATO. "
"1966/03/07","","Day","The U.S. Supreme Court unanimously upholds the Voting Rights Act of 1965. "
"1966/06/01","1966/06/02","Day","The White House Conference on Civil Rights urges Congress to pass further civil rights legislation. "
"1966/06/06","","Day","James Meredith is shot in a March from Memphis, Tennessee, to Jackson, Mississippi; civil rights leaders organize to complete his march. During this demonstration, Stokely Carmichael makes a statement in support of "black power." "
"1966/06/13","","Day","In <i>Miranda v. Arizona</i>, the U.S. Supreme Court rules that the constitutional provision against self-incrimination applies to police interrogations. "
"1966/10/01","","Month","Huey P. Newton and Bobby Seale found the Black Panther Party in Oakland, California. "
"1967/01/27","","Day","A launch pad fire during tests for the Apollo program kills three astronauts. "
"1967/02/10","","Day","The Twenty-Fifth Amendment to the Constitution is ratified, providing rules of succession upon the death or incapacitation of the President, and enabling the President to appoint a new vice-president in the case of a vacancy. "
"1967/06/05","","Day","The Six Day War breaks out between Israel and several Arab nations. "
"1967/06/14","","Day","Johnson appoints Thurgood Marshall to the Supreme Court. "
"1967/07/13","","Day","Riots break out in Newark, New Jersey."
"1967/07/23","","Day","Riots spread across the city of Detroit, Michigan. "
"1967/10/21","","Day","Anti-war demonstrators March to the Pentagon in an attempt to shut it down. "
"1968/01/22","","Day","North Korean forces capture the <i>U.S.S. Pueblo</i>. "
"1968/01/30","","Day","North Vietnamese troops surprise South Vietnamese and American troops by attacking during the Tet holiday. While the Tet Offensive is not a military loss for the United States, it leads to a loss of confidence in the Johnson administration's prosecution of the war. "
"1968/02/08","","Day","George Wallace enters the presidential race as an independent. "
"1968/03/12","","Day","Johnson wins the New Hampshire Democratic primary, but anti-war candidate Eugene McCarthy comes in a close second with 42 percent of the vote. "
"1968/03/16","","Day","U.S. forces in Vietnam commit massacre in the hamlet of My Lai; hundreds of unarmed men, women, and children are killed. News of the event would not reach the public until November 1969. "
"1968/03/16","","Day","Robert Kennedy enters the race for the Democratic nomination for President. "
"1968/03/31","","Day","Johnson announces a partial bombing halt and his unwillingness to seek reelection to the presidency. "
"1968/04/04","","Day","Martin Luther King Jr. is assassinated in Memphis, Tennessee. "
"1968/04/23","","Day","Students at Columbia University take over several buildings on campus. "
"1968/04/29","","Day","Ralph Abernathy of the Southern Christian Leadership Conference (SCLC) begins the Poor People's Campaign in Washington, D.C."
"1968/05/13","","Day","The United States and North Vietnam begin peace talks in Paris. "
"1968/06/05","","Day","Senator Robert Kennedy is assassinated after winning the Democratic primary in California. "
"1968/08/20","1968/08/21","Day","The Soviet Union invades Czechoslovakia to end the movement toward greater freedom and independence. "
"1968/08/25","1968/08/29","Day","Hubert H. Humphrey is nominated in Chicago as the Democratic candidate for President.  Demonstrators and police clash in violent confrontations. "
"1968/11/05","","Day","Richard M. Nixon is elected President of the United States, and Spiro Agnew is elected vice-president. "
"1968/11/12","","Day","Leonid Brezhnev announces that the Soviet Union has the right to intervene anywhere in its sphere of influence. This "Brezhnev Doctrine" becomes central to Soviet foreign policy. "
