
"1861/02/07","","Day",<p>The Confederate States of America is organized by the lower Southern states stretching from South Carolina to Texas. Jefferson Davis is elected president. Davis, a native Mississippian, had served in the Senate as a leading Southern advocate and was Secretary of War for President Franklin Pierce. Over the course of the Civil War, Davis will face the conflict between the confederate ideology of states' rights and the need for a strong, central government to lead the war against President Abraham Lincoln and the Union.</p>
"1861/03/04","","Day",<p>Abraham Lincoln is inaugurated as the sixteenth President of the United States, and the nation's first Republican President. Many Southerners view his victory, determined by the free states, as the final blow in decades of sectional conflict. Between the time of Lincoln's election and his inauguration, seven states from the lower South secede. In his inauguration speech, Lincoln attempts to pacify the South by stating that he will not interfere with slavery where it exists but that the secession of states from the Union is illegal. He warns that he will respond to violence with force. </p>
"1861/03/11","","Day",<p>The Confederate Congress unanimously adopts the Confederate Constitution, which declares the sovereignty of states and forbids the passage of any bill which outlaws slavery. </p>
"1861/04/12","","Day",<p>Responding to Lincoln's attempt to resupply Fort Sumter (one of the last remaining federal stations in the South), South Carolina's Confederate batteries, under the command of General P.G.T. Beauregard open fire on the federal arsenal, in the Charleston harbor, at 4:30 a.m. Confederate President Jefferson Davis issues the order to Beauregard. </p>
"1861/04/13","","Day",<p>Out of supplies and after thirty-three hours under attack, Major Robert Anderson of Fort Sumter surrenders. The federal outpost is evacuated the next day. </p>
"1861/04/15","","Day",<p>Following the incident at Fort Sumter, Lincoln calls for 75,000 militiamen (volunteer troops) to put down the rebellion. He declares that an "insurrection" exists, marking the official beginning of the Civil War. In four and a half years, nearly 5 million American men will serve as soldiers with more than 600,000 of them falling as casualties, making the Civil War the bloodiest war in American history. </p>
"1861/04/17","","Day",<p>In response to Lincoln's decision to use force in South Carolina, Virginia secedes from the nation, followed by three other upper Southern states: North Carolina, Tennessee, and Arkansas. Four border slave states remain in the Union. </p>
"1861/04/19","","Day",<p>With only 42 ships and 3550 miles of Confederate coastline to patrol, Lincoln orders a blockade of Confederate ports that will eventually weaken the Confederacy by disrupting the importation of supplies. Meanwhile, the first casualties of the Civil War occur in Baltimore, Maryland. </p>
"1861/05/06","","Day",<p>Arkansas secedes from the Union. </p>
"1861/05/10","","Day",<p>Searching for a way to finance the war, the House of Representatives passes the Morrill Tariff and excise taxes (sponsored by Senator Morrill of Vermont). The law signals a new impulse toward protectionism and the increasing centralization of the federal government. Congress becomes the regulator of imports, doubling duties and levying taxes on goods associated with manufacturers and most other professions. </p>
"1861/05/20","","Day",<p>North Carolina secedes from the Union. </p>
"1861/05/21","","Day",<p>Following Virginia's secession, the capital of the confederacy moves from Montgomery, Alabama, to Richmond, Virginia. Virginia is most populous of the Southern states. </p>
"1861/06/08","","Day",<p>Tennessee secedes from the Union. </p>
"1861/07/21","","Day",<p>The Battle of Bull Run takes place near Manassas, Virginia. Confederate General Beauregard defeats the Union forces under General Irvin McDowell. Confederate General Thomas J. Jackson is nicknamed "Stonewall" for his firm stand at a crucial moment in the battle. The fighting inspires the Confederacy to create a new battle flag after confusion occurs between the Confederacy's "stars and bars" and the Union flag. </p>
"1861/07/25","","Day",<p>The Union endorses the use of volunteers for the war and offers a $100 bonus for at least two years of service. </p>
"1861/09/14","","Day",<p>The Civil War's first naval engagement occurs at Pensacola, Florida, between the <i>USS Colorado</i> and the steamer <i>Judah</i>. Navy Lt. John H. Russell and his crew arrive at the Navy yard at 2 a.m. and set fire to the <i>Judah</i>. The Union suffers three deaths and four wounded, while the Confederates suffer no casualties. </p>
"1861/10/31","","Day",<p>General Winfield Scott retires as commander in chief of the Union army at age 75. </p>
"1861/11/01","","Day",<p>Following General Scott's retirement, President Lincoln names George McClellan, a West Point graduate, as new commander of the Union army. McClellan proves to be an extremely cautious general. His inability to win decisive battles will frustrate Lincoln, who will eventually replace him. </p>
"1862/02/20","","Day",<p>William Wallace (Willie) Lincoln dies from typhoid fever. He is the second son the Lincolns have lost. </p>
"1862/03/09","","Day",<p>The first duel between two ironclad warships occurs. With trade suffering from the federal blockade, the Confederacy converts the wooden <i>Merrimack</i> into an ironclad gunship, now called the <i>Virginia</i>. The Union <i>Monitor</i> battles the <i>Virginia</i> to a standoff. In May, the Union forces the Confederacy to abandon Norfolk, definitively establishing the Union's naval superiority. </p>
"1862/04/16","","Day",<p>Slavery is abolished in District of Columbia. </p>
"1862/06/01","","Day",<p>General Robert E. Lee is appointed commander of the Confederate Army of Northern Virginia after his predecessor is wounded. </p>
"1862/07/01","","Month",<p>Major General David Hunter of the Union organizes the first black troops, among whom number many former slaves. By war's end, nearly 200,000 African Americans will have served in the Union forces, comprising roughly ten percent of the Union's total manpower. Initially, the Confederacy threatens to execute every captured black soldier; Lincoln responds by promising to execute one Confederate soldier for each black killed. </p>
"1862/07/22","","Day",<p>Lincoln announces to his cabinet his intention to issue the Emancipation Proclamation. By this point, he believes the border states will remain in the Union. Lincoln decides to wait to address the nation publicly, however, hoping to introduce his proclamation after a more favorable military battle. </p>
"1862/08/29","1862/08/30","Day",<p>The Second Battle of Bull Run takes place. Generals Stonewall Jackson and Lee prove too much for the Union troops under General John Pope, who retreat to Washington, D.C. The battle leads to huge Union losses. </p>
"1862/09/17","","Day",<p>The Battle of Antietam Creek near Sharpsburg, Maryland, occurs, and becomes the bloodiest one-day engagement of the Civil War. General Lee invades the North in an attempt to isolate Washington, D.C., but finds himself thwarted by General McClellan and the Union forces. The Union is aided by a copy of Lee's orders, left by a Confederate soldier at a campsite. In the carnage that follows, nearly 5,000 men are killed and 18,000 wounded. McClellan fails to follow Lee's retreat, and a frustrated Lincoln consequently removes him from his command. </p>
"1862/09/22","","Day",<p>Following the Confederate defeat at Antietam, Lincoln issues the Emancipation Proclamation, to go into effect on January 1, 1963. In the document, Lincoln frees all slaves in Confederate or contested areas of the South. Slaves in non-Confederate border states and in parts of the Confederacy under Union control are not included. European public opinion sides with Lincoln and the Union. </p>
"1862/12/13","","Day",<p>The Battle of Fredericksburg, Virginia, marks a grave defeat for the Union. General Lee and his Confederate troops defeat General Burnside. Union losses number more than 12,600, while Confederate casualties rise to 5,300. </p>
"1862/12/31","","Day",<p>The Union ironclad <i>Monitor</i> (now <i>Virginia</i>) sinks off Cape Hatteras, North Carolina. </p>
"1862/11/01","","Month",<p>Midterm congressional elections take place. The Republicans maintain control of both the House of Representatives and the Senate, with a 39-12 majority in Senate and a 103-80 majority in the House. </p>
"1863/01/01","","Day",<p>The Emancipation Proclamation goes into effect. </p>
"1863/01/02","","Day",<p>The Battle of Murfreesboro occurs. </p>
"1863/02/24","","Day",<p>The territory of Arizona is formed from the Territory of New Mexico. </p>
"1863/02/25","","Day",<p>The National Banking Act, designed by Secretary of the Treasury Salmon P. Chase, creates the system for a national bank.  To supervise, Congress creates the "controller of the currency" position, which is first given to Hugh McCulloch on May 9, 1863. </p>
"1863/03/03","","Day",<p>Congress passes a conscription law, requiring military service. For $300, a draftee can hire a substitute; this addendum angers some who claim it is "aristocracy legislation." </p>
"1863/05/01","1863/05/04","Day",<p>Near the District of Columbia, in Virginia, the Battle of Chancellorsville takes place. General Lee wins a brilliant victory over Union General Joseph Hooker. Following his success, Lee decides to begin a second invasion into the North. </p>
"1863/05/02","","Day",<p>General Stonewall Jackson is wounded in the Battle of Chancellorsville, accidentally shot by his own troops; his left arm must be amputated. Jackson catches pneumonia and dies on May 10. </p>
"1863/05/03","","Day",<p>The Territory of Idaho is created from existing territories. This territory later includes the states of Montana and Wyoming. </p>
"1863/06/20","","Day",<p>West Virginia is admitted to Union as the thirty-fifth state. </p>
"1863/07/01","1863/07/01","Day",<p>The Battle of Gettysburg, the war's greatest engagement, occurs. In his invasion of the North, Lee makes a bid to smash through Union forces and take Washington, D.C., from the west with 75,000 troops. General George E. Meade, who replaced McClellan, meets him accidentally at Gettysburg, Pennsylvania. After two days of battle, Lee makes his greatest blunder and sends General George Picket and 15,000 men on a suicidal charge across Cemetery Ridge. By July 4, both sides are exhausted; the following day, Lee's troops retreat across the Potomac, never to return to the North. The South suffers greatly with nearly 30,000 killed, wounded, or missing; the North endures 23,000 casualties. For the remainder of the war, Lee will fight on the defensive. Meanwhile, Meade fails to pursue the retreating Confederate troops, frustrating Lincoln. </p>
"1863/07/04","","Day",<p>After an engagement of months, General Ulysses S. Grant finally captures Vicksburg, Mississippi, a Confederate stronghold. Using the tactics of "total war," Grant feeds his troops on Southern crops and starves Vicksburg and its defenders into submission. Capturing Vicksburg gives the Union control over the entirety of Mississippi. Shortly thereafter, Lincoln appoints Grant his lieutenant general, announcing, "Grant is my man, and I am his the rest of the war." </p>
"1863/07/13","","Day",<p>Angry over the draft, rioters in New York City protest the conscription act. More than one-hundred people, many of them African-American, are killed. Lincoln has units from Gettysburg rush to the city to end the fighting. </p>
"1863/11/19","","Day",<p>Lincoln makes his famous Gettysburg Address -- consisting of three short paragraphs -- on the bloodstained battlefield. Ceremonies take place which include the dedication of a national cemetery. </p>
"1863/12/08","","Day",<p>Lincoln offers a full pardon to Southerners who take the prescribed oath. </p>
"1864/05/07","1864/05/20","Day",<p>General Grant continues his Spotsylvania campaign, hammering through Lee's forces. </p>
"1864/06/07","","Day",<p>The Republican National Convention nominates President Lincoln for second term. Andrew Johnson is nominated as his new vice president. </p>
"1864/07/05","","Day",<p>Horace Greeley, a radical Republican, is eager for peace. Lincoln opens peace negotiations and tells Greeley that emissaries from Jefferson Davis are in Canada. Without proper authority, however, negotiations at Niagara Falls, New York, fail. </p>
"1864/08/29","","Day",<p>The Democratic National Convention nominates General George B. McClellan, the former Union commander, for the presidency and George Pendleton for the vice-presidency. Claiming the war effort a failure, the Democrats support a ceasefire and peace conference. </p>
"1864/09/01","1864/09/02","Day",<p>Confederates under General John Hood evacuate from Atlanta, Georgia. The next day, Union forces led by General William Tecumseh Sherman occupy the city. Grant's colleague, Sherman will continue his run through Georgia, utilizing the tactics of "total warfare." </p>
"1864/10/31","","Day",<p>Nevada is admitted to the Union as the thirty-sixth state. </p>
"1864/11/08","","Day",<p>Following decisive Union victories by Admiral Farragut in Alabama and General Sherman in Atlanta, Abraham Lincoln is reelected as President of the United States, with Andrew Johnson as his vice president. Along with 55 percent of the popular vote, Lincoln wins 212 electoral votes to McClellan's 21. </p>
"1864/11/16","","Day",<p>After burning Atlanta, General Sherman begins his notorious 300-mile march to the sea with 62,000 men. Traveling roughly ten miles a day, the Union troops ravage the countryside, leaving a path of destruction fifty miles wide; they capture Savannah in late December. Sherman then turns toward South Carolina. </p>
"1864/12/15","","Day",<p>Salmon P. Chase is appointed Chief Justice of the Supreme Court. Formerly Governor of Ohio and then secretary of the treasury under Lincoln, Chase kept the nation out of financial ruin through Legal Tender Act in 1862. With this legislation, Chase issued 150 million "greenbacks" (paper money), ordering that "In God We Trust" be printed on them to encourage people to accept the money at face value. Chase had also orchestrated the first income tax in 1863. </p>
"1864/11/01","","Month",<p>In congressional elections, the Republicans increase their power in both houses. They now hold majorities of 42-10 in the Senate and 149-42 in the House. </p>
"1865/01/31","","Day",<p>With Lincoln's influence, the House of Representatives approves the Thirteenth Amendment, which calls for the emancipation of all slaves and no compensation to their owners. The amendment was passed by the Senate in 1864 but failed to receive the necessary votes in the House. By December of 1865, enough states ratify the amendment to make it constitutionally binding. </p>
"1865/02/06","","Day",<p>The Confederate Congress in Richmond gives Robert E. Lee overall command of the Confederate armies. Previously, President Jefferson Davis had served as commander. </p>
"1865/03/13","","Day",<p>Desperate for manpower, the Confederate Congress approves the recruitment of 300,000 slaves for military involvement. Jefferson Davis declares that all volunteers and their families will be given freedom. </p>
"1865/03/03","","Day",<p>Congress creates the Freedmen's Bureau to help Southern blacks affected by the war. The Bureau supplies blacks with food, clothing, and medical care, and will orchestrate the placement of freedmen on abandoned lands. </p>
"1865/03/04","","Day",<p>Abraham Lincoln is inaugurated as President for his second term while Andrew Johnson succeeds Hannibal Hamlin as vice-president. </p>
"1865/04/03","","Day",<p>Richmond is evacuated. </p>
"1865/04/09","","Day",<p>After Union forces capture much-needed Confederate supplies at Appomattox Court House, Virginia, Confederate General Robert E. Lee surrenders to General Grant, marking the end of the Civil War. </p>
"1865/04/14","","Day",<p>Actor and Confederate sympathizer John Wilkes Booth shoots President Lincoln at Ford's Theater in Washington, D.C., at around 10:15 p.m. </p>
"1865/04/15","","Day",<p>Abraham Lincoln dies at 7:22 a.m. in the home of William Petersen. Vice President Andrew Johnson is sworn in as the seventeenth President of the United States. </p>
