
<h2>2 8, 1809</h2>"","",<p>Congress announces the results of the 1808 presidential election. Jefferson's secretary of state, Republican-Democrat James Madison, emerges victorious. Madison swamps Federalist opponent Charles C. Pinckney in electoral votes, 122 to 47. Pinckney carries only five states -- all of them in New England -- to Madison's twelve.</p>
<h2>3 4, 1809</h2>"","",<p>James Madison is inaugurated as the fourth President of the United States. </p>
<h2>3 , 1809</h2>"","",<p>Congress authorizes $12,000 to refurbish the White House. </p>
<h2>4 19, 1809</h2>"","",<p>After negotiations with British minister Erskine, Madison issues a proclamation -- known as the Erskine Agreement -- revoking the embargo on Britain, effective June 10. For his part, Erskine leads Madison to believe that Britain will revoke its Orders in Council. On March 25, however, the American envoy in Britain learns that British foreign secretary Canning has canceled the Erskine Agreement; news reaches Madison six weeks later. On August 9, Madison rescinds his proclamation establishing trade with Britain and resumes a policy of nonintercourse. </p>
<h2>8 , 1809</h2>"","",<p>Madison persuades Albert Gallatin to remain secretary of treasury in the face of strong congressional opposition and discord within Madison's cabinet. </p>
<h2>1 3, 1810</h2>"","",<p>Prompted by tensions with Spain over West Florida, Madison calls for renewal of an act authorizing the President to call out 100,000 militiamen, fill up the regular army to its authorized strength, establish a force of 20,000 volunteers for immediate emergencies, and reactivate idle components of the naval fleet. </p>
<h2>4 16, 1810</h2>"","",<p>John Marshall overrules state legislation in <i>Fletcher v. Peck</i>, finding attempts to rectify the Yazoo land fraud scheme a violation of contract rights. Madison determines to add Republicans to the court. </p>
<h2>5 1, 1810</h2>"","",<p>To replace the Nonintercourse Act, Congress passes Macon's Bill Number 2, which allows American ships to carry French or English goods while barring belligerent powers from American ports. The bill further promises to renew nonintercourse with one of the two belligerent nations if the other withdraws its decrees. Trade with France and Britain is restored so long as the European nations respect American trade rights. </p>
<h2>8 5, 1810</h2>"","",<p>The Cadore letter notifies the American minister in France that the Decrees of Berlin and Milan will be repealed, effective November 1, if Britain revokes its Orders in Council or if the United States bars trade with Britain. </p>
<h2>10 27, 1810</h2>"","",<p>Madison issues a proclamation authorizing occupation of West Florida, also claimed by Spain, as part of the Louisiana Purchase. </p>
<h2>11 2, 1810</h2>"","",<p>Under the terms of Macon's Bill Number 2, Madison accepts a French offer to stop confiscation of American supplies and ships. In February 1911, he declares a halt in trade with Britain unless the Orders are repealed. Undeterred, Britain vows to continue to seize American ships until France ends its trade restrictions. </p>
<h2>2 2, 1811</h2>"","",<p>Madison reestablishes nonintercourse with Britain. Meanwhile, the French continue their seizure of American ships. </p>
<h2>3 3, 1811</h2>"","",<p>The Bank of the United States closes. Treasury Secretary Gallatin urges Congress to extend its charter but fails to convince members concerned with the large British interest in the Bank. </p>
<h2>3 20, 1811</h2>"","",<p>After Madison dismisses Secretary of State Robert Smith, James Monroe accepts Madison's offer of the cabinet position. </p>
<h2>Spring, 1811</h2>"","",<p>Madison vetoes two bills of Congress, one granting land in the Mississippi Territory to a Baptist congregation and the other incorporating an Episcopal church in Washington, D.C. Madison argues that both bills violate the non-establishment clause of the First Amendment. Later in the year, Congress will pass a Religious Freedom Act. </p>
<h2>4 16, 1811</h2>"","",<p><i>National Intelligencer</i> editor Gales prints a summary of his discussion with Madison. The talks indicate that Madison has hardened his attitude toward Britain. </p>
<h2>5 16, 1811</h2>"","",<p>After it is attacked, the U.S. battleship <i>President</i> fires on the British ship <i>HMS Little Belt</i>. </p>
<h2>6 23, 1811</h2>"","",<p>The British foreign secretary announces an end to the Orders in Council. The announcement comes too late, however, as Madison requested a declaration of war against Britain on June 1. </p>
<h2>7 2, 1811</h2>"","",<p>Former secretary of state Robert Smith publishes an <i>Address to the People of the United States</i>, attacking Madison's administration and revealing the disagreements within the cabinet. </p>
<h2>7 6, 1811</h2>"","",<p>The new British foreign minister, Foster, arrives in Washington and warns Madison that if nonintercourse remains the policy of the United States, Britain will retaliate against American commerce. </p>
<h2>7 24, 1811</h2>"","",<p>Madison calls a special session of Congress to convene November 4 in preparation for war against Britain. </p>
<h2>11 5, 1811</h2>"","",<p>Madison delivers a tentative war message to Congress, indicating his shift in policy. </p>
<h2>11 7, 1811</h2>"","",<p>After acknowledging the danger posed by Shawnee leader Tecumseh, who hopes to assemble a confederation of tribes, General William Henry Harrison, the governor of the Indian Territory, carriers out a pre-emptive strike on Tecumseh. Harrison's militia is barely successful at the Battle of Tippecanoe, an engagement that serves as a prelude to the War of 1812. Tecumseh flees to Canada and British protection. On December 18, Madison proclaims the Battle of Tippecanoe a victory that will restore peace to the northwestern frontier. </p>
<h2>11 25, 1811</h2>"","",<p>The Senate confirms James Monroe as secretary of state, replacing Robert Smith. </p>
<h2>11 29, 1811</h2>"","",<p>The House Committee on Foreign Relations recommends legislation to bring the Army up to full strength, establish a second regular army of 10,000, enable the President to organize 50,000 volunteers, strengthen the Navy, incorporate militia units into national service, and arm merchantmen. </p>
<h2>1 10, 1812</h2>"","",<p>Congress passes an Army bill to enlarge the second regular army to 25,000. The increase in manpower is far greater than Madison's request -- he had asked for a force of 10,000 -- but the bill provides less flexibility than Madison had requested. Amidst disagreements between Madison's administration and Congress, modifications are made to the legislation over the summer. </p>
<h2>1 27, 1812</h2>"","",<p>The House refuses to enlarge the Navy. </p>
<h2>3 9, 1812</h2>"","",<p>Madison shares the letters of John Henry, agent for governor of Canada, with Congress, having purchased the letters the previous month for $50,000. The documents indicate that the governor general of Canada is inciting rebellion in New England. </p>
<h2>3 21, 1812</h2>"","",<p>British minister Foster tells Madison's administration that the Orders in Council will be continued. </p>
<h2>3 23, 1812</h2>"","",<p>News arrives that France has sunk American ships carrying flour to British troops in Spain, leading many in Congress to call for war against France. The incident is seen by many as "proof" that France has not repealed edicts against American neutral commerce. </p>
<h2>4 2, 1812</h2>"4 3, 1812","",<p>Congress passes an embargo, effective through July 4, on all shipping to give shippers the opportunity to get their vessels to safe haven. </p>
<h2>4 15, 1812</h2>"","",<p>Louisiana is admitted to the nation as the eighteenth state of the Union. </p>
<h2>5 18, 1812</h2>"","",<p>Amidst fierce intra-party competition, Madison is nominated by the Democratic-Republicans for a second term as President.</p>
<h2>5 23, 1812</h2>"","",<p>Madison sees the letter from Lord Castlereagh to British minister Foster confirming the continuance of the Orders in Council, and the President begins drafting his war message to Congress. </p>
<h2>6 1, 1812</h2>"","",<p>Madison delivers a message to Congress, justifying war against Britain and asking for a declaration of war. On June 4, the House of Representatives votes 79-49 for war against Britain. On June 16, Britain revokes its Orders in Council in an attempt to avoid war with the United States, but news of the British decision will reach the United States too late. On June 17, Senate votes 19-13 for a declaration of war. </p>
<h2>6 18, 1812</h2>"","",<p>Madison issues a declaration of war against Britain. In addition to concern over British actions with regard to international trade, some proponents of war also endorse territorial expansion into British Canada and Spanish Florida; they also hope to end suspected British support of Indian attacks. Without the Bank of America and with an Army of only 6,700, the United States faces dire economic and military straits at the war's outset. The U.S. Navy, with a fleet of only sixteen vessels, delivers the nation's only victories in the first year of war. </p>
<h2>6 22, 1812</h2>"","",<p>General Henry Dearborn, commanding American forces into Canada, requests that all New England governors cap the size of militias guarding their respective coasts and frontiers; Connecticut, Massachusetts, and Rhode Island refuse. </p>
<h2>8 8, 1812</h2>"","",<p>Dearborn signs an armistice with the governor of Lower Canada. Madison repudiates it the following week, and Dearborn terminates the armistice on August 25. </p>
<h2>8 11, 1812</h2>"","",<p>Michigan governor and general William Hull, in charge of the American offensive from Detroit into Upper Canada, gives up his attack on Fort Malden and surrenders Detroit to British forces on August 16 without firing a shot. </p>
<h2>11 1812</h2>"12 1812","",<p>Despite fierce competition and conflict within the Democrat-Republican party, Madison wins reelection, securing 128 electoral votes to Federalist DeWitt Clinton's 89. The electoral results indicate a divide within the nation. </p>
<h2>1 14, 1813</h2>"","",<p>John Armstrong of New York replaces William Eustis as secretary of war. </p>
<h2>1 18, 1813</h2>"1 23, 1813","",<p>Americans throughout the northwest are outraged by Winchester's battle and surrender at Frenchtown, and the Wyandotte murder of sixty Kentucky prisoners of war. The northwest ceases to play a role in war strategy. </p>
<h2>1 1813</h2>"","",<p>William Jones of Pennsylvania replaces Paul Hamilton as secretary of the Navy. </p>
<h2>4 21, 1813</h2>"","",<p>Albert Gallatin and James A. Bayard leave to join John Quincy Adams in St. Petersburg for peace negotiations sponsored by Russia. </p>
<h2>5 31, 1813</h2>"","",<p>John Quincy Adams, James A. Bayard, and Albert Gallatin are nominated as representatives to the peace negotiations, but the Senate rejects Gallatin on July 19. Gallatin is eventually confirmed after the Senate forces Madison to declare Gallatin's treasury cabinet post vacant. </p>
<h2>9 10, 1813</h2>"","",<p>In an impressive display of valor, Captain Oliver Perry wins control of Lake Erie in the Battle of Put-In-Bay. For four hours, Perry's flagship, the <i>Lawrence</i>, receives heavy attacks from two British warships, leaving most of his crew dead or wounded. Instead of surrendering, however, Perry rows to another ship and launches an attack on the British, finally accepting surrender of the entire British fleet. Perry sends word to General Harrison, stating, "We have met the enemy and they are ours." </p>
<h2>10 5, 1813</h2>"","",<p>The United States under General Harrison emerges victorious at the Battle of the Thames -- the most important American victory to date -- as it ends British and Indian control in Northwest and Upper Canada. Tecumseh dies in the battle. </p>
<h2>12 9, 1813</h2>"","",<p>Madison calls for a total embargo on exports and a ban on all imports of British origin, believing that Britain depends on trade with the United States. Congress passes the embargo just days later. </p>
<h2>1 28, 1814</h2>"","",<p>James Jackson of Virginia introduces a constitutional amendment in the House authorizing the establishment of a national bank, but Congress postpones consideration. </p>
<h2>2 , 1814</h2>"","",<p>Madison appoints Henry Clay, Albert Gallatin, James Bayard, Jonathan Russell, and John Quincy Adams as commissioners to negotiate directly with Britain in Gothenburg, Sweden. These negotiations are later transferred to Ghent, Belgium. </p>
<h2>2 9, 1814</h2>"","",<p>George Washington Campbell of Tennessee replaces Gallatin as secretary of the treasury. </p>
<h2>3 3, 1814</h2>"","",<p>Congress authorizes the borrowing of $25 million to finance war costs. </p>
<h2>3 27, 1814</h2>"","",<p>Under the command of Andrew Jackson, 2,000 troops defeat the Creek Confederation at the Battle of Horseshoe Bend in the Tallapoosa River, eliminating the Confederation as an obstacle to American expansion toward the Gulf Coast. The engagement is one of the most significant American victories in the War of 1812, providing the United States with two-thirds of Creek land in the Treaty of Fort Jackson. </p>
<h2>3 31, 1814</h2>"","",<p>Napoleon's European empire collapses. Learning of Napoleon's defeat, Madison calls for an immediate repeal of the trade embargo with neutral nations, signaling a major reassessment of American war aims and strategy. He signs the bill into law on April 14. The British, meanwhile, can now turn their complete attention to war with the United States. </p>
<h2>5 11, 1814</h2>"","",<p>William Henry Harrison resigns as Major General and is replaced by Andrew Jackson, against Madison's orders. </p>
<h2>6 7, 1814</h2>"","",<p>Madison and his cabinet decide to continue with the attempted invasion of Canada. </p>
<h2>7 1, 1814</h2>"","",<p>Madison convenes his cabinet to establish a special military district for the protection of Washington and Baltimore, placing it under the command of Brigadier General William Winder. </p>
<h2>7 27, 1814</h2>"","",<p>The Battle of the Burnt Corn in the Mississippi Territory brings the Creek Indians into the war against the United States. </p>
<h2>8 24, 1814</h2>"","",<p>With momentum on their side, and in retaliation for the torching of Canadian Parliament buildings, British forces attack and burn Washington, D.C., setting the White House, the Capitol, and other federal buildings ablaze. </p>
<h2>9 14, 1814</h2>"","",<p>Following the sack of Washington, U.S. General Samuel Smith turns back a British attack on Fort Henry at Baltimore. After the unsuccessful British offensive, Francis Scott Key pens "The Star-Spangled Banner." </p>
<h2>9 27, 1814</h2>"","",<p>Madison nominates James Monroe as secretary of war to replace John Armstrong. Monroe will serve as secretary of both war and state until the end of the war. </p>
<h2>10 5, 1814</h2>"","",<p>Alexander J. Dallas is appointed secretary of treasury, replacing the inept George W. Campbell. On October 17, Dallas calls for Congress to establish a national bank to finance the war and to increase taxes. The Senate passes a new bank bill on December 9. </p>
<h2>10 18, 1814</h2>"","",<p>The Massachusetts General Court calls a convention of New England states, whose livelihood depends largely on international trade, to coordinate regional grievances against the federal government. From December 15 through January 5, delegates from some New England states meet in Hartford, Connecticut, to discuss grievances against the federal government and to provide alternative solutions to talk of secession among New England radicals. </p>
<h2>11 7, 1814</h2>"","",<p>Without authorization, Andrew Jackson takes Spanish-held and British-occupied Pensacola, Florida, in pursuit of Creek warriors. </p>
<h2>12 15, 1814</h2>"","",<p>Twenty-two delegates at the Hartford Convention issue a report condemning the federal government for failing to defend New England. The report recommends that states negotiate arrangements with the federal government for their defense, and proposes constitutional amendments to protect the region's increasingly minority status in the Union. Following news of Jackson's victory at New Orleans, the U.S. public condemns the Hartford Convention as anti-American. The Federalist Party suffers as a result. </p>
<h2>12 24, 1814</h2>"","",<p>In Europe, the United States and Britain sign the Treaty of Ghent. News of the Treaty will reach the United States in February 1815. </p>
<h2>1 7, 1815</h2>"","",<p>The House of Representatives passes an amended bank bill as a compromise between Federalists and anti-bank Republicans. The bill is nevertheless unsatisfactory to Madison and Secretary of the Treasury Dallas. Madison vetoes the bank bill on January 30. </p>
<h2>1 8, 1815</h2>"","",<p>Jackson, leading 4,000 militiamen, citizens, and regular soldiers, wins a resounding victory over 6,000 British forces in the Battle of New Orleans. Many of Jackson's troops are volunteers, among them free blacks and slaves. There are just a dozen American casualties to 2,000 British casualties. Jackson's victory, along with his success against the Creeks, makes him a national hero. </p>
<h2>1 27, 1815</h2>"","",<p>Madison signs a bill allowing the President to call up 40,000 state troops. Congress has limited the bill, however, by authorizing troops to serve only in their home states with the consent of state governors. </p>
<h2>2 13, 1815</h2>"2 14, 1815","",<p>News arrives of the December 1814 Treaty of Ghent that ends the War of 1812. On February 15, Congress appropriates $500,000 for the reconstruction of federal buildings. The Senate ratifies the Treaty of Ghent on February 16. </p>
<h2>5 10, 1815</h2>"","",<p>With Madison having secured a declaration of war on Algiers, Captain Stephen Decatur leads a flotilla from New York against the Mediterranean pirates, who attack American ships during the War of 1812. Algiers surrenders on June 30. </p>
<h2>June 1815</h2>"","",<p>Gallatin negotiates a commercial convention with Britain, further signifying the potential for the United States to play an important role in international trade and industrialization. </p>
<h2>12 , 1815</h2>"","",<p>Madison presents his seventh annual message to Congress, advocating military streamlining, a new national bank, protective tariffs to promote industry, and internal improvements. </p>
<h2>4 10, 1816</h2>"","",<p>Madison signs a bill re-chartering a new national bank in Philadelphia. The charter is set for a twenty-one year term. </p>
<h2>4 19, 1816</h2>"","",<p>Madison signs a bill admitting Indiana to statehood. </p>
<h2>11 1816</h2>"12 1816","",<p>Secretary of State James Monroe is elected President, easily defeating Federalist Rufus King of New York. Monroe receives 183 electoral votes to King's 34. </p>
<h2>12 3, 1816</h2>"","",<p>Madison delivers his eighth annual address to Congress, calling for vigilance in foreign affairs, internal improvements, and the restructuring of the judiciary and executive offices. </p>
<h2>3 3, 1817</h2>"","",<p>Madison vetoes Henry Clay's "Bonus Bill" for internal improvements. </p>
<h2>3 4, 1817</h2>"","",<p>Republican-Democrat James Monroe is inaugurated as the fifth President of the United States. </p>
