
<h2>3 4, 1897</h2>"",""<p>William McKinley is inaugurated as the twenty-fifth President of the United States. McKinley asserts: "The country is suffering from industrial disturbances from which speedy relief must be had. Our financial system needs some revision; our money is all good now, but its value must not further be threatened."</p>
<h2>3 15, 1897</h2>"",""<p>President McKinley calls Congress into a special session for the purpose of revising the tariff laws. </p>
<h2>4 19, 1897</h2>"",""<p>John J. McDermott wins the first Boston Marathon. The 26.2 miles from Hopkinton to Copley Square will become one of the world's most prestigious marathons. </p>
<h2>5 </h2>"",""<p>Congress appropriates $50,000 for the relief of Americans in Cuba. </p>
<h2>7 14, 1897</h2>"",""<p>The first shipment of gold discovered in Alaska, totaling $750,000, arrives in San Francisco. </p>
<h2>7 24, 1897</h2>"",""<p>President McKinley signs the Dingley Tariff Law, which raises custom duties by an average of 57 percent. Although American industries no longer needed such heavy protection against foreign goods, the tariff was raised nonetheless; imported woolen products, for example, faced a 91 percent rate. Republicans associate the high tariff with national prosperity while Democrats and progressives will blame the tariff for causing subsequent price increases. </p>  
<h2>9 10, 1897</h2>"",""<p>More than twenty workers are killed in Lattimer, Pennsylvania, after deputy sheriffs open fire on striking coal miners. In sympathy, coal miners in the Ohio, West Virginia, and the Lehigh Valley of Pennsylvania walk off their jobs. The strike is settled soon thereafter, with Pennsylvania workers being awarded an eight-hour day. </p> 
<h2>12 6, 1897</h2>"",""<p>President McKinley's first annual message to Congress is read aloud. The President states that while the government of Spain should be given time to reform its behavior in Cuba, America would continue to devote significant diplomatic attention to the island. McKinley also reminds Americans to refrain from factionalism: "Questions of foreign policy, of revenue, the soundness of the currency, the inviolability of national obligations, the improvement of the public service, appeal to the individual conscience of every earnest citizen to whatever party he belongs or in whatever section of the country he may reside." </p>
<h2>1 12, 1898</h2>"",""<p>In Havana, Cuba, pro-Spanish groups riot in opposition to Cuban autonomy. </p>
<h2>1 25, 1898</h2>"",""<p>The U.S. Battleship <i>Maine</i> arrives in Havana on a nominally "friendly visit." Its true mission is to protect American life and property.  </p>
<h2>2 9, 1898</h2>"",""<p>A letter written by Spanish minister to the United States Enrique deLÙme, containing insults directed at President McKinley, is published in William Randolph Hearst's <i>New York Journal</i>. </p>
<h2>2 15, 1898</h2>"",""<p>The battleship <i>Maine</i> explodes and sinks in Havana harbor, killing 266 Americans. Subsequent press coverage of the event points to Spanish sabotage as the cause of the disaster, despite dubious evidence. The sinking of the <i>Maine</i> fans popular opinion, already sympathetic to the cause of Cuban independence, in support of American intervention. </p>  
<h2>3 9, 1898</h2>"",""<p>At President McKinley's behest, Congress votes a $50 million appropriation for national defense. </p>
<h2>3 17, 1898</h2>"",""<p>The U.S. Navy reports that the <i>Maine</i> explosion was the result of external factors. </p>
<h2>3 22, 1898</h2>"",""<p>The Spanish Navy releases its own report on the <i>Maine</i> disaster, concluding that an internal explosion destroyed the battleship. </p>
<h2>4 11, 1898</h2>"",""<p>President McKinley asks Congress for authority to "use armed force" in Cuba to end the civil war. Meanwhile, Spanish Prime Minister Sagasta makes a last-minute peace concession by offering the Cubans limited autonomy. </p>
<h2>4 19, 1898</h2>"",""<p>Congress adopts a joint resolution authorizing President McKinley to intervene in Cuba. The resolution also states that the United States has no plans to annex Cuba. Spain counters by severing diplomatic relations with the United States. </p>
<h2>4 21, 1898</h2>"",""<p>President McKinley orders a blockade of northern Cuban ports. </p>
<h2>4 22, 1898</h2>"",""<p>Congress passes the Volunteer Army Act, which authorizes the organization of the First Volunteer Cavalry, or Rough Riders, under the command of Colonel Leonard Wood and Lt. Colonel Theodore Roosevelt. That same day, the U.S. captures its first spoils of war, the Spanish ship <i>Buena Ventura</i>. </p>
<h2>4 23, 1898</h2>"",""<p>President McKinley calls for 125,000 volunteers to fight the war with Spain. </p>
<h2>4 23, 1898</h2>"",""<p>Spain declares war on the United States. </p>
<h2>4 25, 1898</h2>"",""<p>The United States Congress declares war on Spain. </p>
<h2>5 </h2>"",""<p>Commodore George Dewey, commanding an American squadron of six ships, soundly defeats a larger but outgunned Spanish fleet at Manila Bay. This action opens the door for American occupation of Manila in August. </p>
<h2>5 </h2>"",""<p>President McKinley issues a new call for volunteers, asking for an additional 75,000. A U.S. troop expedition of 2,500 men also sets sail for Manila, Philippines, from San Francisco, California. </p>
<h2>6 1, 1898</h2>"",""<p>Congress passes the Erdman Arbitration Act, which authorizes government mediation between interstate carriers and their employees. The legislation prohibits interstate carriers from discriminating against or blacklisting union laborers. The Supreme Court would rule the Erdman Act unconstitutional in June 1908. </p>
<h2>6 10, 1898</h2>"",""<p>Roughly 600 U.S. Marines land at Guant·namo, Cuba. </p>
<h2>6 10, 1898</h2>"",""<p>Congress passes the War Revenue Act, which generated about $150 million of tax revenue a year from taxes levied on beer, tobacco, amusements, and some business transactions. President McKinley signs the bill on June 13.	</p>
<h2>6 12, 1898</h2>"6 12-14, 1898",""<p>Some 17,000 U.S. troops under the command of General William Shafter embark from Key West, Florida, headed for Cuba. </p>
<h2>6 21, 1898</h2>"",""<p>Guam, whose Spanish commander was oblivious to the outbreak of the war, surrenders to advancing western Pacific fleets. The ignorance of the Spanish garrison becomes apparent to the captain of the <i>U.S.S. Charleston</i> when, following his bombardment of Guam, the Spanish apologize for not having returned the salute. </p>
<h2>6 24, 1898</h2>"",""<p>The United States defeats Spanish troops at the Battle of Las 
Guasimas, the first major land battle of the Spanish-American War. </p>
<h2>7 1, 1898</h2>"",""<p>After heavy fighting, American forces in Cuba take the Spanish garrisons at El Caney and San Juan Hill. </p>
<h2>7 3, 1898</h2>"",""<p>American naval forces destroy the Spanish fleet off Santiago de Cuba. </p>
<h2>7 7, 1898</h2>"",""<p>President McKinley signs a joint congressional resolution providing for the annexation of Hawaii. </p>
<h2>7 17, 1898</h2>"",""<p>Santiago de Cuba surrenders, along with 24,000 Spanish troops, to American General William Shafter. </p>
<h2>7 25, 1898</h2>"",""<p>American forces invade Puerto Rico, encountering little resistance. </p>
<h2>8 12, 1898</h2>"",""<p>Spain and the United States sign an armistice in which Spain agrees to grant Cuba its independence and cede Puerto Rico and Guam to the United States. The fate of the Philippines is left to be determined at a postwar conference between the United States and Spain.  </p>
<h2>8 14, 1898</h2>"",""<p>Spanish forces in the Philippines surrender to the United States. </p>
<h2>9 9, 1898</h2>"",""<p>President McKinley appoints U.S. peace commissioners for negotiations with Spain; Secretary of State William R. Day will lead the delegation. McKinley asks Day to resign his office to assume the leadership of the peace commission. John Hay becomes secretary of state on September 30. </p>
<h2>9 26, 1898</h2>"",""<p>President McKinley appoints the Dodge Commission to investigate the conduct of the War Department. </p>
<h2>10 12, 1898</h2>"",""<p>A strikers' riot in Virden, Illinois, leads to thirteen deaths and twenty-five injuries. </p>
<h2>10 28, 1898</h2>"",""<p>American peace commissioners in Paris receive instructions to demand from Spain the cession of the Philippine Islands. </p>
<h2>11 8, 1898</h2>"",""<p>The Republicans gain Senate seats in mid-term elections, emerging with a 53-26-8 lead; they lose strength in the House, where their advantage narrows to 185-163-9. </p>
<h2>12 5, 1898</h2>"",""<p>President McKinley's second annual message is read to both Houses of Congress. He declares his intention to build an inter-oceanic canal through Nicaragua and discusses the merits of fighting the Spanish-American war: "Military service under a common flag and for a righteous cause has strengthened the national spirit and served to cement more closely than ever the fraternal bonds between every section of the country." </p>
<h2>12 10, 1898</h2>"",""<p>The United States and Spain sign the Treaty of Paris. </p>   
<h2>1 1, 1899</h2>"",""<p>The United States takes official control of Cuba. </p>
<h2>1 20, 1899</h2>"",""<p>President McKinley appoints Jacob Gould Schurman chairman of the first Philippine Commission. </p>
<h2>2 4, 1899</h2>"",""<p>Philippine guerrillas, led by Emilio Aguinaldo, attack U.S. forces in Manila, beginning the Philippine Insurrection. The initial skirmishes, in which 57 American fighters are killed and 215 are wounded, last several days. </p>
<h2>2 6, 1899</h2>"",""<p>The Senate ratifies the peace treaty between the United States and Spain by a vote of 57 to 27. The United States acquires Puerto Rico and Guam, and assumes the temporary administration of Cuba. While the United States pays Spain $20 million for certain Filipino holdings, the sum is interpreted by some as payment for the outright purchase of the Philippines. </p>
<h2>2 14, 1899</h2>"",""<p>Congress authorizes voting machines for federal elections, subject to the request of individual states. </p>
<h2>5 </h2>"",""<p>President McKinley issues an executive order exempting between 3,000 to 4,000 positions from competitive civil service examinations. McKinley's order marks a retreat from President Grover Cleveland's more aggressive practices of civil service reform. </p>
<h2>November 1899</h2>"",""<p>President McKinley becomes the first President to ride in an automobile when he motors in a Stanley Steamer in his hometown of Canton, Ohio. </p>
<h2>7 19, 1899</h2>"",""<p>Secretary of War Russell A. Alger resigns, effective August 1, after the Dodge Commission criticizes the War Department's handling of the war. Elihu Root replaces Alger. </p>
<h2>9 6, 1899</h2>"",""<p>Secretary of State John Hay issues the Open Door notes to Britain, France, Russia, and Japan. Hay calls for broad, multi-lateral access to Chinese markets across foreign spheres of influence as well as for the preservation of the territorial sovereignty of the Chinese Empire. </p>
<h2>12 5, 1899</h2>"",""<p>President McKinley sends his third annual message to Congress.  It focuses largely on foreign affairs, with McKinley calling for beefing up the U.S. Navy to benefit overseas commerce. With regard to the Philippines, McKinley affirms, "I shall use the authority vested in me by the Constitution and the statutes to uphold the sovereignty of the United States in those distant islands as in all other places where our flag rightfully floatsÖ.Aiming only at the public good, we cannot err. A right interpretation of the people's will and of duty cannot fail to insure wise measures for the welfare of the islands which have come under the authority of the United States, and inure to the common interest and lasting honor of our country." </p>
<h2>2 5, 1900</h2>"",""<p> Britain and the United States sign the Hay-Pauncefote Treaty to provide for an isthmian canal in Central America. </p>
<h2>3 7, 1900</h2>"",""<p>President McKinley signs the Gold Standard Act, which fixes the standard of value for all money issued or coined by the United States. It marks a victory for the so-called "goldbugs" from the Northeast and urban Midwest who pushed for gold-backed currency to stabilize industrial investment. Likewise, it is a crushing defeat for the free silver forces from the South and West who advocated silver coinage as a way to flush the agricultural economy with more available currency.  </p>
<h2>3 24, 1900</h2>"",""<p>The Carnegie Steel Company, organized in 1899, is incorporated in New Jersey ñ and capitalized at $160 million. </p>
<h2>4 7, 1900</h2>"",""<p>President McKinley appoints a Second Philippine Commission, chaired by William Howard Taft. </p>
<h2>4 30, 1900</h2>"",""<p>Congress passes an act establishing the Territory of Hawaii. </p>
<h2>6 19, 1900</h2>"6 21, 1900",""<p>The Republican National Convention re-nominates McKinley for the presidency. Spanish-American War Hero and New York governor Theodore Roosevelt is nominated for vice president. </p>
<h2>6 21, 1900</h2>"",""<p>Amnesty is given to Filipino insurgents in a decree issued by the military governor of the Philippines. </p>
<h2>7 3, 1900</h2>"",""<p>Secretary of State John Hay issues the second Open Door Note, a circular letter outlining American desires to keep China intact in the midst of Western intervention during the Boxer Rebellion. </p>
<h2>7 5, 1900</h2>"",""<p>The Democratic National Convention nominates William Jennings Bryan for the presidency and Adlai E. Stevenson for the vice presidency. During the subsequent campaign, Bryan charges McKinley with being an imperialist and runs once again on a "free silver" platform.  </p>
<h2>7 12, 1900</h2>"",""<p>President McKinley formally accepts the Republican presidential nomination in a speech at Canton, Ohio. McKinley's campaign slogan reminded voters of previous prosperity and promised more of the same: "Four more years of the full dinner pail." </p>
<h2>11 6, 1900</h2>"",""<p>William McKinley is re-elected President of the United States, with Theodore Roosevelt elected as vice president. McKinley wins with 292 electoral votes against 155 for William Jennings Bryan; Social Democratic candidate Eugene V. Debs secures 94,768 popular votes. Republicans strengthen their hold on both houses of Congress, securing a 55-31 majority in the Senate and a 197-151 majority in the House.  </p>
<h2>12 3, 1900</h2>"",""<p>President McKinley submits his fourth annual message to Congress. He notes that in foreign affairs, "the dominant question has been the treatment of the Chinese problem. Apart from this our relations with the powers have been happy."  </p>
<h2>12 20, 1900</h2>"",""<p>The Senate ratifies a modified version of the Hay-Pauncefote Treaty, in which the British government agrees to an American canal with the conditions that it be neutral and unfortified. This treaty abrogates the Clayton-Bulwer Treaty of 1850.  </p>
<h2>12 29, 1900</h2>"",""<p>Negotiations conclude between the Dutch and the Americans regarding the Dutch West Indies (which become the U.S. Virgin Islands), allowing Congress simply to appropriate funds to carry out the transfer. This transfer did not occur until 1917. </p>
<h2>1 10, 1901</h2>"",""<p>The first great oil strike in Texas occurs near Beaumont. </p>
<h2>3 1, 1901</h2>"",""<p>Congress adopts the Platt Amendment, which governs future relations between the United States and Cuba, as part of the Army Appropriation Act of 1901. The amendment allows American intervention in Cuban domestic affairs to preserve the sovereignty of the island nation against threats from other foreign powers.  </p>
<h2>3 4, 1901</h2>"",""<p>William McKinley is inaugurated as President for a second term, with Theodore Roosevelt sworn in as vice president. McKinley calls for the Filipino rebellion to end "without further bloodshed," wising that "there be ushered in the reign of peace to be made permanent by a government of liberty under law!" </p>
<h2>3 4, 1901</h2>"",""<p>North Carolina's George H. White leaves Congress, the last black member to serve for more than twenty-five years. </p>
<h2>3 11, 1901</h2>"",""<p>The British government informs the United States that it will not accept the Hay-Pauncefote Treaty as amended by the Senate. </p>
<h2>3 23, 1901</h2>"",""<p>Filipino resistance leader Emilio Aguinaldo is captured by Frederick Funston, crippling the Philippine insurrection. </p>
<h2>4 19, 1901</h2>"",""<p>The rebellion in the Philippines ends by proclamation. Sporadic fighting continues for another year before American military forces fully secure the islands. </p>
<h2>6 11, 1901</h2>"",""<p>President McKinley announces he will not be a candidate for a third term. </p>
<h2>9 5, 1901</h2>"",""<p>Speaking in Buffalo, New York, President McKinley endorses the concept of tariff reciprocity. McKinley also notes, in what would be his last speech, "The period of exclusiveness is past. The expansion of our trade and commerce is the pressing problem." </p>
<h2>9 6, 1901</h2>"",""<p>Leon Czolgosz shoots McKinley in the stomach while the President shakes hands at the Pan-American Exposition in Buffalo, New York. Czolgosz, an anarchist, admitted to the shooting, and he expressed no remorse for his actions. He died in the electric chair on October 29, 1901. </p>
<h2>9 14, 1901</h2>"",""<p>President McKinley dies from his wounds as the result of complications due to gangrene, and Vice President Theodore Roosevelt takes the oath of office to become the twenty-sixth President of the United States. </p>
