
<h2>1817/3/4</h2>"","",<p>President James Monroe is sworn in as the fifth President of the United States and delivers his first inaugural address.</p>
<h2>1817/4/28</h2>"","",<p>Britain's minister to the United States, Charles Bagot, agrees to the conditions of the Rush-Bagot Agreement. Following negotiations, acting Secretary of State Richard Rush sends the document to Britain in August 1816. This is the final version of a treaty that Monroe, while secretary of state under Madison, negotiated with British foreign minister Robert Stewart Castlereagh. The agreement limits naval capacity on the Great Lakes; in doing so, it alleviates possible tension between the two nations following the War of 1812. Each country is held to one ship on Lakes Champlain and Ontario, and two ships on all the other lakes. Limits are also placed on ship tonnage and armaments. </p>
<h2>1817/6/1</h2>"1817/9/28","Month",<p>Monroe embarks on a lengthy, sixteen-week tour of New England. In the absence of his major cabinet appointees, Monroe uses the tour to foster a sense of national unity through local political contact, public appearances, and private meetings with opposing Federalists. The tour gives birth to the designation of Monroe's administration as the "Era of Good Feelings." </p>
<h2>1817/12/1</h2>"","Month",<p>Monroe enunciates a policy of neutrality towards the Latin American colonies seeking independence. He also advocates a controversial fact-finding mission, the Aguirre Mission, to Buenos Aires that could be construed as recognition for the colony's sovereignty. </p>
<h2>1817/12/10</h2>"","",<p>Mississippi becomes the twentieth state in the Union. </p>
<h2>1817/12/26</h2>"","",<p>Secretary of War John C. Calhoun orders General Andrew Jackson to quell Seminole Indian uprisings in the Floridas and southern Georgia; Jackson also receives a private letter from Monroe urging such action. In March 1818, Jackson pursues the Seminoles into Spanish Florida -- where he suspects they are receiving assistance -- takes the fort of St. Marks on March 6, forces the surrender of Fort Carlos de Barrancas, and executes, among others, a Scot Indian trader and a British lieutenant. After capturing the Spanish capital in May, Jackson returns to Tennessee. </p>
<h2>1818/6/18</h2>"","",<p>Monroe learns of Jackson's exploits and, along with his cabinet (except John Quincy Adams), disapproves of Jackson's actions. Following protests from the ministers of Britain, Spain, and France, Monroe concedes that Jackson's behavior in Pensacola amounted to acts of war. The President repudiates Jackson and orders that Pensacola be handed back to Spain. Meanwhile, Adams, in a July letter, supports Jackson's tactics, blaming Spain for its inability to control the Indians. Despite his concession, Monroe recognizes that Jackson's activities in the Floridas provide the United States with a favorable strategic position for negotiations with Spain. </p>
<h2>1818/10/20</h2>"","",<p>British and American diplomats meet at the Anglo-American Convention and conclude a treaty resolving some, but not all, of the outstanding issues from the War of 1812. The nations agree on a northern border of the Louisiana Purchase, fixed at the 49th parallel, from the Lake of the Woods to the Rocky Mountains. Britain also acknowledges U.S. fishing rights off Newfoundland and provides compensation for slaves who fled to British lines. The Rush-Bagot Agreement is formally signed. </p>
<h2>1818/12/3</h2>"","",<p>Illinois is admitted as the twenty-first state of the Union.</p>
<h2>1818/12/14</h2>"","",<p>Alabama becomes the twenty-second state of the Union. </p>
<h2>1819/1/1</h2>"","Month",<p>The Panic of 1819 begins to take shape. A sharp decline in real estate values and a severe credit contraction (an inability to secure bank loans) inflates the currency and causes imports and prices to fall. In March, the price of cotton collapses in the English market. The conservative policies of the Second Bank of the United States, founded in 1816, accelerates the crisis, which ends around 1823. </p>
<h2>1819/2/15</h2>"","",<p>Debates over Missouri's admission to the Union are triggered in February by New York Republican congressman James Tallmadge, Jr. Tallmadge introduces an amendment to the Missouri statehood bill prohibiting further introduction of slavery in Missouri, despite the fact that 2,000 slaves already reside in the territory. He also proposes a gradual emancipation in the Louisiana territory north of 36 degrees, 30'. Currently, the United States has eleven slave and eleven free states. Missouri's population, meanwhile, surpasses 60,000, the minimum for a state constitution. </p>
<h2>1819/2/22</h2>"","",<p>The Transcontinental Treaty, also known as the Adams-Onis treaty, is resolved in February after the conclusion of negotiations dating back to July 1818. The treaty transfers the Floridas from Spain to the United States for $5 million, and advances the U.S. border across Mexico to the Pacific Ocean. Spain also relinquishes claims to the Oregon Territory. Secretary of State John Quincy Adams orchestrates the proceedings with the Spanish minister to Washington, Luis de Onis. </p>
<h2>1819/3/6</h2>"","",<p>Under Chief Justice John Marshall, the United States Supreme Court rules against the state of Maryland in <i>McCulloch v. Maryland</i>. In a unanimous decision, the Court finds that states cannot tax federal agencies. The ruling establishes a precedent of broad federal power, marking a blow to states' rights. </p>
<h2>1820/3/3</h2>"","",<p>After months of fierce debate, Congress agrees to the first Missouri Compromise, addressing congressional jurisdiction over the conditions of statehood. After Maine petitions Congress for statehood, the balance of free and slave states in Senate will be maintained with a free Maine and a slave Missouri. The Compromise also addresses all land in the Louisiana Purchase territory and establishes that land north of the 36 degree, 30' line—with the exception of Missouri—will be free, while territory below the line will be slave. In February 1821, Congress admits Maine and Missouri as states, formalizing the Missouri Compromise. Henry Clay, "the Great Pacificator," is by and large the architect of the Compromise. </p>
<h2>1820/3/15</h2>"","",<p>Maine is admitted as the twenty-third state of the Union. </p>
<h2>1820/12/6</h2>"","",<p>As expected, Monroe secures reelection as President of the United States, receiving 231 electoral votes to John Quincy Adams's 1. Vice President Tompkins will also serve a second term.   </p>
<h2>1821/3/2</h2>"","",<p>Monroe signs the Military Establishment Act, forwarded by Secretary of War Calhoun, to reduce the Army's manpower by 40 percent to 6,126 men. The move reflects a shift in national priorities toward commerce and negotiation, and away from intimidation, as the primary tool of foreign policy. </p>
<h2>1821/3/5</h2>"","",<p>Monroe begins his second presidential term. </p>
<h2>1821/8/10</h2>"","",<p>Missouri is admitted as the twenty-fourth state of the Union. </p>
<h2>1823/8/20</h2>"","",<p>In a letter to Richard Rush, British foreign secretary George Canning discreetly contemplates recognition of what is referred to as the "no-transfer" principle advocated by the United States. This proposal requires European powers to abstain from exchanging colonies or acquiring new possessions from Spain. </p>
<h2>1823/12/2</h2>"","",<p>In his annual address to Congress, Monroe formally articulates the foreign policy position that becomes known as the "Monroe Doctrine." It meets with widespread approval and political consent. Monroe's repudiation of further American hemispheric colonization speaks to the claims of Britain and Russia, as well as Spain. The enunciation of American exclusivity and European non-interference is a seminal event in United States foreign policy. </p>
<h2>1824/1/1</h2>"","Month",<p>Cherokee chiefs arrive in Washington, D.C., to object to the government's removal policies and plead for their sovereign right to stay in Georgia. Originally siding with the Cherokee, Monroe will later reverse his stance on the issue. </p>
<h2>1824/4/30</h2>"","",<p>Monroe signs the General Survey Bill, departing from his opposition to congressionally sponsored internal improvements. The United States Army Corps of Engineers prepare to produce surveys, plans, and estimates to improve navigation. Monroe subsequently purchases 1,500 shares of stock in the Chesapeake and Delaware Canal Co. for $300,000. </p>
<h2>1824/5/22</h2>"","",<p>Monroe signs the Tariff of 1824 into law, implementing protectionist measures in support of local manufactures and goods. Complaints arise in the South with cotton-growers fearful of British retaliation for the increase in price. Northern manufacturers are pleased with the law. </p>
<h2>1824/8/15</h2>"","",<p>Following Congress's invitation, the Marquis de Lafayette, the inspirational liberal French philosopher, makes a lengthy visit to the United States. The visit commands national attention in the press and host cities for months. </p>
<h2>1824/11/1</h2>"","Month",<p>At sixty-seven, Monroe decides not to seek re-election in the presidential race -- a contest that is far more contentious than the previous one. Henry Clay, William Crawford, John Quincy Adams, Andrew Jackson, and John C. Calhoun initially vie for nominations. </p>
<h2>1825/1/1</h2>"","Month",<p>Unable to alter the demands of the Georgia congressional delegation, Monroe concedes that the only way to mitigate Indian concerns is through their removal west of the Mississippi. This position conflicts with his earlier recognition of Cherokee claims. </p>
<h2>1825/3/3</h2>"","",<p>In his last day in office, Monroe vetoes the Cumberland Road bill, which would extend construction of the interstate artery to Zanesville, Ohio. Monroe is concerned about the bill's constitutionality. Construction of the first federally financed interstate road began under Jefferson in 1811 and will continue under Adams's administration. </p>
<h2>1825/3/4</h2>"","",<p>John Quincy Adams is sworn in as the sixth president of the United States. </p>  
