
<h2>1 6, 1853</h2>"",""<p>Two months before taking office as President, Franklin Pierce and his family are struck by tragedy. A train wreck kills the Pierces' eleven-year-old son, Benjamin, the only surviving child of his marriage. Jane Pierce, already unhappy with the prospect of moving to Washington, interprets the death as a condemnation of her husband's decision to be President and becomes a recluse. President Pierce, meanwhile, is grief and guilt-stricken when he enters office. </p>
<h2>3 4, 1853</h2>"",""<p>Franklin Pierce is inaugurated as the nation's fourteenth President. His inaugural speech alludes to the need for additional lands to enhance U.S. security -- a pledge which angers Northerners who charge that Pierce is bowing to Southern desires to expand slavery. </p>
<h2>12 30, 1853</h2>"",""<p>The Gadsden Purchase, negotiated by James Gadsden, U.S. minister to Mexico, is signed. At the cost of $15 million, the United States acquires more than 29,600 square miles of new territory in southwest Arizona and New Mexico. The purchase establishes the final boundaries of the United States and, by providing a strip of land to the Pacific Ocean, will be used a route for the Southern Pacific Railroad. </p>
  <p>Fernando Wood wins the New York City mayoral race, becoming the first boss of Tammany Hall to fill the position. Under the leadership of Wood, Tammany Hall has become the dominant force in the life of New York City politics. Formed in 1786, the Tammany Society evolves to uphold Jeffersonian politics in the city. In the late 1840s, the political organization enjoys success over the local Know-Nothing and Whig parties through its affiliation with numerous immigrants. Its programs and services provide new Americans with food, employment, and protection. In return, the party's constituents overlook Tammany's fraudulent elections and other corrupt practices. </p>
<h2>3 31, 1854</h2>"",""<p>After nearly three centuries of Japanese isolation, Commodore Matthew Perry -- first ordered to Japan by President Fillmore -- signs the Treaty of Kanagawa, marking the beginning of the Pacific nation's trade with the rest of the world. The United States is permitted a consulate in Japan, and U.S. ships will be allowed to sail into Japanese ports for the purpose of conducting limited trade. </p>  
<h2>4 26, 1854</h2>"",""<p>The Massachusetts Emigrant Aid Society is founded by Eli Thayer to encourage opponents of slavery to move to Kansas. Thayer, who becomes a U.S. Congressman (Republican) from 1857 to 1861, establishes the society while serving in the state legislature. On February 21, 1855, the society is renamed the New England Emigrant Aid Society. </p>
<h2>5 </h2>"",""<p>The Kansas-Nebraska Act is signed into law after being introduced by President Pierce's rival, Senator Stephen Douglas (Democrat - IL). The bill reopens the question of slavery in the West by repealing the Missouri Compromise of 1820, organizes the Kansas and Nebraska territories on the basis of "popular sovereignty," and paves the way for the transcontinental railroad from Chicago to California. Although Pierce dislikes the proposal and worries that it will create national controversy, he succumbs to pressure from various senators who threaten to block appointments. </p>
<h2>6 5, 1854</h2>"",""<p>The Canadian Reciprocity Treaty opens the U.S. market to Canadian agricultural products, including timber and fish. In return, the United States gets new commercial rights in Canadian waters and on the Great Lakes. </p>
<h2>7 6, 1854</h2>"",""<p>Coinciding with the further disintegration of the Whig Party, the Republican Party is founded in Jackson, Michigan. Its membership is composed of Whigs, Free-Soilers, and northern Democrats angry at the passage of the Kansas-Nebraska Act, specifically, and concerned with the prospect of expanding slavery. </p>
<h2>10 18, 1854</h2>"",""<p>The Ostend Manifesto written by Pierre Soule, U.S. minister to Spain, suggests that the United States threaten to invade Cuba if Spain is not willing to sell the island to the United States. Soule's brash diplomacy in Spain dashes Pierce's hopes to annex Cuba, a goal supported by Southerners who viewed the island as a location where slavery might flourish. The State Department disavows any connection to the document and forces Soule's resignation later that year. Future President James Buchanan is one of three signers of the Manifesto. </p>
  <p>In congressional elections, the Whigs continue to decline in power while Democrats also suffer losses. The fledging Republican Party has yet to prove its ability to contest the Democrats but boasts impressive gains through cooperation with the American Party. Forty-four Republicans are elected to the House of Representatives. </p>
<h2>1854</h2>"1856",""<p> "Bleeding Kansas" --  a guerilla war between pro-slavery and anti-slavery settlers as they attempt to establish "popular sovereignty" --  emerges and consumes Kansas for two years. </p>  
<h2>2 10, 1855</h2>"",""<p>Nationality laws are changed so that all children born abroad to U.S. parents are guaranteed American citizenship. </p>
<h2>6 5, 1855</h2>"",""<p>The Native American Party, or Know-Nothing Party, becomes the American Party. </p>
<h2>9 5, 1855</h2>"",""<p>Antislavery settlers in Kansas form an army -- entitled the Free State forces -- with munitions from Northern states. Abolitionist John Brown follows five of his sons to the territory to lead the group. </p>
<h2>10 23, 1855</h2>"",""<p>In response to the pro-slavery territorial government and its illegal political proceedings, the Topeka Constitution, written by Free State forces and outlawing slavery, creates a second government in Kansas. </p>
<h2>11 26, 1855</h2>"",""<p>The Wakarusa War threatens Lawrence, Kansas. Fifteen hundred Border Ruffians attack the town, only to retreat after finding it defended by Free State forces. Lawrence -- originally named Wakarusa -- becomes the center of Free-State activities after being founded by the Massachusetts Emigrant Aid Society. </p>
<h2>2 22, 1856</h2>"",""<p>The Republican Party holds its first national meeting in Pittsburgh, Pennsylvania. The American Party, or Know-Nothing Party, meets in Philadelphia to nominate former President Millard Fillmore for President in the upcoming election. </p>
<h2>5 </h2>"",""<p>Pro-slavery forces and Border Ruffians, including Sheriff Jones of Douglas County and his followers, lead another attack on Lawrence, Kansas. One person dies as the band burns a hotel and two newspaper offices. </p>
<h2>5 </h2>"",""<p>The Sumner-Brooks Affair occurs, in which cane-wielding Representative Preston Brooks (D-SC) attacks abolitionist Senator Charles Sumner (R-MA) on the Senate floor. The fight is provoked by conversation and derogatory remarks made two days earlier during the Senate debate on the admission of Kansas. Following the beating, Brooks is arrested and fined $500; he subsequently resigns (although he will be re-elected). Sumner suffers severe injuries, taking three years to recover from the beating. </p> 
<h2>5 </h2>"",""<p>In retaliation for the pro-slavery raid on Lawrence, Kansas, John Brown and several followers massacre five unarmed, pro-slavery Kansans along the Pottawatomie Creek. </p>
<h2>6 2, 1856</h2>"",""<p>The anti-slavery section of the Know-Nothing Party nominates John C. Fr&eacute;mont for President and W.F. Johnston for vice president. </p>
<h2>6 2, 1856</h2>"6 5, 1856",""<p>The Democratic National Convention nominates James Buchanan of Pennsylvania for President and John Breckinridge of Kentucky for vice president. Although Pierce desires a second term, his party refuses to nominate him, unhappy with his performance. Such a denial to a United States President is without precedent. </p>
<h2>6 17, 1856</h2>"6 19, 1856",""<p>The Republican National Convention nominates California senator John C. Fr&eacute;mont for President and William L. Dayton for vice president. </p>
<h2>8 1, 1856</h2>"",""<p> "Bleeding Kansas" continues to rage without a settled government. Raids persist, with 200 dead and $2 million in property lost during the two years of strife. From August 24-26, 1856, an army of 400 to 600 hundred pro-slavery Missourians attack John Brown and 40 defenders. In the Battle of Osawatomie, the settlement (all but four homes) is burned by the invaders and John Brown's son Frederick is killed. Four wagonloads of dead and wounded are brought to Booneville, Missouri, when the invading army returns. </p>
<h2>9 17, 1856</h2>"",""<p>The Whig National Convention nominates Millard Fillmore (also chosen by the pro-slavery contingent of the Know-Nothing Party) for President and Andrew J. Donelson for vice president. </p>
<h2>11 4, 1856</h2>"",""<p>James Buchanan is elected President of the United States, with John Breckinridge winning the vice presidency. The Democrats defeat Republican candidate John C. Fr&eacute;mont, even though Fr&eacute;mont wins 11 of 31 states -- all in the North -- and Millard Fillmore, who runs on both the Whig and Know-Nothing tickets. Although Buchanan's electoral college returns are strong, the new President carries only 45.3 percent of the popular vote and wins only four of fourteen Northern states. </p>
 
<h2>1 15, 1857</h2>"",""<p>The State of Disunion Convention, contemplating the peaceful separation of  North and South, is held in Worcester, Massachusetts. The Massachusetts Emigrant Aid Society supports this gathering. William Lloyd Garrison delivers a speech avowing "No union with slaveholders." </p> 
<h2>2 21, 1857</h2>"",""<p>Congress declares that foreign coins are no longer considered legal tender in the United States. </p>
<h2>3 4, 1857</h2>"",""<p>James Buchanan is inaugurated as the fifteen President of the United States. </p>
