
"1845/03/04","","Day","James K. Polk is inaugurated as the eleventh President of the United States."
"1845/06/25","","Day","General Zachary Taylor receives orders from Polk to move his troops from Fort Jesup in Louisiana to a position "on or near the Rio Grande" in Texas to discourage a Mexican invasion."
"1845/07/01","","Month","New York Jacksonian Democrat, John L. O'Sullivan, accuses opponents of Texas annexation of "limiting our greatness and checking the fulfillment of our manifest destiny to overspread the continent allotted by Providence for the free development of our yearly multiplying millions."  The term, "Manifest Destiny," quickly becomes the label used to encapsulate the belief among Americans in their country's God-given right to expand its territory and institutions."
"1845/10/10","","Day","Under the direction of Secretary of the Navy George Bancroft, the Naval Academy opens at Annapolis, Maryland."
"1845/12/29","","Day","Texas is admitted as a slave state, making it the twenty-eighth state in the Union."
"1845/01/01","1846/12/31","Year","The great Irish potato famine forces huge waves of starving immigrants to the United States, sparking anti-Catholic, nativist backlashes."
"1846/02/04","","Day","The Mormon migration to Utah, led by Brigham Young, begins. "
"1846/05/13","","Day","Congress declares war on Mexico after American troops, under General Zachary Taylor, clash with Mexican troops on the north bank of the Rio Grande. "
"1846/06/14","","Day","In the Bear Flag Revolt, approximately thirty American settlers (anticipating the Mexican War) take over a small Mexican garrison in Sonoma, California, and declare California a free and independent republic. "
"1846/06/15","","Day","The Oregon Treaty establishes the 49th parallel as the border between British and American claims to the Oregon Territory, granting the United States clear title to present-day Idaho, Washington, Oregon, and Montana, while granting to Britain territory above the 49th parallel and full control over Vancouver Island. "
"1846/07/29","","Day","Congress passes the Tariff of 1846, a key part of President's Polk's domestic agenda. Known as the "Walker Tariff," after Polk's secretary of the Treasury, Robert J. Walker, the Tariff of 1846 lowers rates toward revenue-only levels, although a few items remain protected."
"1846/08/03","","Day","President Polk vetoes a river and harbors bill which would have provided for federally funded internal improvements. Like Andrew Jackson in his veto of the Maysville Road bill, Polk argues that the bill unfairly favors particular areas, including ports which have no foreign trade. Therefore, says Polk, the bill is unconstitutional."
"1846/08/06","","Day","President Polk signs into law the Independent Treasury, which he calls a "Constitutional Treasury," an integral part of his domestic agenda."
"1846/08/10","","Day","Congress establishes the Smithsonian Institution. "
"1846/11/01","","Month","The Whigs regain a majority of seats in the House of Representatives. "
"1846/12/28","","Day","Iowa is admitted as a free state, making it the twenty-ninth state in the Union."
"1847/02/22","1847/02/23","Day","General Zachary Taylor defeats the Mexicans under General Santa Anna at the Battle of Buena Vista. Taylor's victory cements his growing acclaim as a national hero and helps propel him to the 1848 Whig nomination for President. "
"1847/07/22","","Day","The first Mormon settlers arrive in the Salt Lake Valley. "
"1847/09/14","","Day"," General Winfield Scott takes Mexico City, adding pressure to the Mexican government to submit to the demands of President Polk and sign a treaty of peace. "
"1848/01/24","","Day"," James Marshall discovers gold near Sacramento, California. The discovery begins the massive migrations of the California gold rush, allowing the territory to become a state and setting off fierce debates over whether to admit California as a free or slave state. "
"1848/02/02","","Day","The Treaty of Guadalupe Hidalgo ends the Mexican War and grants the United States vast territories, including all or large parts of present-day California, Arizona, New Mexico, Colorado, Nevada, Utah, and Wyoming, and confirms the incorporation of Texas as part of the United States. The acquisition of these lands aggravates growing sectionalism in the country over the future of slavery in the Union. "
"1848/05/29","","Day","Wisconsin is admitted as a free state, making it the thirtieth state in the Union. "
"1848/07/12","1848/07/20","Day","Elizabeth Cady Stanton and Lucretia Mott hold a women's rights convention in Seneca Falls, New York. Among other demands, the convention&rsquo;s "Declaration of Sentiments" calls for women's suffrage."
"1848/11/07","","Day","Zachary Taylor is elected the twelfth President of the United States. "
"1848/11/01","","Month","Democrats regain a majority of seats in the House of Representatives. "
"1849/03/03","","Day","The United States Department of Interior is created. It combines the General Land Office, the Bureau of Indian Affairs, the Pension Office, the Bureau of the Census, and the Patent Office into a single department. "
"1849/03/05","","Day","Zachary Taylor is inaugurated as the twelfth President of the United States, and Polk begins a goodwill tour of the South that will eventually end in Tennessee."
