 
				
<h2>9 14, 1901</h2>"","",<p>Vice President Theodore Roosevelt (TR) takes the oath of office in Buffalo, New York, after President William McKinley is assassinated. Roosevelt becomes the twenty-sixth President of the United States and the youngest President yet at 43 years old. Roosevelt's succession appalls Republicans who blanched at his liberal leanings; TR was nominated for the vice presidency in 1900 partly because Republican leaders were attempting to relegate him to a harmless position.</p>
<h2>10 16, 1901</h2>"","",<p>TR dines with Booker T. Washington at the White House.</p>
<h2>11 18, 1901</h2>"","",<p>The United States and Great Britain sign the Hay-Pauncefote Treaty, by which the British grant control of an isthmian canal to the United States. The Senate would ratify Hay-Pauncefote on December 16, thereby abrogating the Clayton-Bulwer Treaty of 1850.</p>
<h2>4 29, 1902</h2>"","",<p>Congress extends the Chinese Exclusion Act, prohibiting the immigration of Chinese laborers from the Philippines.</p>
<h2>5 12, 1902</h2>"","",<p>A coal-miners strike begins in Pennsylvania, during the course of which 140,000 workers would leave their jobs. </p>
<h2>5 22, 1902</h2>"","",<p>The President establishes Crater Lake National Park in Oregon. </p>
<h2>6 17, 1902</h2>"","",<p>TR signs the Newlands Reclamation Act, thereby authorizing federal irrigation projects. </p>
<h2>6 28, 1902</h2>"","",<p>Congress passes the Isthmian Canal Act, which called for the funding and building of a canal across the Isthmus of Panama. </p>
<h2>7 1, 1902</h2>"","",<p>Congress passes the Philippine Government Act, establishing the Philippine Islands as an unorganized territory and all inhabitants as territorial citizens. </p>
<h2>9 2, 1902</h2>"","",<p>While emphasizing the need for a strong foreign policy, Roosevelt talks of the need to "Speak softly and carry a big stick." The saying catches the fancy of the whole nation, and the "big stick" becomes a favorite object of political cartoonists. </p>
<h2>10 , 1902</h2>"","",<p>TR plays a key role in settling the Anthracite Coal Strike. During the spring of 1902, laborers tied to the United Mine Workers union had walked off the job in the hard coal mines of Pennsylvania. The prospect of coal shortages in the winter months loomed, and TR decided that public interest demanded vigorous executive action.  Roosevelt summoned union leaders and mine operators to the White House, a significant gesture for both his presidency and for the development of his reform program, known as the "Square Deal." The coal strike ended on October 21. </p>
<h2>11 4, 1902</h2>"","",<p>In congressional elections, the Republicans maintain a majority in the Senate, 57 to 33. In the House, the Republicans emerge with a 208-178 majority. </p>
<h2>2 14, 1903</h2>"","",<p>Roosevelt signs a bill creating the Department of Commerce and Labor, the ninth Cabinet office, which will itself emerge as two separate departments in 1913.
<h2>2 19, 1903</h2>"","",<p>Congress approves the Elkins Anti-Rebate Act, making it illegal for railroads to give rebates on their published freight rates. The Elkins Act is a response to railroads engaging in business practices that gave certain shippers and certain areas a marked advantage. It would fall short of regulating railroads sufficiently; the Hepburn Act would have to be instituted three years later to further that cause. </p>
<h2>2 19, 1903</h2>"","",<p>The Department of Justice announces that the federal government would prosecute the Northern Securities Company (a subsidiary of J.P. Morgan) for violating the Sherman Antitrust Act. </p>
<h2>2 23, 1903</h2>"","",<p>The Supreme Court hands down a decision in <i>Champion v. Ames</i>, making federal police power superior to that of the states. The ruling became the basis for the future federal regulation of food, drugs, and narcotics. </p>
<h2>3 14, 1903</h2>"","",<p>Roosevelt proclaims Pelican Island, Florida, as the first federal bird reservation. </p>
<h2>3 18, 1903</h2>"","",<p>The Report of the Anthracite Coal Strike Commission, appointed by TR to investigate the mining industry, declares that workers cannot be discriminated against because they belong to a union. </p>
<h2>11 3, 1903</h2>"","",<p>A revolt breaks out in Panama against Colombian rule. The uprising is sponsored by Panamanian agents and officers of the Panama Canal Company, with tacit permission of the Roosevelt administration. The presence of the American Navy prevents Colombia from crushing the revolt. </p>
<h2>11 6, 1903</h2>"","",<p>The United States recognizes the Republic of Panama. </p>
<h2>11 18, 1903</h2>"","",<p>The United States negotiates the Hay-Buneau-Varilla Treaty with Panama to build the Panama Canal. The treaty gives the United States control of a ten-mile-wide canal zone in return for $10,000,000 in gold plus a yearly fee of $250,000. </p>
<h2>1 4, 1904</h2>"","",<p>The Supreme Court rules that citizens of Puerto Rico are not aliens and therefore cannot be denied entry to the continental United States. But the Court also holds that they are not U.S. citizens. </p>
<h2>2 29, 1904</h2>"","",<p>TR appoints the Panama Canal Commission to oversee the construction of the Panama Canal.</p>
<h2>3 14, 1904</h2>"","",<p>In accordance with the Sherman Anti-Trust Act, the Supreme Court, in <i>Northern Securities Company v. United States</i>, orders the dissolution of the Northern Securities Company. The decision is major victory for TR and his belief in the necessity of trust-busting.</p>
<h2>6 21, 1904</h2>"6 23, 1904","",<p>The Republican Party nominates Roosevelt for the presidency, along with Charles Fairbanks as his vice presidential running mate. </p>
<h2>7 6, 1904</h2>"7 9, 1904","",<p>The Democratic Party nominates Alton B. Parker of New York for the presidency and Thomas Tibbles for the vice presidency. </p>
<h2>10 19, 1904</h2>"","",<p>A merger between the Consolidated and the American & Continental tobacco companies produces the American Tobacco Company. </p>
<h2>11 8, 1904</h2>"","",<p>TR wins the presidential election, trouncing Democratic candidate Alton B. Parker, 336 electoral votes to 140. With the exception of Maryland, Roosevelt wins every state north of Washington, D.C., including all Midwestern and Western states; Parker sweeps the South and Texas. In the Senate, the Republicans maintain their 57 to 33 advantage, while in the House, they gain 43 seats, for a 250-136 majority. Roosevelt vows to not seek another presidential term in order to deflect Democratic charges that he would remain in office for life. </p>
<h2>12 6, 1904</h2>"","",<p>In his annual message to Congress, the President issues the "Roosevelt Corollary" to the Monroe Doctrine. Roosevelt augments the justification for U.S. intervention in the Western Hemisphere "in flagrant cases of wrongdoing or impotence," arguing that America might be obliged to carry out "the exercise of an international police power." </p>
<h2>1 21, 1905</h2>"","",<p>The United States signs a protocol with the Dominican Republic, thereby giving it control of the latter's customs and international in and mollifying European creditors. Though the Senate refuses to ratify this agreement, Roosevelt makes a temporary arrangement with the republic to undertake the newly envisioned "Roosevelt Corollary." </p>
<h2>2 1, 1905</h2>"","",<p>Roosevelt establishes the National Forest Service. </p>
<h2>2 20, 1905</h2>"","",<p>In <i>Jacobson v. Massachusetts</i>, the Supreme Court recognizes the legality of compulsory vaccination laws. </p>
<h2>3 4, 1905</h2>"","",<p>Roosevelt is inaugurated for his first full term as President of the United States. Also sworn in is Vice President Charles W. Fairbanks. </p>
<h2>4 17, 1905</h2>"","",<p>In <i>Lochner v. New York</i>, the Supreme Court rules that state laws limiting working hours are illegal. </p>
<h2>7 7, 1905</h2>"","",<p>The Industrial Workers of the World (IWW) forms in Chicago, Illinois, to counteract the conservative American Federation of Labor. </p>
<h2>7 11, 1905</h2>"7 13, 1905","",<p>A group of black intellectuals, including W.E.B. DuBois, meets near Niagara Falls to demand racial equality. This begins the Niagara Movement, a forerunner of the National Association for the Advancement of Colored People (NAACP). </p>
<h2>9 5, 1905</h2>"","",<p>Russia and Japan sign the Portsmouth Treaty, ending the Russo-Japanese War. Roosevelt played a significant role in mediating this conflict, urging an end to hostilities and brining both sides to the conference table in Portsmouth, N.H. For his actions, Roosevelt would win the 1906 Nobel Peace Prize. The treaty also allowed the United States to maintain a balance of power in the Far East while preserving an Open Door Policy in China. </p>
<h2>1 16, 1906</h2>"","",<p>The Algeciras Conference opens, with TR hoping to mediate a disagreement between France and Germany over Morocco.</p>
<h2>4 13, 1906</h2>"","",<p>Clashes erupt in Brownsville, Texas, after white civilians taunt black soldiers. Three whites are killed. </p>
<h2>4 18, 1906</h2>"","",<p>A devastating earthquake strikes San Francisco, California, killing 452 and leveling 490 blocks. </p>
<h2>6 8, 1906</h2>"","",<p>Roosevelt signs the National Monuments Act, establishing the first eighteen national monuments, including Devils Tower, Muir Woods, and Mount Olympus. </p>
<h2>6 29, 1906</h2>"","",<p>TR signs the Hepburn Act, which gives the Interstate Commerce Commission increased power to regulate railroad rates. Roosevelt's leadership is key for the passage of this act, as many observers claim the act would have not come out of the Senate without TR's advocacy. </p>
<h2>6 30, 1906</h2>"","",<p>Roosevelt signs the Meat Inspection Act and the Pure Food and Drug Act. The legislation calls for both an honest statement of food content on labels and for federal inspection of all plants engaging in interstate commerce. The major impetus for these measures was <i>The Jungle</i>, the scathing report on meatpacking plants written by muckraking journalist Upton Sinclair, which TR personally read. </p>
<h2>8 23, 1906</h2>"","",<p>Cuban President Tom·s Palma asks Roosevelt to send American troops to Cuba to quell a rebellion which arose from a disputed election. TR demurs at first, but sends troops in October. </p>
<h2>9 22, 1906</h2>"9 24, 1906","",<p>A race riot in Atlanta, Georgia, leaves twenty-one people dead, including eighteen blacks. </p>
<h2>9 29, 1906</h2>"","",<p>The Platt Amendment is invoked, authorizing U.S. military control of Cuba.  Future President William Howard Taft serves as provisional governor. </p>
<h2>11 6, 1906</h2>"","",<p>The Republicans gain four seats in the Senate, for a 61 to 31 majority. In the House, the Republicans lose 28 seats, but maintain a 222-164 advantage. The national labor movement became involved in these elections, thereby marking a turning point in the history of national elections. Samuel Gompers and the American Federation of Labor had issued "Labor's Bill of Rights," asking both parties to support the program. When Republicans declined to do so, the AFL backed the Democrats, who claimed to be the "First to Recognize Organized Labor." </p>
<h2>11 9, 1906</h2>"11 26, 1906","",<p>The President and Mrs. Roosevelt go to Panama to inspect the building of the Panama Canal, marking the first trip abroad by a sitting American President. </p>
<h2>12 10, 1906</h2>"","",<p>The Nobel Prize Committee awards Roosevelt its Peace Prize for his role in ending the Russo-Japanese War during the Portsmouth Conference in 1905. </p>
<h2>12 12, 1906</h2>"","",<p>TR appoints Oscar Straus of New York City to head the Commerce and Labor Department. Straus is the first Jew to hold a cabinet post. </p>
<h2>1 26, 1907</h2>"","",<p>Congress passes a law prohibiting campaign contributions to candidates for national office.</p>
<h2>2 8, 1907</h2>"","",<p>The Dominican Republic and the United States sign a treaty empowering American agents to collect Dominican customs taxes for the purpose of satisfying the nation's creditors. The Senate ratifies the treaty on February 25; in 1905, it had refused to ratify a similar agreement. </p>
<h2>2 20, 1907</h2>"","",<p>TR signs the Immigration Act of 1907, which includes a provision allowing the President to restrict Japanese immigration. The issue had been a matter of great debate during TR's tenure, and Roosevelt proclaimed in his 1905 State of the Union address, that "probably a very large proportion, including most of the undesirable class [of immigrants], does not come here of its own initiative, but because of the activity of the agents of the great transportation companiesÖthey wheedle and cajole many immigrants, often against their best interest, to come here." </p>
<h2>3 2, 1907</h2>"","",<p>To get around restrictive language in an appropriation bill inhibiting the creation of new forest reserves in six Western states, TR issues proclamations establishing forest reserves in affected states before the law goes into effect. In doing so, TR faced down Westerners who disdained interference from Washington. </p>
<h2>3 14, 1907</h2>"","",<p>An executive Inland Waterways Commission is appointed to study the relationship between forest preservation and commercial waterways. </p>
<h2>3 21, 1907</h2>"","",<p>U.S. Marines land in Honduras to protect life and property during a series of political disturbances. </p>
<h2>6 15, 1907</h2>"","",<p>The Second International Peace Conference opens at The Hague, The Netherlands. The United States argues, unsuccessfully, for the establishment of a World Court. </p>
<h2>10 22, 1907</h2>"","",<p>The Panic of 1907 begins when shares of the United Copper Company begin to fluctuate wildly. Rumors spread like wildfire about the Kinckerbocker Trust Company, which triggered a run on several New York Banks. Panic sets in, destabilizing the jerry-built foundation of the American banking system. </p>
<h2>10 23, 1907</h2>"","",<p>TR returns to Washington from a hunting trip to deal with Secretary of the Treasury Cortelyou and shore up fears of a financial crash. Although $68 million dollars is distributed, the government's response fails to calm fears about a possible depression. </p>
<h2>11 16, 1907</h2>"","",<p>Oklahoma is admitted to the Union as the 46th state. </p>
<h2>12 16, 1907</h2>"","",<p>Under Roosevelt's orders, the Great White Fleet (so named because of the boats' color) embarks on a voyage around the world from Hampton Roads, Virginia. The fleet returns triumphantly on February 22, 1909, having been enthusiastically welcomed at many ports and underscoring America's growing naval strength. The voyage would serve as Roosevelt's proudest accomplishment while in office. </p>
<h2>2 3, 1908</h2>"","",<p>In <i>Loewe v. Lawlor</i>, the Supreme Court rules that antitrust law applies to labor unions.</p>
<h2>2 18, 1908</h2>"","",<p>The United States and Japan reach an agreement on the restriction of Japanese immigration. The Japanese government agrees not to issue any more visas permitting Japanese laborers to emigrate to the United States. </p>
<h2>5 13, 1908</h2>"5 15, 1908","",<p>At the White House, the first Conference of Governors meets to discuss the problems of conservation. </p>
<h2>5 28, 1908</h2>"","",<p>Congress passes a child labor law for the District of Columbia. </p>
<h2>6 8, 1908</h2>"","",<p>Roosevelt establishes the National Commission for the Conservation of Natural Resources, headed by Gifford Pinchot. </p>
<h2>6 16, 1908</h2>"6 20, 1908","",<p>The Republican Party nominates William Howard Taft for the presidency and James Sherman for the vice-presidency. Republicans were far from united in their support for Taft; party chairman Henry Cabot Lodge speaks in praise of President Roosevelt, touching off a forty-five minute demonstration among the delegates. </p>
<h2>7 7, 1908</h2>"7 10, 1908","",<p>William Jennings Bryan wins the Democratic nomination for the presidency, with John Kern as his vice-president running mate.  Bryan had lost much of the glamour in this, his third run for the office. </p>
<h2>9 16, 1908</h2>"","",<p>The General Motors Company files incorporation papers in Hudson County, New Jersey. </p>
<h2>10 1, 1908</h2>"","",<p>Ford introduces the "Model T" automobile, which costs $850, making Henry Ford's mass-produced cars available to the average wage earner. </p>
<h2>11 3, 1908</h2>"","",<p>William Howard Taft is elected President over Democrat William Jennings Bryan. Running for his third and last shot at the presidency, Bryan garners 162 electoral votes, far behind Taft's winning total of 321. Taft sweeps the Northeast and the Midwest, while Bryan wins every state south of the Mason-Dixon line. The Democrats gain one seat in the Senate, but still trail the Republicans 61 to 32. In the House, the Republicans lose three seats but maintain a 219-172 advantage.	</p>
<h2>2 12, 1909</h2>"","",<p>Black intellectuals, including W.E.B. DuBois, and white progressives, led by Oswald Garrison Villard, form the National Association for the Advancement of Colored People (NAACP).</p>
<h2>2 18, 1909</h2>"","",<p>The North American Conservation Conference convenes at the White House. </p>
<h2>3 4, 1909</h2>"","",<p>Roosevelt's administration ends with the inauguration of William Howard Taft as the twenty-seventh President. Roosevelt leaves on a yearlong African safari in order to avoid charges that he was attempting to run the White House from the shadows. </p>
