
<h2>3 4, 1909</h2>"",""<p>William Howard Taft takes the oath of office, becoming the twenty-seventh President of the United States. Taft had been handpicked by his predecessor, Theodore Roosevelt, and trusted to carry through Theodore Roosevelt's progressivism. Not surprisingly, Taft makes many references to his "distinguished predecessor" in his inaugural address. Nevertheless, a newfound chill had arisen between the two men, mirroring the frigid temperatures in the capital that day.</p>
<h2>3 15, 1909</h2>"",""<p>A special session of the United States Congress convenes to consider revision of the tariff. On March 16, Taft sends a special message to Congress urging prompt revision of the tariff. </p>
<h2>4 6, 1909</h2>"",""<p>Robert E. Peary reaches the North Pole. </p>
<h2>5 </h2>"",""<p>Helen "Nellie' Taft suffers a stroke, leaving her speech impaired.  Her recovery lasts approximately one year. </p>
<h2>6 16, 1909</h2>"",""<p>Delivering a message to Congress, Taft proposes a two-percent tax on the net income of all corporations except banks, which he believes will make up for revenue lost by tariff reductions. He also proposes that Congress adopt a constitutional amendment that would permit the collection of personal federal income taxes. </p>
<h2>7 12, 1909</h2>"",""<p>The Senate passes a resolution calling for a sixteenth amendment to the Constitution, authorizing Congress to collect income taxes. </p>
<h2>7 15, 1909</h2>"",""<p>Taft cables the Chinese regent Prince Chun, requesting that China grant American investors a share of a loan that had been floated in Europe for the purposes of building a railroad in southern China.  The Chinese reluctantly grant the United States investment privileges. </p>  
<h2>8 6, 1909</h2>"",""<p>Taft signs the Payne-Aldrich Tariff Act, which establishes a Tariff Board and reduces the tariff. </p>
<h2>9 14, 1909</h2>"",""<p>President Taft begins a tour of the southern and western states of the United States. </p>
<h2>9 17, 1909</h2>"",""<p>While on a tour of the United States, Taft calls the Payne-Aldrich Act "the best" tariff bill ever passed by the Republican Party, leaving both Republican progressives and party regulars dismayed. </p>  
<h2>10 16, 1909</h2>"",""<p>Taft visits Mexican dictator Porfirio DÌaz at El Paso, Texas, and at Juarez, Mexico. </p>
<h2>11 10, 1909</h2>"",""<p>Taft returns from his trip across the United States, having made 259 speeches. An observer in Winona, MN comments about Taft, "I knew he was good natured but I never dreamed he was so dull." </p>  
<h2>11 13, 1909</h2>"",""<p>Louis Glavis, chief of the Field Division of the Department of the Interior, charges in <i>Collier's Weekly</i> magazine that Secretary of the Interior Richard Ballinger conspired to defraud the public domain in the Alaskan coal fields ñ and that the Taft administration was complicit in Ballinger's wrongdoing. </p>
<h2>11 18, 1909</h2>"",""<p>Taft orders two U.S. warships to Nicaragua in response to the deaths of 500 revolutionaries, and two of their American advisors, at the hands of Nicaragua dictator JosÈ Santos Zelaya. The further threat of American force convinces Zelaya to retire on December 16. </p>
<h2>11 20, 1909</h2>"",""<p>Special government prosecutor Frank Kellogg wins a Court of Appeals case against Standard Oil, which is ruled a monopoly and in violation of the Sherman Anti-Trust Act. </p>
<h2>12 20, 1909</h2>"",""<p>Taft appoints General Leonard Wood as Chief of Staff of the Army. He also elevates circuit judge Horace H. Lurton to the Supreme Court. </p>
<h2>1 7, 1910</h2>"",""<p>Taft fires Gifford Pinchot, head of the United States Forest Serviceóa leading conservationist and one of the most recognizable officials in the federal governmentóupon release of a letter Pinchot had written to Senator Dolliver of Iowa on behalf of two of his employees implicated in the <i>Glavis</i> case. </p>
<h2>2 , 1910</h2>"",""<p>Secretary of State Philander Knox tours Central and South America on a good-will mission. </p>
<h2>3 19, 1910</h2>"",""<p>Representative George Norris, a progressive Republican from Nebraska, wins a major procedural victory in the House of Representatives when that body approves a plan by which the members of the House Rules Committee would be elected by the full House, rather than appointed by the Speaker of the House.  This represented a major defeat for Speaker "Uncle Joe" Cannon (R-IL), a leading opponent of the progressives. </p>
<h2>4 25, 1910</h2>"",""<p>President Taft appoints Governor Charles E. Hughes of New York to the Supreme Court. </p>
<h2>5 </h2>"",""<p>At a congressional investigation into the Glavis-Ballinger dispute, attorney Louis Brandeis, representing Glavis, reveals damaging information about the Taft administration. Congress clears Ballinger and the Taft administration of any wrongdoing, however. </p>
<h2>5 </h2>"",""<p>Taft obtains an injunction to prevent western railroads from raising freight rates. Taft was a fervent anti-trust supporter whose unrelenting ant-itrust crusade outmatched even that of Teddy Roosevelt. </p>  
<h2>6 18, 1910</h2>"",""<p>Taft elects not to greet Theodore Roosevelt upon the latter's return from Africa, a move that widens the rift between the two men. </p>
<h2>6 20, 1910</h2>"",""<p>TR declines Taft's invitation to the White House but praises the President's progress on a number of fronts, including railroad legislation, a postal savings bill, and conservationism. </p>
<h2>6 25, 1910</h2>"",""<p>Taft signs the Postal Savings Bank Act, which allowed one bank in each state, under federal supervision, to give two percent interest on accounts under $500. </p>
<h2>6 25, 1910</h2>"",""<p>Congress passes the Mann Act, also known as the "white slave traffic act," which prohibits the interstate or international transport of women for "immoral purposes." </p>
<h2>8 31, 1910</h2>"",""<p>TR returns and delivers the most radical speech of his political career at Osawatomie, Kansas. In his "New Nationalism" speech, Roosevelt outlines a new role for the government in dealing with social issues. His program takes American progressivism in a new direction, endorsing conservation, control of trusts, labor protection, and a graduated income tax. It also embraces the growing conviction that the nation must address the plight of children, women, and the underprivileged. </p> 
<h2>9 5, 1910</h2>"",""<p>Taft rejects a proposed dinner, given by the National Conservation Congress, that would honor both himself and TR. </p>
<h2>9 7, 1910</h2>"",""<p>The International Court of Arbitration at The Hague settles a dispute between Britain and the United States over the Newfoundland fisheries. </p>
<h2>9 10, 1910</h2>"",""<p>Taft, in a letter to his brother, comments that Roosevelt "has proposed a program (ëNew Nationalism') which it is absolutely impossible to carry out except by a revision of the federal ConstitutionÖIn most of these speeches he has utterly ignored meÖHis attitude toward me is one that I find difficult to understand and explain." </p>
<h2>9 27, 1910</h2>"",""<p>At the New York State Republican Convention in Saratoga, New York, Taft supports Roosevelt's choice for governor of New York, Henry Stimson. </p>
<h2>9 29, 1910</h2>"",""<p>The National Urban League is formed in New York. Its mission is "to enable African Americans to secure economic self-reliance, parity and power and civil rights." </p>
<h2>11 , 1910</h2>"",""<p>Taft appoints Willis Van Devanter to the Supreme Court to replace Justice William Moody. </p>
<h2>11 8, 1910</h2>"",""<p>In congressional elections, Democrats win control of the House of Representatives for the first time since 1894, gaining a 228 to 162 to 1 majority. In the Senate, Republicans hold a 51 to 41 advantage. </p>
<h2>12 12, 1910</h2>"",""<p>Taft appoints Associate Justice Edward White as chief justice of the Supreme Court; in January, Taft would also appoint Joseph R. Lamar to the Supreme Court. </p>
<h2>1 21, 1911</h2>"",""<p>Wisconsin Senator Robert LaFollette establishes The National Progressive Republican League in Washington, D.C. </p>
<h2>2 7, 1911</h2>"",""<p>The United States and Great Britain sign a treaty guaranteeing the preservation and protection of pelagic fur seals in Bering Sea waters. </p>
<h2>3 2, 1911</h2>"",""<p>Taft appoints a commission to investigate postal rates for newspapers and magazines; its report helps to convince Congress that a recent rate increase was justified. </p>
<h2>3 25, 1911</h2>"",""<p>The Triangle Shirtwaist Company bursts into flames in Manhattan. Women who worked in very cramped and unsafe conditions stampeded toward inadequate exits; 146 women would die, some even leaping to the pavement hoping to survive. The tragedy highlights the need to provide social justice for immigrant sweatshop workers, and the New York legislature responds by undertaking remedial legislation to ensure better working conditions and provide fire safety measures. </p>
<h2>3 7, 1911</h2>"",""<p>Taft orders the mobilization of 20,000 American soldiers along the Mexican border after American ambassador to Mexico Henry Lane Wilson reports that the safety of Americans residing in Mexico may be endangered. </p>
<h2>3 7, 1911</h2>"",""<p>Taft appoints Walter Fisher, an ally of Gifford Pinchot, as Secretary of the Interior to replace Richard Ballinger, who resigned. </p>
<h2>3 16, 1911</h2>"",""<p>Taft appoints Henry Stimson secretary of war to replace Jacob Dickinson. </p>
<h2>5 </h2>"",""<p>The U.S. Supreme Court orders the dissolution of the Standard Oil Company. </p>
<h2>5 </h2>"",""<p>President Porfirio DÌaz of Mexico resigns. </p>
<h2>5 </h2>"",""<p>The Supreme Court finds the American Tobacco Company in violation of the Sherman Anti-trust Act and orders its dissolution. </p>
<h2>6 6, 1911</h2>"",""<p>The United States signs a treaty with Nicaragua which would have made that nation a U.S. protectorate. The Senate later rejects the treaty. </p>
<h2>6 17, 1911</h2>"",""<p>Senator Robert LaFollette, a progressive from Wisconsin, announces his candidacy for the Republican presidential nomination. </p>
<h2>7 26, 1911</h2>"",""<p>Taft signs the Canadian Tariff Reciprocity Agreement. </p>
<h2>8 3, 1911</h2>"",""<p>Taft signs general arbitration treaties with France and England.  Roosevelt, along with his friend and ally Senator Henry Cabot Lodge, lead the campaign in opposition to the treaties. </p>
<h2>8 17, 1911</h2>"",""<p>Taft vetoes tariff reductions on wool and woolen goods, arguing that the Tariff Board had not completed its investigation. </p>
<h2>Fall, 1911</h2>"",""<p>Taft tours the western United States to drum up support for his arbitration treaties with England and France. In March 1912, the Senate will approve the treaties, which are rejected by Britain and France. </p>
<h2>9 21, 1911</h2>"",""<p>In the Canadian parliamentary elections, reciprocity with the United States is defeated, killing the treaty signed earlier in the year by the United States and Canada. </p>
<h2>10 26, 1911</h2>"",""<p>Taft files suit against U.S. Steel for violating the Sherman Act. In papers filed for the suit, Taft alleges that Roosevelt in 1907 had mistakenly let U.S. Steel purchase the Tennessee Coal and Iron Company. This action damages the Taft-TR relationship irreparably.   </p>
<h2>11 6, 1911</h2>"",""<p>Francisco Madero, a wealthy landowner, assumes office after being elected President of Mexico. </p>
<h2>11 10, 1911</h2>"",""<p>Andrew Carnegie founds the Carnegie Corporation with an initial endowment of $125,000,000. </p>
<h2>1 6, 1912</h2>"",""<p>New Mexico is admitted as the forty-seventh state. </p>
<h2>1 17, 1912</h2>"",""<p>Taft urges the adoption of an annual federal budget. </p>
<h2>1 22, 1912</h2>"",""<p>American troops occupy Tientsin, China, to protect American interests from the Chinese Revolution. </p>
<h2>2 14, 1912</h2>"",""<p>Arizona is admitted as the forty-eighth state. </p>
<h2>2 20, 1912</h2>"",""<p>President Taft nominates Mahlon Pitney for a seat on the U.S. Supreme Court. Pitney is confirmed by the Senate and takes his oath on March 13. </p>
<h2>2 22, 1912</h2>"",""<p>Theodore Roosevelt announces that his "hat is in the ring" as a candidate for President. Taft and running mate James S. Sherman are re-nominated together, the first time that Republicans endorse a sitting President and vice president for the party ticket. </p>
<h2>3 14, 1912</h2>"",""<p>The Justice Department begins proceedings to halt the merger of the Southern Pacific and Union Pacific railroads. </p>
<h2>3 15, 1912</h2>"",""<p>Dr. Harvey Wiley, Head Chemist at the Department of Agriculture, resigns because of differences with Secretary of Agriculture James Wilson. Wiley was a chief proponent of safe food and drug laws. </p>
<h2>3 27, 1912</h2>"",""<p>Mrs. Taft plants the first of the Cherry Trees, given to the United States by Japan, along the Tidal Basin as a symbol of international friendship.  </p>
<h2>4 9, 1912</h2>"",""<p>Taft signs a bill authorizing the creation of the Children's Bureau in the Department of Commerce. The agency is charged with monitoring child welfare. </p>
<h2>4 14, 1912</h2>"",""<p>The British luxury liner <i>Titanic</i> sinks off the coast of Newfoundland. Taft's key aide, Archie Butt, perishes in the tragedy. </p>
<h2>4 15, 1912</h2>"",""<p>President Taft appoints Julia Lathrop head of the newly-created Children's Bureau. She is the highest ranking woman in the U.S. government. </p>
<h2>6 5, 1912</h2>"",""<p>American Marines land in Cuba to ensure order under the Platt Amendment. </p>
<h2>6 19, 1912</h2>"",""<p>Congress passes a labor law authorizing an eight-hour working day for all workers with federal contracts. </p>
<h2>6 18, 1912</h2>"6 22, 1912",""<p>Taft wins the Republican presidential nomination over Theodore Roosevelt. James Sherman is re-nominated for vice-president. The bitter primary campaign between TR and Taft featured a thorough discussion within the Republican Party on the issue of government regulation. </p>
<h2>7 2, 1912</h2>"",""<p>The Democratic Party nominates Governor Woodrow Wilson of New Jersey as its candidate for President. Thomas Marshall of Indiana is nominated as vice president. </p>
<h2>8 5, 1912</h2>"",""<p>TR is nominated for President by the Progressive (Bull Moose) Party. Hiram Johnson of California is nominated for vice president on the ticket. </p>
<h2>8 20, 1912</h2>"",""<p>U.S. battleships are sent to Nicaragua to protect American economic interests and rail lines. </p>
<h2>8 24, 1912</h2>"",""<p>Taft signs the Panama Canal Act, which exempts American coastwise shipping from paying tolls when transiting the Panama Canal. Many Americans, as well as Britons, consider this a violation of the Hay-Pauncefote Treaty of 1901. </p>
<h2>9 24, 1912</h2>"",""<p>U.S. Marines are sent to restore order in Santo Domingo. </p>
<h2>10 30, 1912</h2>"",""<p>Vice President John Sherman dies, and Nicholas Butler, the president of Columbia University, replaces him on the Republican presidential ticket. </p>
<h2>11 5, 1912</h2>"",""<p>Democrat Woodrow Wilson defeats Taft and TR in the 1912 presidential election. Wilson wins the electoral college with 435 votes to TR's 88 and Taft's 8. In the popular vote, Wilson defeats TR by over 2 million votes, and Taft by almost 3 million, but TR musters the best third-party showing in history with 27 percent of the popular vote. In congressional elections, Democrats take a majority in the Senate, 51-44-1. In the House, Democrats enjoy a 291-127-17 lead. </p>
<h2>2 14, 1913</h2>"",""<p>Taft vetoes a bill calling for literacy tests for immigrants.  </p>
<h2>2 18, 1913</h2>"",""<p>General Victoriano Huerta overthrows Mexican President Madero. Taft refuses to intervene, despite the American public's calls for action. </p>
<h2>2 25, 1913</h2>"",""<p>The Sixteenth Amendment, originally passed in Congress on July 2, 1909, is finally ratified. Previous federal income tax laws had been struck down by the Supreme Courtóone in 1862 and another in 1894óon the grounds that they were "direct" taxes and could not be levied without breaching state apportionment. Prior to this amendment, tariff revenue had been the largest single source of government income. The debacle was finally resolved by the Thirteenth Amendment, which called for very low graduated rates on income (1-6 percent).</p>
<h2>3 1, 1913</h2>"",""<p>Over Taft's veto, Congress passes the Webb-Kenyon Interstate Liquor Act, which prohibits the shipment of liquor into "dry" states. </p>
<h2>3 4, 1913</h2>"",""<p>Congress divides the Department of Labor and Commerce into two separate departments, both with cabinet status. </p>
<h2>3 4, 1913</h2>"",""<p>Woodrow Wilson is inaugurated as the twenty-eighth President of the United States. The Tafts leave Washington for a vacation in Augusta, Georgia. </p>
