
"1841/04/04","","Day","After the death of President William Henry Harrison, Vice President John Tyler assumes the presidency. He is the first ever to do so, setting the precedent for presidential succession."
"1841/09/11","","Day","Tyler's entire cabinet, with the exception of Secretary of State Daniel Webster, resigns after Tyler vetoes a second bill for the establishment of a National Bank of the United States. "
"1842/08/09","","Day","The signing of the Webster-Ashburton Treaty normalizes U.S.-British relations by adjusting the Maine-Brunswick border, settling boundary issues around western Lake Superior, and resurveying numerous smaller borders. "
"1842/03/01","","Month","The Massachusetts Supreme Court establishes the legality of labor unions, including the right for workers to strike, in the case of <i>Commonwealth v. Hunt</i>. "
"1844/01/01","1845/12/31","Year","In the congressional elections, the Democrats gain a majority over the Whigs in the House of Representatives, while at the same time defending their majority in the Senate. "
"1844/04/12","","Day","The Texas Annexation Treaty is signed by the United States and the Republic of Texas. "
"1844/05/24","","Day","The first telegraph line in the United States is completed between Washington, D.C., and Baltimore. "
"1844/06/08","","Day","The Texas Annexation Treaty fails to gain the required two-thirds majority in the Senate amid controversy over the western expansion of the nation. "
"1844/06/26","","Day","President John Tyler marries Miss Julia Gardiner, becoming the first President to wed while in office. "
"1844/12/04","","Day","James K. Polk is elected as the eleventh President of the United States on promises to "re-annex" Texas and "re-occupy" Oregon. "
"1845/02/28","","Day","Congress passes the joint resolution (which only requires a simple majority by both houses) submitted by Tyler to annex Texas. The Republic of Texas votes to accept annexation on June 23. "
"1845/03/03","","Day","Florida is admitted as a slave state, making it the twenty-seventh state in the Union. "
"1845/03/04","","Day","James K. Polk is inaugurated as the eleventh President of the United States."
