
<h2>4 30, 1789</h2>"",""<p>George Washington inaugurated as the first President of the United States in New York City, the nation's capital.</p>
<h2>7 4, 1789</h2>"",""<p>Congress, led by Representative James Madison, enacts the first protective tariff.  Madison consulted with President Washington about the need for the measure.</p>   
<h2>3 26, 1790</h2>"",""<p>Congress passes the United States' first naturalization law, establishing terms of citizenship.</p>  
<h2>5 </h2>"",""<p>Rhode Island ratifies the Constitution, becoming the last of the original thirteen states under the Articles of Confederation to join the newly formed Union.</p>  
<h2>5 </h2>"",""<p>President Washington signs the first United States copyright law.</p>      
<h2>7 16, 1790</h2>"",""<p>President Washington signs a bill into law that permanently places the nation's capital along the Potomac River, in an area to be called the District of Columbia.</p>  
<h2>8 4, 1790</h2>"",""<p>President Washington signs a bill into law that directed the federal government to assume the Revolutionary War debts of the states.</p>    
<h2>12 6, 1790</h2>"",""<p>The United States Capital officially moves from New York to Philadelphia, where it remains until the completion of the District of Columbia in 1800.</p>  
<h2>12 13, 1790</h2>"",""<p>Secretary of the Treasury Alexander Hamilton, with President Washington's support, sends Congress a controversial message (The Report on a National Bank) calling for the creation of an official Bank of the United States. After a hard-won approval by Congress, Washington signs the bill on February 25, 1791.</p>  
<h2>3 3, 1791</h2>"",""<p>Congress approves its first internal revenue law, creating fourteen revenue districts and placing a tax on all distilled spirits.</p>   
<h2>9 9, 1791</h2>"",""<p>Commissioners name the territory within the District of Columbia (and the future seat of the Federal Government) the city of Washington in honor of the nation's first President.</p>  
<h2>11 4, 1791</h2>"",""<p>The Miami Indians soundly defeat an American military force of 1400 men led by General Arthur St. Clair at the cost of 900 American lives. The Washington Administration had sent St. Clair to the Ohio country with the hope that his presence would clear the way for American settlers.</p>  
<h2>12 15, 1791</h2>"",""<p>The states officially ratify the first ten amendments to the Constitution, also known as the Bill of Rights. President Washington had called for their ratification in his first inaugural address.</p>  
<h2>1 12, 1792</h2>"",""<p>President Washington appoints Thomas Pinckney as the first United States minister to England. Washington instructs him to convey a spirit of "sincere friendship" and to seek the liberation of American commerce from British regulations.</p>      
<h2>10 13, 1792</h2>"",""<p>The cornerstone for the President's mansion is laid in Washington D.C.</p>    
<h2>12 , 1792</h2>"",""<p>George Washington is unanimously re-elected President of the United States by the Electoral College. John Adams is elected for a second term as Vice President.</p>  
<h2>4 22, 1793</h2>"",""<p>President Washington issues a proclamation of neutrality, warning Americans to avoid aiding either side in the emerging conflict between Britain and revolutionary France.</p>     
<h2>5 </h2>"",""<p>President Washington cautiously receives France's envoy to the United States, Edmond Charles Genet. Washington fears that Genet wants to enlist U.S. aid in the conflict between Britain and France.</p>   
<h2>Fall, 1793</h2>"",""<p>American relations with Britain begin to deteriorate rapidly after the British government issues secret orders for the Royal Navy to confiscate any vessels trading with French possessions in the Caribbean. The Royal Navy seizes more than 200 American ships.</p>  
<h2>12 31, 1793</h2>"",""<p>Thomas Jefferson resigns as secretary of state. President Washington appoints Edmund Randolph as his successor.</p>  
<h2>3 , 1794</h2>"",""<p>Congress responds to British aggression by authorizing the production of six warships (March 11) and announcing a sixty-day embargo on American shipping (March 26). The Washington administration supports both measures.</p>    
<h2>4 16, 1794</h2>"",""<p>In the hopes of quelling mounting tensions between the United States and Britain, Washington selects Chief Justice of the Supreme Court John Jay to serve as a special envoy to Britain, in the hope that he can broker a deal with the British government to improve relations and address American grievances.</p>     
<h2>7 1794</h2>"11 1794",""<p>Farmers in western Pennsylvania rebel over the strict enforcement of an excise tax on whiskey passed in 1791. President Washington issues a proclamation on August 7 ordering the insurgents to return home. When this fails, he calls up more than 12,000 militiamen and dispatches them to Pennsylvania, whereupon the insurrection dissolves.</p>   
<h2>8 20, 1794</h2>"",""<p>General Anthony Wayne defeats an Indian force numbering more than 1,000 at the Battle of Fallen Timbers. The victory helps open the Ohio territory for American settlement and is a defeat for Britain, which had allied with the Native Americans in the region.</p>  
<h2>11 19, 1794</h2>"",""<p>John Jay concludes a treaty of Amity, Commerce and Navigation with Britain, known today as the Jay Treaty. Democrat-Republicans, and the American public in general, attack the treaty mercilessly as a betrayal of American interests, opening a fierce partisan political debate.</p>   
<h2>1 31, 1795</h2>"",""<p>Alexander Hamilton resigns from his post as secretary of the treasury. Washington appoints Oliver Wolcott to replace Hamilton.</p>    
<h2>6 24, 1795</h2>"",""<p>After fierce public debate, the Senate ratifies the Jay Treaty. President Washington signs the treaty on August 14.</p>      
<h2>10 27, 1795</h2>"",""<p>The United States signs the Treaty of San Lorenzo with Spain, granting Americans the right to ship goods through the port of New Orleans without having to pay duties to the Spanish Government.</p>   
<h2>11 , 1795</h2>"",""<p>The American Government, represented by David Humphreys, agrees to pay a sum of nearly a million dollars to the Dey of Algiers for protection of American shipping in the Mediterranean and for the ransom of sailors.</p>   
<h2>March–April, 1796</h2>"",""<p>A heated dispute erupts between President Washington and his Federalist allies and Democrat-Republicans in the House of Representatives after the latter demand that the President provide Congress with all papers relating to the Jay Treaty. Washington refuses their demands.</p>  
<h2>6 1, 1796</h2>"",""<p>Congress grants Tennessee's application for statehood, allowing it to become the 16th state in the Union.</p>  
<h2>7 , 1796</h2>"",""<p>France informs James Monroe, America's leading diplomat in Paris, that the Jay Treaty violates, and therefore suspends, certain provisions of the 1778 Treaty of Amity and Commerce between the two nations. This begins a serious diplomatic crisis between France and the United States.</p>  
<h2>9 19, 1796</h2>"",""<p>President Washington releases what has become known as his "Farwell Address," in which he advises future American leaders to minimize "political connection" with foreign powers.</p>   
<h2>11 4, 1796</h2>"",""<p>In an agreement resembling the one signed with the Dey of Algiers in 1795, the American government signs a treaty with Tripoli, agreeing to pay a yearly tribute to the Pasha of Tripoli in exchange for the peaceful treatment of U.S. shipping in the Mediterranean region.</p>   
<h2>12 , 1796</h2>"",""<p>John Adams is elected President of the United States. Thomas Jefferson, the candidate with the second highest electoral vote, becomes vice president.</p>  
<h2>1 , 1797</h2>"",""<p>France refuses to accept Monroe's replacement, Charles Cotesworth Pinckney, as American envoy to France, worsening relations between the two nations.</p>  
<h2>3 4, 1797</h2>"",""<p>John Adams is inaugurated as the second President of the United States, thereby officially ending the presidency of George Washington. Washington retires to his home at Mount Vernon.</p>  