
"1913/03/04","","Day",<p>Woodrow Wilson is inaugurated as the twenty-eighth President of the United States. He proclaims it his duty "to cleanse, to reconsider, to restore, to correct the evil without impairing the good, to purify and humanize every process of our common life without weakening or sentimentalizing it."</p>
"1913/03/04","","Day",<p>Congress divides the Department of Commerce and Labor into two departments, with each having cabinet status. </p>
"1913/04/08","","Day",<p>President Wilson appears before Congress to speak about revising tariffs.  Not since John Adams in 1800 had a President addressed Congress personally. </p>
"1913/05/02","","Day",<p>President Wilson extends official recognition to the new Republic of China. </p>
"1913/05/14","","Day",<p>In one of the largest philanthropic acts in American history, John D. Rockefeller donates $100,000,000 to begin the Rockefeller Foundation. </p>
"1913/05/19","","Day",<p>In a discriminatory measure against the Japanese, Gov. Hiram W. Johnson signs the Webb Alien Land-Holding Law, prohibiting Japanese ownership of land in California. The statute is enacted despite the objection of President Wilson and the Japanese Government. </p>
"1913/05/31","","Day",<p>The Seventeenth Amendment to the U.S. Constitution is enacted, providing for the direct popular election of U.S. senators. Previously, senators were chosen by their respective state legislatures. This amendment succeeds in diminishing the prestige of state governments and enhances popular control of the federal legislature. </p>
"1913/04/01","","Month",<p>The Ford Motor Company institutes the first automobile assembly line to produce the Model T. Company founder Henry Ford breaks precedence and pays his line workers $5 a day, believing that higher wages would lead to greater worker productivity and loyalty. </p>
"1913/08/27","","Day",<p>After considerable political instability in Mexico, following the assassination of President Francisco Madero, President Wilson declares the United States policy towards Mexico to be one of "watchful waiting." Wilson refuses to recognize the new government of General Victoriano Huerta, who led the coup against Madero on February 22. </p>
"1913/10/03","","Day",<p>President Wilson signs the Underwood-Simmons Tariff Act, considerably reducing rates set by previous Republican administrations. </p>
"1913/10/10","","Day",<p>From the White House, President Wilson detonates a charge to destroy the Gamboa Dike in Panama, leading to the completion  of the Panama Canal. </p>
"1913/12/10","","Day",<p>The Nobel Prize Committee selects Elihu Root, Theodore Roosevelt's secretary of state from 1905 to 1909, as the recipient of the Nobel Peace Prize for his work as president of the Carnegie Endowment for International Peace. </p>
"1913/12/23","","Day",<p>In an effort to safeguard America's financial institutions, the American economy, and the supply of U.S. currency, the Federal Reserve Act is signed into law. In contrast to the economies of Europe, the U.S. economy had functioned without the sophisticated management of banking ever since Andrew Jackson destroyed the Second Bank of the United States in 1830. The Federal Reserve Act created a Federal Reserve System, comprised of a Federal Reserve Board, twelve regional reserve banks, and the underpinnings of a smooth central banking system. </p>
"1914/04/09","","Day",<p>In the port of Tampico, Mexican officials detain several U.S. Marines from the <i>U.S.S. Dolphin</i>. Despite the their quick release and an expression of regret by President Victor Huerta, U.S. Admiral Henry T. Mayo demands that Mexican troops salute an American flag as a sign of contrition. President Huerta refuses the demanded salute on April 11; three days later President Wilson orders American warships to Tampico Bay. </p>
"1914/04/19","","Day",<p>In order to "obtain from General Huerta and his adherents the fullest recognition of the rights and dignity of the United States," President Wilson requests authorization from Congress to use force in Mexico. After some debate, both houses sanction such force on April 22. </p>
"1914/04/21","","Day",<p>At Vera Cruz, Mexico, U.S. forces seize the customhouse. Marines occupy the city and a detachment is sent to exact an apology from President Huerta for the arrest of several drunken U.S. sailors earlier in the month. </p>
"1914/04/25","","Day",<p>President Wilson accepts the offer of arbitration presented by the "ABC Powers" of Argentina, Brazil, and Chile to resolve the Tampico controversy. The mediation proves unnecessary when Mexican President Huerta is forced to resign on July 15. </p>
"1914/05/07","","Day",<p>Congress establishes Mother's Day as the second Sunday in May. </p>
"1914/05/08","","Day",<p>Congress passes The Smith-Lever Act, providing federal funds for agricultural instruction for farmers and state college students. </p>
"1914/06/28","","Day",<p>A Serbian nationalist assassinates Archduke Francis Ferdinand of Austria in Sarajevo, Serbia. This event serves as the proximate cause for the termination of diplomatic relations among the major European nations. One month later, Austria-Hungary declares war on Serbia. </p>
"1914/08/04","","Day",<p>Germany launches war on Belgium, France, and Great Britain. The United States declares its official neutrality as the Great War begins. </p>
"1914/08/15","","Day",<p>The Panama Canal officially opens after decades of toil, controversy, and diplomatic maneuvering. </p>
"1914/09/26","","Day",<p>President Wilson signs legislation establishing the Federal Trade Commission, which is designed to regulate business conglomeration. </p>
"1914/10/14","","Day",<p>Signing the Clayton Anti-trust Act, President Wilson advances the third legócorporate regulationóof his "New Freedom" program. The law strengthens the original Sherman Anti-trust Act of 1890 by prohibiting exclusive sales contracts, predatory pricing, rebates, inter-corporate stock holdings, and interlocking directorates in corporations capitalized at $1 million or more in the same area of business. The act restricts the use of the injunction against labor, and it legalizes peaceful strikes, picketing, and boycotts. </p>
"1914/11/03","","Day",<p>Democrats gain five seats in the Senate giving them a 56-40 majority.  Democrats in the House fare worse, losing 61 seats. Nevertheless, Wilson's party retains a 230-196 majority with nine seats held by minor parties. </p>
"1914/11/23","","Day",<p>U.S. forces in Vera Cruz, Mexico, are withdrawn as a result of the resignation of Mexican President Huerta, who fails to win Wilson's support. </p>
"1915/01/02","","Day",<p>Congress approves a bill requiring literacy tests for all immigrants to the United States, although President Wilson vetoes the bill on January 28.  Proponents of immigration restriction argue that the United States is allowing too many ill-qualified immigrants into the country, and justify their positions by appealing to religious, ethno-cultural, or racial prejudice. </p>
"1915/01/25","","Day",<p>The first transcontinental telephone call is made by the same men who had made the original telephone call in 1876. Speaking from New York City, Alexander Graham Bell tells Dr. Thomas A. Watson in San Francisco, "Mr. Watson, come here, I want you." </p>
"1915/01/26","","Day",<p>Congress establishes Rocky Mountain National Park in Colorado. </p>
"1915/02/23","","Day",<p>Nevada signs an easy divorce bill, requiring only six months' residence for a divorce to take effect. </p>
"1915/05/07","","Day",<p>A German U-Boat torpedoes the British passenger liner <i>Lusitania</i> off the coast of Ireland. The American public recoils at the loss of 1,198 civilians, including 114 Americans. The Wilson administration issues a fiery response to Germany, holding that nation responsible for the loss of American lives and the violation of American neutrality. Eager to keep the United States at bay, Berlin promptly expresses its regret but claims that the British were illegally smuggling arms aboard the ship. </p>
"1915/06/03","","Day",<p>The District Court of New Jersey rules that U.S. Steel is a lawful corporation and not in violation of anti-trust laws. </p>
"1915/06/07","","Day",<p>William Jennings Bryan resigns as secretary of state in protest over the Wilson administration's handling of the <i>Lusitania</i> sinking. Bryan thinks Wilson is acting too boldly and calls on him to take a more moderate approach, banning American travel on belligerents' ships. Wilson names Robert Lansing acting secretary of state. </p>
"1915/07/21","","Day",<p>A third <i>Lusitania</i> note is dispatched to Germany, warning the nation that any consequent violation of American rights would be viewed as "deliberately unfriendly." </p>
"1915/07/29","","Day",<p>U.S. Marines land in Haiti to restore order after the assassination of Haitian president Vilbrun Guillaume Sam. With the country suffering seemingly endless political strife, Wilson justifies the intervention as an exercise in teaching Haitians "how to elect good men." </p>
"1915/09/16","","Day",<p>Haiti signs an agreement with the United States to become an American protectorate for ten years. U.S. forces would not leave Haiti until 1934, when President Franklin D. Roosevelt withdraws them in accordance with his "Good Neighbor" policy. </p>
"1915/10/15","","Day",<p>American bankers, organized under J.P. Morgan & Company, authorize a $500 million loan to the British and French governments. </p>
"1915/12/04","","Day",<p>Georgia grants the Ku Klux Klan a new state charter after decades of dormancy. </p>
"1915/12/18","","Day",<p>President Wilson marries Edith Bolling Galt in a Washington, D.C., ceremony. The two honeymoon briefly in Virginia. </p>
"1916/01/24","","Day",<p>In <i>Brushaber v. Union Pacific Railroad</i>, the federal income tax survives a Supreme Court challenge. </p>
"1916/01/28","","Day",<p>Wilson appoints Louis B. Brandeis to the Supreme Court. He is the first Jewish justice in American history. </p>
"1916/03/15","","Day",<p>General John Pershing begins a punitive expedition into Mexico, without the approval of the Mexican government, to capture Pancho Villa and his bandit force. Villa had staged raids along the U.S.-Mexico border after President Wilson failed to support his claims on the leadership of the Mexican government. </p>
"1916/05/01","","Month",<p>U.S. Marines land in Santo Domingo, Dominican Republic, to restore political stability. The American occupation continues until 1924. </p>
"1916/05/05","","Day",<p>Germany issues the "Sussex Pledge" after a U-Boat sinks another passenger ship, the French liner <i>Sussex</i>, without warning on April 24. Following protests from Washington about German unrestricted submarine attacks, the German government promises not to sink any more merchant ships without prior warning and without time for passengers and crew to abandon ship. </p>
"1916/06/03","","Day",<p>Congress passes the National Defense Act in response to deteriorating relations between Germany and the United States. The act bolsters the standing Army to 175,000 and the National Guard to 450,000. </p>
"1916/06/07","1916/06/10","Day",<p>New York Governor Charles Evans Hughes earns the nomination for President at the Republican National Convention. Delegates select Charles Warren Fairbanks of Indiana as Hughes' running mate. </p>
"1916/06/14","1916/06/16","Day",<p>Democrats re-nominate Woodrow Wilson and vice president Thomas Marshall at their national convention. </p>
"1916/06/17","","Day",<p>After U.S. forces enter his country, the Mexican consul at Brownsville, Texas, issues an ultimatum for their withdraw. Four days later, on June 21, American troops come under fire from Mexican forces in Carrizal with seventeen troops killed or wounded. </p>
"1916/07/17","","Day",<p>President Wilson signs the Federal Farm Labor Act, establishing a banking system for farmers to improve their holdings. </p>
"1916/07/22","","Day",<p>A bomb explodes in San Francisco during a Preparedness Day parade, killing ten and wounding forty. Labor leaders Tom Mooney and Warren K. Billings are convicted in the case on dubious evidence in 1917. Mooney, originally sentenced to death, would be pardoned in 1939; Billings would be released in 1940. </p>
"1916/07/30","","Day",<p>An ammunition depot explodes and destroys docks at Toms River Island near Jersey City, New Jersey. Investigators blame German saboteurs in for the attack and for an explosion at a munitions plant in Kingsland, New Jersey, on January 17, 1917. </p>
"1916/08/04","","Day",<p>The U.S. and Denmark sign a treaty for the purchase of the Danish West Indies for $25 million. </p>
"1916/08/25","","Day",<p>The National Park Service is established under the Department of the Interior. </p>
"1916/09/03","","Day",<p>President Wilson signs the Adamson Eight-Hour Act, mandating an eight-hour day standard for most railroad workers. </p>
"1916/10/16","","Day",<p>Margaret Sanger, Fania Mindell, and Ethel Burne open the nation's first birth control clinic in Brooklyn, New York. </p>
"1916/11/07","","Day",<p>Woodrow Wilson is reelected President of the United States by a 23-vote margin in the Electoral College. Wilson staves off stiff competition from Charles Evans Hughes, winning a 49.6 percent majority of the popular vote versus Hughes' 46.1 percent. Wilson runs on the slogan "He kept us out of War" despite the growing implausibility of U.S. neutrality in the Great War. The election hinged on Wilson's slim 4,000-vote majority in California, where Hughes' loss of support from Governor Hiram Johnson may have cost him the election. In congressional elections, the Democrats maintain a 53-42 majority in the Senate and a thin 216-210 majority in the House of Representatives. </p>
"1916/12/18","","Day",<p>In an effort to mediate a settlement to the battlefield stalemate in Europe, President Wilson dispatches identical peace notes to all the belligerents, asking for the war aims of each. </p>
"1917/01/22","","Day",<p>President Wilson criticizes the European powers' war aims in a speech in the Senate, urging the combatants to accept "peace without victory" to ensure a settlement free of rancor that could ignite another war. </p>
"1917/01/28","","Day",<p>The War Department recalls U.S. forces under General Pershing from Mexico after searching in vain for Pancho Villa for almost a year. </p>
"1917/01/31","","Day",<p>The German government informs the United States that its naval forces will resume unrestricted submarine warfare in the Atlantic the next day. </p>
"1917/02/03","","Day",<p>In reaction to the German resumption of unrestricted attacks against merchant shipping, the United States severs diplomatic relations with Germany. </p>
"1917/02/05","","Day",<p>Congress overrides President Wilson's veto of the Immigration Act, which requires a literacy test for immigrants and restricts the entry of Asian laborers not covered by separate diplomatic agreements. </p>
"1917/02/24","","Day",<p>British officials present Walter Hines Page, U. S. ambassador to Great Britain, with a coded message from German foreign minister Alfred Zimmerman to the German ambassador of Mexico. The note instructs its recipient to seek a German-Mexican alliance in the event of war with the United States, and authorizes the German ambassador to offer the Mexican government the return of territory it lost to the United States in the Mexican-American war in return for Mexican military involvement. </p>
"1917/03/01","","Day",<p>The White House releases the contents of the Zimmermann Telegram to the press, three days after Wilson asks Congress for the authority to arm merchant ships. </p>
"1917/03/04","","Day",<p>President Woodrow Wilson and Vice President Thomas Marshall are inaugurated for second terms. In his inaugural address, Wilson reiterates the U.S. stance on neutrality but clearly hints at the almost certain likeliness of American intervention in the World War. Wilson declares that "The tragic events of the thirty months of vital turmoil through which we have just passed have made us citizens of the world. There can be no turning back. Our own fortunes as a nation are involved whether we would have it so or not." </p>
"1917/04/02","","Day",<p>The first woman in the House of Representatives, Rep. Jeannette Rankin (R-MT), is seated. </p>
"1917/04/02","","Day",<p>As the 65th Congress opens its first session, President Wilson asks for a declaration of war against Germany. Wilson argues that the United States needs to wage war to "make the world safe for democracy." </p>
"1917/04/04","1917/04/06","Day",<p>Congress debates and votes on a declaration of war against Germany. The Senate approves the declaration on April 4 by a vote of 82-6; on April 6, the House of Representatives passes the resolution by a vote of 373-50. Wilson signs the declaration on April 6. </p>
"1917/04/14","","Day",<p>President Wilson issues an executive order creating the Committee on Public Information and appoints Denver journalist George Creel as its head. The CPI coordinates propaganda and censorship efforts for the federal government throughout the war. </p>
"1917/04/24","","Day",<p>President Wilson signs a bill instituting the first Liberty Loan drive, authorizing Secretary of Treasury William G. McAdoo to sell $3 billion of debt at 3.5 percent to the public. </p>
"1917/05/18","","Day",<p>Congress passes the Selective Service Act, requiring all men between the ages of 21 and 30 to register with locally administered draft boards for a federal draft lottery. It is the first conscription act in the United States since the Civil War. </p>
"1917/06/15","","Day",<p>Congress approves the Espionage Act, which President Wilson had requested in his April 2 speech. The act severely limits freedom of expression, mandating that public criticism of the military or the government be punished by a $10,000 fine or up to twenty years in jail. </p>
"1917/06/26","","Day",<p>The first U.S. troops arrive in France at St. Nazaire. </p>
"1917/09/05","","Day",<p>Federal agents stage raids against the Industrial Workers of the World (IWW) in twenty-four cities, seizing literature and arresting ten, including William "Big Bill" Haywood. </p>
"1917/11/03","","Day",<p>The first engagement involving U.S. forces in Europe takes place near the Rhine-Marne Canal in France. </p>
"1917/11/06","","Day",<p>Women in New York receive the franchise in accordance with a state constitutional amendment. </p>
"1917/11/30","","Day",<p>The U.S. 42nd "Rainbow Division" arrives in France, comprised of troops from every state in the Union. Colonel Douglas MacArthur proclaims, "The 42nd Division stretches like a Rainbow from one end of America to the other." </p>
"1917/12/18","","Day",<p>Congress submits the Eighteenth Amendment to the U.S. Constitution to the states for ratification. The amendment forbids the sale, manufacture, or transport of alcohol except under special circumstances. </p>
"1918/01/08","","Day",<p>In an address to Congress, President Wilson lists his "14 Points" for a just and lasting peace. His objectives include the self-determination of nations, free trade, disarmament, a pact to end secret treaties, and a league of nations to realize collective security. This speech becomes the basis for Wilson's peace proposals at the end of the war. </p>
"1918/01/26","","Day",<p>To promote food conservation, food administrator Herbert Hoover calls for one meatless day, two wheatless days, and two porkless days each week. </p>
"1918/05/16","","Day",<p>Congress passes the Sedition Act, which couples with the Espionage Act to limit freedom of expression during the war. The Sedition Act grants the Postmaster General the right to ban the mailing of publications deemed subversive, and erects heavy penalties for those criticizing the government or the war effort. </p>
"1918/05/29","","Day",<p>President Wilson issues an executive order creating the War Industries Board, an agency designed to coordinate wartime production and transportation. </p>
"1918/06/04","","Day",<p>The U.S. Second Division blunts a German advance on Paris at Chateau-Thierry. </p>
"1918/06/06","1918/06/25","Day",<p>The U.S. Second Division and Fourth Marine Brigade counter a German offensive in the battle of Belleau Wood. </p>
"1918/08/29","","Day",<p>The Labor Department announces that the cost of living jumped seventeen percent in New York City from July 1917 to July 1918. </p>
"1918/09/14","","Day",<p>Prominent socialist and presidential candidate Eugene V. Debs is sentenced to a ten-year jail term for violating the Espionage Act, the result of an antiwar speech he delivered in Canton, Ohio, on June 30. </p>
"1918/09/30","","Day",<p>President Wilson addresses the Senate with the message that women's suffrage was a "vitally necessary war measure." </p>
"1918/10/01","","Month",<p>The world-wide influenza epidemic reaches its height in the United States.  The extremely virulent strain of the disease first develops in east-coast cities and spreads rapidly across the country and the Atlantic as a result of war-related transportation. The epidemic eventually claims more than 600,000 lives in the United States and perhaps 20 million globally. </p>
"1918/11/05","","Day",<p>Republicans win majorities in both houses of Congress, securing a two-seat majority in the Senate and a comfortable cushion of fifty votes in the House. </p>
"1918/11/09","","Day",<p>Kaiser Wilhelm II abdicates the throne of the German Empire after revolution breaks out in Germany. </p>
"1918/11/11","","Day",<p>Allied and German military leaders implement an armistice. The new German government issues an appeal to President Wilson to negotiate peace along the lines he enumerated in his Fourteen Points speech. </p>
"1918/11/18","","Day",<p>Wilson announces he will attend the Paris Peace Conference. </p>
"1918/11/21","","Day",<p>President Wilson signs the Wartime Prohibition Act, banning the manufacture of alcohol for domestic sale effective from June 30, 1919, until demobilization. </p>
"1919/01/18","","Day",<p>The Paris Peace Conference opens, two weeks after President Wilson receives glowing welcomes in Rome and Paris. </p>
"1919/01/29","","Day",<p>The State Department announces the ratification of the Eighteenth Amendment to the Constitution as of January 16, 1919, when Nebraska's approval achieved the amendment's required three-fourths majority. A nation-wide ban on the sale, distribution, or production of alcoholic beverages will go into effect on January 16, 1920. </p>
"1919/02/14","","Day",<p>President Wilson presents his draft for the League of Nations covenant to the Paris Peace Conference. </p>
"1919/03/03","","Day",<p>The Supreme Court upholds the constitutionality of the Espionage Act in <i>Schenck v. United States</i>, establishing that civil liberties can be restricted by the government if there is a "clear and present danger" to law and order. </p>
"1919/05/19","","Day",<p>Congress adopts the Nineteenth Amendment to the U.S. Constitution, giving women the franchise. The joint resolution reads: "The right of citizens of the U.S. to vote shall not be denied or abridged by the United States or by any State on account of sex." </p>
"1919/07/10","","Day",<p>After failing to secure a peace without rancorous provisions from his fellow Allied leaders, President Wilson submits the Treaty of Versailles and League of Nations to the Senate for ratification. Senatorial deliberation on the treaty will last longer than the Paris Conference itself. </p>
"1919/08/31","","Day",<p>The Communist Labor Party of America is founded in Chicago and adopts the platform of the Third International as its own. </p>
"1919/09/04","","Day",<p>Against the advice of his doctors and advisors, President Wilson opens his nation-wide speaking tour to promote the Treaty of Versailles and the League of Nations in Columbus, Ohio. </p>
"1919/09/09","","Day",<p>Police in Boston walk out on strike. </p>
"1919/10/02","","Day",<p>President Wilson suffers a serious stroke in Wichita, Kansas, in the middle of his national speaking tour and returns to Washington, DC. </p>
"1919/10/28","","Day",<p>Congress passes the Volstead Act over President Wilson's veto to provide enforcement power to the Eighteenth Amendment. </p>
"1919/11/19","","Day",<p>After a lengthy national debate, the Treaty of Versailles fails to achieve ratification in the Senate by a vote of 53 to 38. </p>
"1919/12/22","","Day",<p>Foreign-born radicals arrested by the Department of Justice in the "Red Scare" raids of 1919 are deported, leaving from New York harbor on the U.S. transport <i>Buford</i>, popularly referred to as the "Soviet Ark," bound for the U.S.S.R. </p>
"1920/01/02","","Day",<p>Attorney General A. Mitchell Palmer stages the most extensive series of raids of the entire "Red Scare," arresting nearly 2,700 people in 33 cities. </p>
"1920/03/19","","Day",<p>The Senate defeats a resubmitted version of the Treaty of Versailles with reservations added by Foreign Relations Committee chairman Henry Cabot Lodge. </p>
"1920/04/01","","Day",<p>U.S. forces cease their operations in support of counter-revolutionary forces in Siberia and are withdrawn. </p>
"1920/04/15","","Day",<p>Shoe factory employees Frank Parmenter and Alexander Berardelli are murdered in a robbery in South Braintree, Massachusetts. Immigrant laborers Nicola Sacco and Bartolomeo Vanzetti are arrested three weeks later for the crimes in what becomes one of the most politically charged murder cases of the early twentieth century. </p>
"1920/05/20","","Day",<p>Congress passes a joint resolution declaring an end to the war with Germany. President Wilson vetoes the resolution. </p>
"1920/06/08","1920/06/12","Day",<p>Republicans gather in Chicago to select candidates for the presidential and vice presidential elections. After party leaders break the convention deadlock in what one attendee calls a behind-the-scenes deal "in a smoke-filled room," Ohio Senator Warren G. Harding is nominated for the presidency. Massachusetts governor Calvin Coolidge receives the vice-presidential nomination. </p>
"1920/06/28","","Day",<p>Ohio governor James M. Cox and Franklin Delano Roosevelt of New York receive the nominations for President and vice president at the Democratic National Convention in San Francisco. </p>
"1920/08/26","","Day",<p>The Nineteenth Amendment, granting women the right to vote, officially becomes law. </p>
"1920/08/28","","Day",<p>In a speech given from his front porch in Marion, Ohio, Harding denounces the League of Nations. </p>
"1920/11/02","","Day",<p>Warren G. Harding is elected the twenty-ninth President of the United States with an overwhelming 404 electoral votes (60.3 percent of the popular vote to Democratic rival James Cox's 127 electoral votes (only 34.1 percent of the popular vote). Eugene V. Debs garners nearly one million popular votes for the Socialist Party despite his imprisonment for violating the Espionage Act the previous year. The election splits the North and South, with Cox winning all states (except for Tennessee) below the Mason-Dixon line and Harding winning the rest. </p>
"1920/11/20","","Day",<p>Woodrow Wilson wins the Nobel Peace Prize for his efforts to secure a lasting peace after the Great War. </p>
"1921/01/13","","Day",<p>The U.S. Census Bureau reports that for the first time in American history, 51 percent of Americans live in cities and towns of more than 2500 people. </p>