
<h2>11 7, 2000</h2> <p>Americans votes in the 2000 presidential election. Vote differentials in several states are exceedingly close, with the Democratic and Republican candidates disputing many of those counts, leaving the final result inconclusive.</p> 
<h2>12 12, 2000</h2> <p>In a 5-4 ruling, the U.S. Supreme Court stops the recount of votes in several contested Florida counties. The Democratic candidate, Vice President Albert Gore Jr., concedes the election, leaving Governor George W. Bush of Texas, the Republican candidate, as President-elect.</p>
<h2>1 20, 2001</h2> <p>George W. Bush is inaugurated as the 43rd President of the United States. He is the second son of a President to occupy the Oval Office, the first being John Quincy Adams in 1825.</p>
<h2>1 22, 2001</h2> <p>In one of his first policy decisions, President Bush decides to reinstate the ban on aid to international groups performing or counseling on abortion. The ban was initiated by former President Ronald Reagan but is not enforced during the administration of President Bill Clinton.</p>
<h2>1 29, 2001</h2> <p>By executive order, President Bush creates the Office of Faith-Based and Community Initiatives. The new office will work to ease regulations on religious charities and promote grass-roots efforts to tackle community issues such as aid to the poor and disadvantaged.</p>
<h2>2 16, 2001</h2> <p>United States airplanes attack Iraqi radar sites to enforce a &ldquo;no-fly zone.&rdquo; Bush calls the military action a &ldquo;routine mission.&rdquo;</p>
<h2>3 29, 2001</h2> <p>The Bush administration affirms its decision to abandon ratification of the Kyoto Protocol, an international treaty signed by 180 countries to reduce global warming that set limits on industrial emissions.</p>
<h2>4 1, 2001</h2> <p>A U.S. spy plane flying over the South China Sea is clipped by a Chinese fighter jet, forcing the American plane to make an emergency landing on Chinese soil. The incident strains diplomatic ties between the two nations as the United States demands that China return both the plane and its crew to American authorities.</p>
<h2>4 4, 2001</h2> <p>The Miami Herald and USA Today release a comprehensive review of the 2000 presidential election recount efforts in Florida. The review shows that even if Democratic candidate Al Gore had succeeded in getting the recounts he wanted, President Bush would have won Florida by 1,665 votes.</p>
<h2>4 25, 2001</h2> <p>President Bush signals a change in relations with China by officially pledging military support for Taiwan in the event of an attack by China. This is the first time a presidential administration has publicly acknowledged a position that had previously been implicitly accepted.</p>
<h2>5 7, 2001</h2> <p>President Bush signs a $1.35 trillion tax cut into law. Although the amount falls short of the $1.60 trillion the administration has been seeking, the bill does slash income tax rates across the board and provides for the gradual elimination of the estate tax.</p>
<h2>5 9, 2001</h2> <p>President Bush addresses the nation, outlining his plans for the federal funding of stem cell research. The new policy allows for government funding of research on already extracted stem cells but prohibits the extraction of additional stem cells from human embryos.</p>
<h2>5 11, 2001</h2> <p>Terrorists hijack four commercial jets and crash them into the World Trade Center in New York City, the Pentagon in Washington, D.C., and the Pennsylvania countryside. It is the worst attack on American soil since Pearl Harbor, with fatalities numbering about 3,000. Addressing the nation twelve hours after the attacks, President Bush vows to hunt down those responsible. </p>
<h2>5 20, 2001</h2> <p>President Bush appears before a joint session of Congress to outline the administration&rsquo;s plans to defeat world terrorism, singling out Osama bin Laden and his al-Qaeda organization as the primary targets of such a policy. He states that every nation must take sides in the international conflict against worldwide terrorist networks; he also warns Americans to prepare for a protracted campaign against terrorism. The President then appoints Pennsylvania governor Tom Ridge to the new cabinet-level post of director of the Office of Homeland Security. Governor Ridge will coordinate the efforts of more than forty federal agencies to secure the United States against future terrorist attacks.</p>
<h2>10 7, 2001</h2> <p>Speaking from the Treaty Room of the White House, President Bush announces the commencement of military action in Afghanistan, an operation code-named &ldquo;Enduring Freedom.&rdquo;</p>
<h2>10 17, 2001</h2> <p>The Capital shuts down amidst an Anthrax scare. Persons in Florida and New York have already tested positive for the frequently fatal bacteria. Bush calls for $1.5 billion to fight bioterrorism.</p>
<h2>12 2, 2001</h2> <p>The Enron Corporation files for Chapter Eleven bankruptcy protection, the largest bankruptcy case in American history. The beleaguered company, once the world&rsquo;s premier energy trading and services firm, files for court protection after watching its stock price plummet as a result of accounting issues relating to its operations. Earlier in the year, discoveries reveal that Enron&rsquo;s chief financial officer engaged in partnerships which allowed the company to hide half a billion dollars worth of debt. The Bush administration has ties to key Enron executives, including CEO Kenneth Lay, but denies any involvement in the scandal.</p>
<h2>12 13, 2001</h2> <p>After conferring with the National Security Council, President Bush notifies Russia of his intention to withdraw from the 1972 Anti-Ballistic Missile Treaty. Meetings with Russian president Vladimir Putin fail to establish an agreement between the two nations. In June 2002, the United States officially withdraws from the Treaty, allowing it to conduct anti-missile defense tests.</p>
<h2>1 8, 2002</h2> <p>President Bush signs a landmark education reform bill into law. Known as the No Child Left Behind Act, it offers local authorities greater flexibility in spending federal dollars, but requires standardized math and reading tests.</p>
<h2>1 29, 2002</h2> <p>In his State of the Union address, President Bush warns that the war against terrorism is only beginning. Specifically citing North Korea, Iran, and Iraq, Bush speaks of &ldquo;an axis of evil&rdquo; threatening world peace. </p>
<h2>4 4, 2002</h2> <p>Secretary of State Colin Powell travels to the Middle East for talks with Israel and Palestinian leader Yasser Arafat.</p>
<h2>3 22, 2002</h2> <p>Bush renews his call on Palestinian leader Yasser Arafat to end attacks on Israel, indicating that a meeting with Vice President Dick Cheney could still take place if Arafat yielded to American demands. Cheney, on a trip to the Middle East, refuses to meet with Arafat in the current environment. Meanwhile, Arafat remains penned in Ramallah by Israeli threats since December. On March 29, Israeli troops will take over most of his headquarters.</p>
<h2>5 12, 2002</h2> <p>Former President Jimmy Carter travels to Cuba for a tour and visit with Cuban President Fidel Castro. His arrival marks the first trip by an American President in forty years. On May 20, President Bush announces that the forty-year-old trade embargo against Cuba will continue until conditions, including free and fair elections, are met.</p>
<h2>5 16, 2002</h2> <p>Congress presses the Bush administration for further information about warnings of the September 11, 2001, attacks. National Security Advisor Condoleezza Rice holds a briefing, maintaining, &ldquo;I don&rsquo;t think that anybody could have predicted that these people would take an airplane and slam it into the World Trade Center, take another one and slam it into the Pentagon.&rdquo; She insists that there was no lapse in intelligence.</p>
<h2>5 24, 2002</h2> <p>At the Kremlin, President Bush and Russian president Vladimir Putin sign a nuclear arms treaty, vowing to reduce their nations&rsquo; arsenals by two-thirds over the next ten years.</p>
<h2>5 6, 2002</h2> <p>In a televised address to the nation, President Bush announces broad changes to security departments in charge of protecting the nation from terrorism. The Office of Homeland Security will now coordinate a wide range of functions and oversee more than 100 organizations. The announcement follows criticism of the FBI and CIA for failing to prevent the September 11 attacks.</p>
<h2>5 24, 2002</h2> <p>President Bush calls for the Palestinian people to replace Yasser Arafat, head of the Palestinian Authority and leader of the Palestinian cause for more than thirty years. Bush states that &ldquo;when the Palestinians have new leaders, institutions and security arrangements, the U.S. will support the creation of a Palestinian state.&rdquo;</p>
<h2>5 8, 2002</h2>  <p>Following the Enron and WorldCom scandals, in which both companies claimed profits which turned out to be highly inflated, President Bush calls for new laws on corporate abuse. On July 10, the Dow Jones index drops below 9,000, its largest one-day loss since September 2001.</p>
<h2>5 4, 2002</h2> <p>Seeking support for action against Iraq, President Bush addresses Congress, identifying Iraqi strongman Saddam Hussein as &ldquo;a serious threat.&rdquo; Bush mentions the concept of a regime change and announces the visit of British Prime Minister Tony Blair in the days to come. House Majority Whip Tom DeLay (R-TX) calls action in Iraq &ldquo;inevitable.&rdquo;</p>
<h2>5 12, 2002</h2> <p>President Bush addresses the United Nations&rsquo; Security Council, making his case for military action to enforce UN resolutions in Iraq. Additionally, he warns that the United States will move alone if the Council does not act. In the coming days, Bush and Secretary of State Colin Powell will continue to press the Security Council for a resolution against Iraq. France, Germany, and Russia, all permanent members of the Security Council, express severe reservations.</p>
<h2>10 10, 2002</h2> <p>A bipartisan Senate vote of 77-23 gives authorization to Bush to use force against Iraq. The Senate vote follows a similar vote of 296-133 in the House in support of the bill.</p>
<h2>11 5, 2002</h2> <p>In a sweeping mid-term election victory, Republicans gain control of the Senate and maintain their edge in the House.</p>
<h2>12 20, 2002</h2> <p>Following a United Nations report issued by arms inspectors indicating that Iraq remained in violation of Security Council Resolution 1441, Bush speaks out again against Iraq. Inspections in Iraq continue.</p>
<h2>1 7, 2003</h2> <p>Bush reveals a tax-cut plan of $674 billion over ten years. He suggests that the plan will stimulate the U.S. economy, end the recession, and create jobs. Democrats dismiss the plan as financially irresponsible and favorable to the rich.</p>
<h2>2 1, 2003</h2> <p>The seven-member crew of the shuttle Columbia dies in an explosion in space. Debris falls in Texas.</p>
<h2>2 12, 2003</h2> <p>CIA director George Tenet announces that North Korea possesses a nuclear ballistic missile capable of hitting the United States. In the following weeks, reports emerge which suggest that North Korea will soon possess the ability to create a nuclear arsenal.</p>
<h2>3 16, 2003</h2> <p>After months of debate in the United Nations Security Council, President Bush announces the U.S. intention to move against Iraq with its coalition of allies. Bush issues an ultimatum for military action, giving Iraqi leader Saddam Hussein and his sons forty-eight hours to leave Iraq.</p>
<h2>3 19, 2003</h2> <p>The 8:00 p.m. deadline for Hussein to leave Iraq passes. At 10:15 p.m., Bush addresses the nation and informs the American people that the United States is at war with Iraq.</p>
<h2>3 25, 2003</h2> <p>Citing costs of the Iraq War, the Senate approves, by a vote of 51-48, the reduction of Bush&rsquo;s tax cut plan to $350 million, less than half of the original amount.</p>
<h2>4 10, 2003</h2> <p>President Bush and British Prime Minister Tony Blair air a joint address on Iraqi television that describes the goals of coalition forces and reassures the Iraqi people that they will be able to live their lives in peace and security in a post-Saddam era.</p>
<h2>5 1, 2003</h2> <p>In a nationally televised address aboard the aircraft carrier <em>USS Abraham Lincoln</em>, Bush stands in front of a &ldquo;Mission Accomplished&rdquo; banner and declares that major combat operations in Iraq are over. He links the Iraq War to the War on Terror and vows to continue searching for banned weapons in Iraq.</p>
<h2>5 22, 2003</h2> <p>The UN Security Council votes to lift sanctions on Iraq imposed since the 1991 Gulf War. The resolution gives the United States and United Kingdom control of Iraq until it establishes a legitimate government and authority to use Iraqi oil revenues for humanitarian aid and reconstruction.</p>
<h2>5 28, 2003</h2> <p>Bush signs into law his $350 billion tax-cut package, the third-largest in history, in an effort to strengthen the U.S. economy and reverse a trend of increasing unemployment. Congressional Democrats who opposed the bill argued it is skewed towards the wealthy.</p>
<h2>5 4, 2003</h2> <p>Bush meets with Israeli Prime Minister Ariel Sharon and Palestinian Prime Minister Mahmoud Abbas in Aqaba, Jordan, to discuss implementation of a &ldquo;road-map&rdquo; for peace.</p>
<h2>5 17, 2003</h2> <p>President Bush issues comprehensive guidelines forbidding federal law enforcement agencies from considering race or ethnicity in routine patrol duties. Although more extensive than previous federal law, the guidelines provided clear exceptions for matters of national security and counterterrorism operations.</p>
<h2>5 11, 2003</h2> <p>CIA Director George Tenet accepts full responsibility for the statement in Bush&rsquo;s 2003 State of the Union Address regarding Iraq&rsquo;s alleged effort to obtain uranium from Africa, saying its inclusion should not have been approved by the CIA because the intelligence was unsubstantiated and the claim had been discredited.</p>
<h2>5 22, 2003</h2> <p>U.S. forces kill Saddam Hussein&rsquo;s two sons Uday and Qusay in Mosul, Iraq. Officials hope that anti-U.S. attacks in Iraq will decrease as a result. Saddam Hussein&rsquo;s whereabouts are unknown.</p>
<h2>5 24, 2003</h2> <p>The joint Congressional Committee on Intelligence releases an 800-page document on the findings of its inquiry into intelligence failures leading up to the terrorist attacks of September 11, which concludes that intelligence agencies failed to respond to alerts about potential targets and methods. The report faults the NSA, CIA, and the FBI for a breakdown in communications and advocates the creation of a cabinet-level &ldquo;intelligence czar&rdquo; to remove obstacles between agencies.</p>
<h2>5 30, 2003</h2> <p>The Justice Department announces a full criminal investigation into allegations that Bush administration officials had leaked the name of a covert CIA operative to the media in July. Bush urges full cooperation with the probe.</p>
<h2>10 2, 2003</h2> <p>Chief U.S. Weapons Inspector David Kay reports that his 1,400 member team, the Iraq Survey Group, failed to find any biological, chemical, or nuclear weapons in Iraq. Kay acknowledged that they did find evidence that Iraq sought the capacity to create those weapons in the future. Bush used these findings as validation of his prewar claims that Iraq posed a significant security threat to the United States.</p>
<h2>11 5, 2003</h2> <p>Bush signs into law a ban on late-term abortion, the first law to ban an abortion procedure since the Supreme Court&rsquo;s 1973 decision in <em>Roe v. Wade</em>. The Supreme Court later upholds the ban.</p>
<h2>12 8, 2003</h2> <p>Bush signs a landmark bill overhauling Medicare that includes the program&rsquo;s first prescription drug benefits to begin in 2006 and creates incentives for private insurance companies to cover Medicare subscribers.</p>
<h2>12 18, 2003</h2> <p>Iran signs an agreement to grant unrestricted access to UN-IAEA weapons inspectors.</p>
<h2>1 20, 2004</h2> <p>Bush gives his fourth State of the Union Address, laying out a broad domestic and foreign policy agenda while stressing issues of national security.</p>
<h2>3 8, 2004</h2> <p>The Iraqi Governing Council signs an interim constitution to provide a framework for establishment of a transitional government.</p>
<h2>4 4, 2004</h2> <p>U.S. forces in Iraq confront a violent uprising beginning with Shiite Muslims in Baghdad and spreading to Sunni guerrillas in Fallujah, leading to the heaviest fighting since the invasion began in March of 2003.</p>
<h2>4 28, 2004</h2> <p>CBS broadcasts photographs of U.S. Army abuse of Iraqi prisoners in Abu Ghraib prison, a facility on the outskirts of Baghdad. Bush and other senior administration officials voice deep disapproval over these abuses.</p>
<h2>5 17, 2004</h2> <p>Massachusetts becomes the first state to offer marriage licenses to same sex couples. Bush reiterates to Congress his call for a constitutional amendment banning same sex marriage.</p>
<h2>5 3, 2004</h2>  <p>Bush announces he has accepted the resignation of CIA Director George Tenet, widely blamed for intelligence failures in the months leading up to September 11.</p>
<h2>5 8, 2004</h2> <p>Attorney General John Ashcroft appears before the Senate Judiciary Committee to answer questions regarding two leaked government memoranda that contained legal arguments for circumventing U.S. and international bans on torture, specifically for the questioning of terrorist suspects.</p>
<h2>5 28, 2004</h2> <p>The U.S.-led Coalition for Provisional Authority formerly ends foreign occupation of Iraq, granting the provisional government sovereignty. Still, 130,000 troops remain in Iraq.</p>
<h2>5 2, 2004</h2> <p>President Bush and Vice President Cheney are renominated as the Republican candidates at the GOP convention in New York City.</p>
<h2>5 30, 2004</h2> <p>Bush and Democratic nominee, Senator John Kerry, have their first of three presidential debates, this one focused on national security issues and foreign policy. The Bush administration&rsquo;s handling of the Iraq War is the main focus.</p>
<h2>10 8, 2004</h2> <p>Bush and Kerry have their second debate in a town-hall format in St. Louis, Missouri.</p>
<h2>10 13, 2004</h2> <p>Polls show the two candidates in a dead heat as Bush and Kerry meet for their third and final presidential debate on domestic policy.</p>
<h2>10 29, 2004</h2> <p>Qatar-based television channel Al-Jazeera airs excerpts from a videotape of Osama bin-Laden, leader of the terrorist network al-Qaeda, who addresses the American people. Many view this tape as an attempt by al-Qaeda to influence the U.S. presidential election.</p>
<h2>11 3, 2004</h2> <p>Bush wins a second term with 51 percent of the popular vote and 274 electoral votes to John Kerry&rsquo;s 252. The Republican Party builds slightly on its majority in the House and Senate.</p>
<h2>11 8, 2004</h2> <p>U.S. troops launch an assault to retake the rebel-controlled city of Fallujah in the largest military operation since the initial invasion in March of 2003.</p>
<h2>11 15, 2004</h2> <p>Retired Army general and Secretary of State Colin Powell resigns. Bush appoints former National Security Advisor Condoleezza Rice to the position.</p>
<h2>1 20, 2005</h2> <p>President Bush is sworn in for the second term of his presidency. </p>
<h2>2 2, 2005</h2> <p>In his State of the Union, President Bush calls for an historic restructuring of Social Security, allowing workers to use their payroll taxes to invest in the stock market. However, he is unable to move the policy through Congress. </p>
<h2>2 17, 2005</h2> <p>Bush names former U.S. Ambassador to Iraq John Negroponte Director of National Intelligence, a newly created position of &ldquo;intelligence czar&rdquo; created in the wake of Congressional investigations into intelligence failures leading up to September 11.</p>
<h2>2 20-24, 2005</h2> <p>Bush travels to Europe to meet with French President Jacques Chirac, German Chancellor Gerhard Schroeder, and Russian President Vladimir Putin to smooth diplomatic relations after the U.S.-led invasion of Iraq.</p>
<h2>3 31, 2005</h2> <p>Terri Schiavo, a Florida woman long-suffering from brain damage, dies following the removal of her feeding tube. Schiavo had been the focus of legal controversy between the wishes of her parents and those of her husband. Ten days earlier, President Bush had signed a law permitting Schiavo&rsquo;s parents to challenge the removal of her feeding tube in federal court.</p>
<h2>5 5, 2005</h2> <p>Iraqi government announces that a war crimes trial for Saddam Hussein is likely to begin within the next two months and prosecutors would seek the death penalty.</p>
<h2>5 10, 2005</h2> <p>South Korean President Roh Moo Hyun meets with Bush to discuss efforts to persuade North Korea to join the six-party talks intended to end North Korea&rsquo;s pursuit of nuclear weapons.</p>
<h2>5 21, 2005</h2> <p>Vietnamese Premier Phan Van Khai meets with Bush to discuss human rights and treatment of ethnic and religious minorities in Vietnam. This marks the first visit by a Vietnamese Premier to the United States since the country reunited under Communist rule in 1975.</p>
<h2>5 28, 2005</h2> <p>The Senate easily passes an omnibus energy bill aimed at supporting the traditional energy industries of oil and natural gas, but also provide tax incentives for the use of alternative energy sources such as solar and wind power.</p>
<h2>5 26, 2005</h2> <p>The space shuttle Discovery takes off from the Kennedy Space Center on a mission to deliver repairs to the International Space Station. This is the first U.S. space mission since the failed return of the Columbia in 2003.</p>
<h2>5 28, 2005</h2> <p>Hurricane Katrina strikes the southern coast of the United States with devastating effects. The storm breaches the levee system in New Orleans, causing massive flooding and destruction of property. The Bush administration is harshly criticized for an inadequate response by the federal government to the storm&rsquo;s destruction. </p>
<h2>5 29, 2005</h2> <p>John G. Roberts is confirmed as Chief Justice of the U.S. Supreme Court. Roberts replaces William Rehnquist, who died in office, and is President Bush&rsquo;s first nominee to the Court. </p>
<h2>1 26, 2006</h2> <p>The Senate Judiciary Committee approves President Bush&rsquo;s nomination of Samuel A. Alito, Jr., to the U.S. Supreme Court by a vote of 10-8. Previously, concerns were voiced over the disruption of the court&rsquo;s ideological balance that would result from Alito&rsquo;s replacement of moderate Sandra Day O&rsquo;Connor.</p>
<h2>3 21, 2006</h2> <p>In a White House news conference, President Bush admits for the first time that the complete removal of U.S. troops from Iraq during the remainder of his term is improbable. He continues to assert the fact that progress is being made in the establishment of Iraqi democracy. </p>
<h2>5 3, 2006</h2> <p>After several cases of avian influenza are reported in Central and Southeast Asia, the Bush administration proposes a plan to minimize losses in the case of a deadly pandemic. The plan includes coordination with the World Health Organization, reorganization of international travel, and the authorization of military assistance in the case of public unrest. </p>
<h2>5 4, 2006</h2> <p>The U.S. District Court in Alexandria, Virginia, sentences Zacarias Moussaoui to life in prison without parole for his role in the September 11, 2001, terrorist attacks. Moussaoui was the first person to stand trial for the attacks. </p>
<h2>5 7, 2006</h2> <p>The Senate votes 49-48 to conclude debate on a constitutional amendment banning same sex marriages in the United States, thereby preventing a vote on the actual passage of the amendment. President Bush had previously expressed support of the proposed amendment.</p> 
<h2>5 19, 2006</h2> <p>President Bush vetoes a bill to lift constraints on federal funding of embryonic stem cell research, and subsequently, the House unsuccessfully attempts to override the veto. This is the first veto Bush issues during his administration.</p>
<h2>10 26, 2006</h2> <p>President Bush signs a bill providing for the construction of a 700-mile fence along the United States-Mexico border, in an effort to increase border security and stem illegal immigration.</p>
<h2>11 7, 2006</h2> <p>Democrats recapture control of the U.S. House and Senate in the midterm elections. </p>
<h2>12 30, 2006</h2> <p>Former Iraqi President Saddam Hussein is hanged in Baghdad, Iraq, after being convicted of crimes against humanity dating back to 1982.</p> 
<h2>1 4, 2007</h2>  <p>Nancy Pelosi, a Democrat from California, takes office as the first female Speaker of the House. Democrats assume control of both the House of Representatives and the Senate.</p>
<h2>1 8, 2007</h2>  <p>The U.S. Air Force launches an air attack on Islamist militias and suspected al-Qaeda operatives in Somalia.</p>
<h2>1 11, 2007</h2> <p>Bush announces what would be termed a &ldquo;troop surge&rdquo; in Iraq in an attempt to increase security in the capital of Baghdad and smother insurgency centers throughout the country.</p>
<h2>2 10, 2007</h2> <p>General David Petraeus takes over command of the multinational forces in Iraq to oversee the surge.</p>
<h2>3 6, 2007</h2> <p>Scooter Libby, Vice President Cheney&rsquo;s chief of staff, is convicted of perjury and obstruction of justice in the case of CIA operative, Valerie Plame Wilson, whose covert identity was exposed. President Bush later commutes Libby&rsquo;s sentence.</p> 
<h2>4 16, 2007</h2> <p>Seung-Hui Cho kills himself and 32 fellow students at Virginia Tech in the deadliest campus gun rampage in U.S. history. President Bush and the First Lady attend the memorial. </p>
<h2>5 1, 2007</h2> <p>Bush vetoes a war spending bill passed by Congress, which set a timetable for troop withdrawal from Iraq. Within days Bush reaches a record low approval rating.</p>
<h2>5 29, 2007</h2> <p>The Supreme Court reverses an April decision and agrees to hear appeals from Guantanamo Bay detainees who have not had access to the federal courts.</p>
<h2>5 26, 2007</h2> <p>Congress passes the Antiterrorism Bill, which will allow for the screening of air and sea cargo and will give more money in government antiterrorism grants to states with the greatest risk for terrorist attacks.</p>
<h2>5 17, 2007</h2> <p>President Bush names Michael Mukasey as Attorney General after Alberto Gonzalez announces his resignation.</p> 
<h2>10 9, 2007</h2> <p>The Dow Jones industrial average closes at 14,164, its all-time high. Soon after, it begins a steep decline.</p>
<h2>11 27, 2007</h2> <p>President Bush hosts a Middle East Peace Conference in Annapolis, Maryland, with Prime Minister Ehud Olmert of Israel and Palestinian president Mahmoud Abbas.</p>
  
<h2>12 19, 2007</h2> <p>Congress passes new energy legislation to increase automobile fuel efficiency standards and mandates increases in biofuel production. The bill passes the House and Senate, and President Bush signs it into law. </p>
<h2>1 18, 2008</h2> <p>President Bush proposes a $145 billion stimulus package in response to a housing crisis and rapidly increasing oil prices. The package gives individuals several hundred dollars to facilitate spending, as well as rebates for children and tax deductions for businesses in order to jump-start the slowing economy.</p>
<h2>1 31, 2008</h2> <p>U.S. missile strikes in Pakistan kill a top al-Qaeda leader, Abu Laith al-Libi, who trained terror operatives in the region.</p>
<h2>2 1, 2008</h2> <p>The Bureau of Labor Statistics reports that the U.S. economy lost more than 15,000 jobs during the previous month. Such an elimination of jobs from the economy had not occurred for more than four years. </p>
<h2>2 7, 2008</h2> <p>The Senate passes a $170-billion stimulus package to give many Americans tax rebates as large as $600 or more, and to implement tax breaks for certain businesses in an effort to head-off impending economic slowdown.</p>
<h2>2 11, 2008</h2> <p>Six detainees at Guantanamo Bay who were thought to have had roles in orchestrating the September 11 terrorist attacks are charged with conspiracy, murder in violation of the law of war, terrorism, and other charges. All six face the death penalty in military tribunals. </p>
<h2>3 23, 2008</h2> <p>After a roadside bomb exploded in Baghdad, the U.S. death toll for the war in Iraq reached 4,000.</p>
<h2>5 9, 2008</h2> <p>The State Department renews a deal with Blackwater Worldwide, the private defense contractor whose guards killed 17 civilians in 2007, to provide defense for U.S. diplomats in the Middle East.</p>
<h2>5 22, 2008</h2> <p>The House and Senate override President Bush&rsquo;s veto of the Farm Bill, a $307 billion bill which will provide subsidies to farmers. More than $10 billion of the funds will go to expanding nutritional programs such as food stamps. Bush originally vetoed the bill, which he felt to be excessive.</p>
<h2>5 3, 2008</h2> <p>Democratic candidate Barack Obama secures the party&rsquo;s nomination for the presidency.</p>
<h2>5 5, 2008</h2> <p>The Senate Select Committee on Intelligence finds, after a five-year study, that President Bush and other officials greatly exaggerated the evidence showing that Saddam Hussein held weapons of mass destruction.</p>
<h2>5 30, 2008</h2> <p>In a new report issued on the situation in Iraq, the U.S. Army admits that while it was able to adequately topple Hussein&rsquo;s regime, it did not have the capability to rebuild Iraq into a fully-functioning new country.</p>
<h2>5 1, 2008</h2> <p>U.S. forces hand over control of Anbar Province to the Iraqi military and police, who will now be responsible for maintaining order there. </p>
<h2>5 7, 2008</h2> <p>The U.S. government places Fannie Mae and Freddie Mac under its control to prevent the institutions from going under and endangering more than half of the country&rsquo;s mortgages.</p>
<h2>10 1, 2008</h2> <p>Senate approves an end to the long-standing ban on trading nuclear fuels with India, who will be able to purchase fuel on the market as long as it is for civilian purposes.</p>
<h2>10 3, 2008</h2> <p>At the onset of financial crisis, President Bush signs a $700 billion bailout plan for failing bank assets, the largest in U.S. history.</p>
<h2>10 30, 2008</h2> <p>U.S. gross domestic product drops by 0.3 percent, the first time GDP has shrunk in 17 years.</p>
<h2>10 31, 2008</h2> <p>General David Petraeus takes over as Head of Central Command, overseeing all U.S. military operations in Iraq, Afghanistan, Pakistan, Syria, and Iran.</p>
<h2>11 4, 2008</h2> <p>Barack Obama is elected the next President of the United States in an historic election in which Democrats win in several traditionally Republican states and pick up seats in the House and Senate. Obama is the first African American elected President.</p>
<h2>11 25, 2008</h2> <p>The Treasury Department and the Federal Reserve agree to provide another $800 billion in lending programs to buy debt insured by Fannie Mae and Freddie Mac and to provide more small loans to consumers.</p>
<h2>12 16, 2008</h2> <p>Federal Reserve cuts interest rates to an all-time low of zero percent, down from 1 percent and 0.25 percent earlier in the year as part of a plan to stimulate the economy.</p>
<h2>12 19, 2008</h2> <p>President Bush issues a $17.4-billion auto bailout to General Motors and Chrysler to keep the two American automotive giants from going bankrupt.  </p>
<h2>1 20, 2009</h2> <p>Barack Obama is inaugurated the 44th President of the United States. President Bush leaves Washington, D.C., and settles in Dallas, Texas. </p>